### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by enociz** [dularion/streama#1]
Where can people find this online?

**Comment by APIUM** [comment]
You need to host it yourself.

**Comment by InstanceOfMichael** [comment]
> Where can people find this online?

https://github.com/dularion/streama

**Comment by dularion** [comment]
Yes, the purpose of this code is for self-hosting the application. Maybe one day in the future I can find a way to make something public out of this without getting into legal issues, but for now it is self-hosting only.

**Comment by enociz** [comment]
Okay, I didn't understand that, sorry.
