### ISSUE TITLE
TV Series browsing

### ISSUE THREAD

**Issue by Flex101** [dularion/streama#101]
The page you get when managing content for tv, which shows all the episodes, would be great for non-content managers (but obviously without the management functionality). It would allow them to browse the episodes without using the menu while watching a previous episode.

**Comment by phuicy** [comment]
seconded

**Comment by dularion** [comment]
Cool! Will work on that then :)

**Comment by asmartin** [comment]
+1 - I would really like this enhancement too!

**Comment by asmartin** [comment]
I tested this out and it looks great - thanks!

**Comment by dularion** [comment]
I'm glad!

**Comment by asmartin** [comment]
Would it be possible to make this popup box that displays the episodes have a unique URL, so I can create a bookmark that goes directly to it for a particular show?

**Comment by dularion** [comment]
ok thats a cool idea!

**Comment by asmartin** [comment]
I had a chance to test this out and it works great, thanks again!
