### ISSUE TITLE
Admin list all episodes/seasons for tv shows api request never ending and large data

### ISSUE THREAD

**Issue by camelCaseD** [dularion/streama#103]
See below:

![streamaadmin](https://cloud.githubusercontent.com/assets/1644022/11495335/38c90268-97bf-11e5-8c1f-ea39691d83a6.png)

It kept climbing up to 200mb before I left the page and cancelled the request

**Comment by dularion** [comment]
Wow .. that looks pretty bad! how many episodes do you have for that show? It shouldnt be 200mb at least.. I've looked into performance there already, and I will do more, but that seems more like a bug than anything else. Does this happen with any other show? Is there anything specific for that show that is worth mentioning and might bring me closer to a bugfix?

**Comment by camelCaseD** [comment]
The show has 220 episodes uploaded and about 4 seasons.

**Comment by camelCaseD** [comment]
I think the issue is that each episode that is returned has "nextEpsiode" property which continues to chain down through every episode until the last one in the series. Which is just excess data and only needs to show the direct next episode not two, five, or twenty down the chain. Or else episode one will chain all the way down to 220 then the second one will be 219 episodes long and etc.

**Comment by camelCaseD** [comment]
I believe this [line](https://github.com/dularion/streama/blob/master/grails-app/services/streama/MarshallerService.groovy#L150) of code is the culprit. This line needs to somehow limit the number of results returned to 1. I don't know any groovy myself or else I would have created a PR.

**Comment by dularion** [comment]
Should be fixed! please let me know

**Comment by camelCaseD** [comment]
Yes that fixed it, thank you.
