### ISSUE TITLE
How do I add a new category that is not "Movies" or "Shows"?

### ISSUE THREAD

**Issue by vaMuchenje** [dularion/streama#104]
I want a add a unique category, where can I define it or where can I add it?

**Comment by dularion** [comment]
That is currently not possible, but a good idea! I will add that to my feature list.

**Comment by dularion** [comment]
Is this potentially fixed with Add non-themoviedb shows #91?

**Comment by vaMuchenje** [comment]
Yes! Thanks a lot!

**Comment by vaMuchenje** [comment]
@dularion hey, i have been playing around with this and I ended up reopening the issue. Nice touch with the manual addition of movies and shows, however, what I had proposed was adding new categories other than movies and tv series. Say for example I wanted to add a category called 'web clips' or 'trailers'.

**Comment by caiotarifa** [comment]
Oh, yes... Please! I want to add/edit category w/ different names, :+1:

**Comment by dularion** [comment]
all right!

**Comment by dularion** [comment]
First draft for this feature is in, committet to the "beta" branch. If you wanna test it out.
