### ISSUE TITLE
Initial Build error

### ISSUE THREAD

**Issue by danielhklein** [dularion/streama#105]
When I try ```./grailsw run-war``` or ```make``` (Mac OS X 10.11) I get the following message:

```Error: Could not find or load main class Storage.TV```

I don't think it would have affected this issue anyways, but ```echo $JAVA_HOME``` returns:

``` /Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home ```

**Comment by dularion** [comment]
Could you paste a more complete stacktrace? For example via http://pastebin.com/

**Comment by danielhklein** [comment]
Here's everything http://pastebin.com/TcEsHAqu

without using the -d flag, it just shows 

'''
./grailsw war Dockerfile/tomcat/ROOT.war -Dgrails.env=docker
Error: Could not find or load main class Storage.TV
make: *** [grails] Error 1
'''

**Comment by dularion** [comment]
oh, are you running it as docker? I'm not sure if that works yet... got a lot of feedback that it may not work yet... and the co-dev who implemented docker has not been active again.

**Comment by danielhklein** [comment]
I did try the Docker setup but I also attempted the local setup and it produces the exact same error when I try ```./grailsw run-war```

**Comment by thepulkitagarwal** [comment]
On running `./grailsw run-war` I get a ZipException: http://pastebin.com/Vpek05GZ

I downloaded the zip file from http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.4.4.zip using chrome, and on unzipping I got an error message from Archive Manager: `An error occurred while loading the archive.`

Maybe the zip file is the problem?

**Comment by gkiko** [comment]
`./grailsw run-war` downloads and builds grails environment for you. So you don't need to download it separately. I would suggest to try another unarchiver program.

**Comment by thepulkitagarwal** [comment]
I am getting an error with `unzip`, `7z`, and even `jar xvf`. Is there any other way to fix this?

**Comment by z3ntu** [comment]
Try deleting all files and redownload them.

**Comment by dularion** [comment]
Reopen if the problem persists.
