### ISSUE TITLE
I can't add video files to the player 

### ISSUE THREAD

**Issue by Azizoufy** [dularion/streama#107]
whenever I try to play a movie or a show I always get "there seems to be a problem adding the video-file to the player. this is most likely due to a codec-problem. Try converting it to a compatible HTML5 codec, remove the currently attached file and re-add it. if the codecs are fine, check the error log of the server"

Have you already encountered this issue ?
Thx

**Comment by dularion** [comment]
Hi!
this is currently a common issue because video conversion is still in development. please refer to this https://github.com/dularion/streama/wiki/Video-Codecs-&-Conversion

**Comment by Azizoufy** [comment]
Hi Antonia,

Thank you for your reactivity. I tried the solution you gave but it didn't work. I think the issue I'am dealing with is not related to the video codec. I have converted several videos using your script but none of them worked, have you any other idea; knowing that I'am using an Ubuntu 14.04 LTS server, JRE 1.7.0_79, and grails 3.0.10. I have followed the instruction setup on remote Ubuntu 14.04.

Thx

**Comment by dularion** [comment]
did you try the little trick with the browser tab as described in the above link?

**Comment by gkiko** [comment]
I don't think you are using _grails 3.010_. The project uses _grails 2.4.4_ according to [this](https://github.com/dularion/streama/blob/master/grailsw#L135) line and [this](https://github.com/dularion/streama/wiki/Set-Up-Streama-for-Development) doc.

The compatible grails version is downloaded when you run `./grailsw`. You can monitor the event in the command outputs.

@Azizoufy can you describe the detailed steps that lead to the bug? (e.g. video type you try to watch)

**Comment by dularion** [comment]
@gkiko, I doubt the grails version has anything to do with it.. I mean, if he got as far as uploading and viewing the file.. 

the error occurs when the HTML5 video player can, for any reason, not play the video. that's why dragging the file in a new browser tab shows if it's a codec issue. also: my script only works for Chrome! not Firefox or any other browser.

**Comment by Azizoufy** [comment]
Yes, I tried the trick with the browser the video are ok, grails 3.0.10 was already installed on my server. Some of the videos I tried are from this website (i am using chrome):
http://www.quirksmode.org/html5/tests/video.html

I didn't monitor the ./grailsw execution, grails was already instaled on my server with the latest version. I'll try to downgrade to the 2.4.4 and see what happens even is grails 3.0.10 is fully compliant with older versions. 

for the steps i followed:
1- Installing tomcat7 on the server using the tutorial.
2- Installing MySql-server following the tuto (i noticed that using a different password for the db leads to a blank page on streama; Jdbc cannot reach the db)

3- i created the upload directory 
4- i compiled the project (i remember that the git clone git@github.com:dularion/streama.git didn't work so i just made a copy/past of the zip file that i unzipped in the target directory)
5- I built the ROOT.war on my remote server
6- I deployed streama on the server.

Everything went ok until i tried to play a video.

Thx

**Comment by dularion** [comment]
can you open f12 (chrome debugger) and check if there are any console errors when opening the video?

**Comment by Azizoufy** [comment]
onVideoError

application-7ff27e74eb561e6427960a492ca89078.js:1161  onVideoError

Display : 
There seems to be a problem adding the video-file to the player. This is most likely due to a codec-problem. Try converting it to a compatible HTML5 codec, remove the currently attached file and re-add it. If the codecs are fine, check the error log of the server.

**Comment by gkiko** [comment]
@Azizoufy where can we download the file? :smile:

**Comment by dularion** [comment]
Also, do you have a way to give us temporary access to the websites? Maybe by creating a user and later remove it again.. That way I could try to debug

**Comment by Azizoufy** [comment]
For the videos, i just clik right --> save 

Sorry i can't give access the server is hosted in a private network. The IT service will never accept :(

**Comment by gkiko** [comment]
@Azizoufy ok. Then try to simulate similar problem on public file and share the link

**Comment by Azizoufy** [comment]
On the console i have a warning saying that bindHtmlUnsafe is now deprecated. Use ngBindHtml instead. I don't know if it's a problem or not. Otherwise, I'm not used to web dev, i'm not sure what file you want me to share, in doubt i attach a print screen of the console and the Java script file that the console returns for the onVideoError 


![capture du 2015-12-18 15_04_10](https://cloud.githubusercontent.com/assets/16338660/
[application-7ff27e74eb561e6427960a492ca89078.txt](https://github.com/dularion/streama/files/66667/application-7ff27e74eb561e6427960a492ca89078.txt)
11898576/0d516908-a599-11e5-81da-712d85a0d431.png)

**Comment by dularion** [comment]
Would your be willing to do a screen share session, for instance via hangout so that's I can try and debug together with you?

**Comment by Azizoufy** [comment]
Hi guys.
I just left the server I have no access to it. Thanks for your time I'll
will contact you as soon as it's possible.
Thank you guys.

**Comment by dularion** [comment]
I might have reproduced the issue locally. It seems to have to do with large files, 1gb and above. I'll look into it and report back.

**Comment by dularion** [comment]
let me know if version 0.1.7.1 doesnt fix it
