### ISSUE TITLE
user invites

### ISSUE THREAD

**Issue by zinnfamily** [dularion/streama#108]
I am running streama behind a nginx ssl reverse proxy and the invite urls comeback as Sorry, you're not authorized to view this page. I tried https:// removing http:// also remove the :8080. Nothing works.

**Comment by dularion** [comment]
Did you make sure to include the https to your base path in your settings? Can you paste the url of a working page and the invite url ?

**Comment by zinnfamily** [comment]
Where is the base path in your settings?

**Comment by dularion** [comment]
on your installation, go to Admin -> Settings. For me thats 
localhost:8080/streama/#/admin/settings

**Comment by zinnfamily** [comment]
I feel stupid thanks you!

**Comment by dularion** [comment]
don't worry! did it fix the issue?

**Comment by dularion** [comment]
Closing until further notice
