### ISSUE TITLE
Manage Content - List order

### ISSUE THREAD

**Issue by Flex101** [dularion/streama#109]
Could the order of the movies / shows in the manage content section be reversed?
This would put the most recently added at the top which makes it easier for adding files to recently added movies / shows, rather than having to scroll down to the bottom every time.

P.S Thanks for all your hard work on this. Excellent job!

**Comment by Flex101** [comment]
Possibly the same on the dashboard too, as you are likely to want to see the most recent additions first?

**Comment by stramel** [comment]
I feel like this would be a good option accompanied with other sorts, A-Z, Z-A, Recently Release, Recently Added, etc.

**Comment by dularion** [comment]
Sounds great! I will implement it :)
