### ISSUE TITLE
Cannot get property 'BASE_PATH_GRAPHICS' on null object.

### ISSUE THREAD

**Issue by z3ntu** [dularion/streama#11]
I get this when being on http://localhost:8080/streama/#/admin/shows . 
I click 'Create new show', enter 'The IT Crowd', select the first result and click 'Save show'. Then nothing happens in the browser and a NullPointerException follows in the console. :/
Console log: http://pastebin.com/SaUCEDLH

**Comment by dularion** [comment]
Yep! Fixed that 2 commits ago :) please pull & try again

**Comment by z3ntu** [comment]
Oh lol, I just cloned about half an hour ago ;)

**Comment by z3ntu** [comment]
Okay works, thanks :+1: btw awesome program!

**Comment by z3ntu** [comment]
And how can you add video files to an TV show? I added the episodes from season 1 (automatically) , but when I click "Browse for File" I get a "File Browser"... How can I add files there...?

**Comment by dularion** [comment]
Drag and drop em in :) The browser is only for already added files

**Comment by z3ntu** [comment]
Where to Drag&Drop?

**Comment by z3ntu** [comment]
It just downloads the video files. Using Ubuntu 15.04, Chrome 45.0.2454.15 dev (64-bit)

**Comment by dularion** [comment]
from your file system onto the individual episode-boxes. you should see in the gif in my readme.

**Comment by z3ntu** [comment]
Wow lol, didn't know that was even possible... :o :+1:  to you ! xD

**Comment by dularion** [comment]
you can upload 7 at a time, all the others get queued.

**Comment by z3ntu** [comment]
Can I also link existing files as it copies the files to /data/streama ?

**Comment by dularion** [comment]
That is not yet implemented, but I will add that asap :)

**Comment by z3ntu** [comment]
Okay thanks. 
`java.io.IOException: No space left on device`
lol

**Comment by dularion** [comment]
oh dang... is that a bug or is it really a storage issue on your end?

**Comment by z3ntu** [comment]
no, I made the /boot partition smaller, as I wanted to maybe install more than one Linux version on this hard drive and made the rest big. Apparently /data is on /boot :D

**Comment by dularion** [comment]
you can change the directory though, as long as you update the path in config.groovy

**Comment by z3ntu** [comment]
Can I then just copy the /data/streama folder to the new location?

**Comment by dularion** [comment]
yep. just make sure the application has read/write permissions to that new folder. By default, the app uses the path in the config.groovy (so /data/streama) and adds another folder inside of it, called upload. All files in it have hashed names, and those are the ones it looks for. So if you change the path to `/bla` in the config, then one of the files should be at /bla/upload/XYZ.mp4

**Comment by z3ntu** [comment]
Jeah, made it thanks! Manual symbolic links should work already, don't they?

**Comment by dularion** [comment]
Yep, don't see a reason why they shouldnt. Unless there are permission restrictions to the linked files.

**Comment by z3ntu** [comment]
Aaannd I have another error. Posting it in a second.

**Comment by dularion** [comment]
aww :(

**Comment by z3ntu** [comment]
While starting a video/stream

**Comment by z3ntu** [comment]
And you should create a startscript like start-streama.sh because I forget the command to start all the time :crying_cat_face:

**Comment by z3ntu** [comment]
http://pastebin.com/RvfTcv7r

**Comment by z3ntu** [comment]
This is the folder I specified in the Config.groovy: 
`drwxrwxrwx  3 tomcat7 tomcat7    4096 Jul 30 22:33 streama`
I navigated to http://localhost:8080/streama/ and clicked the play icon on the show I added previously 
Player says duration is "null"

**Comment by dularion** [comment]
I know the error in the middle. but it looks like it is restarting also ... is that true or doesnt it auto-restart due to the error?

**Comment by z3ntu** [comment]
I don't exactly know what you mean with "auto restart" but I guess no^^

**Comment by z3ntu** [comment]
The video files have the permission
`-rw-rw-r-- 1 tomcat7 tomcat7 182181888 Jul 30 22:45 ffa39f42e6f79f2ee499c9b800ff0cab7e6a75f3d1cd36748fd0a06c316c3aa7.avi`

**Comment by dularion** [comment]
ok, if it doesnt auto-restart then all this is, is a cosmetic error that I couldnt yet get rid off. The reason why your file isnt playing seems to be of a different nature: the file may not be html5 compatible. Could you try the following for me: could you open a new browser tab (empty is fine) and just drag the file in? if a video-player shows up, the file is html5-compatible. if the file gehts downloaded, its not. Please report back.

**Comment by z3ntu** [comment]
Format is .avi and it downloads :/

**Comment by z3ntu** [comment]
That means nearly all my video files are not compatible?

**Comment by dularion** [comment]
yeah.. 
avi often uses an incompatible codec :( mp4 & mkv is the way to go ... In the future I will add an auto-conversion, so that when you add files it converts to the right formats, but i havent added it yet ... :( Might do that over the weekend now.

**Comment by z3ntu** [comment]
That would be awesome!

**Comment by dularion** [comment]
Btw, are you using chrome or firefox?

**Comment by z3ntu** [comment]
Chrome 45.0.2454.15 dev (64-bit)

**Comment by dularion** [comment]
kk, good. more formats are compatible with chrome as they are with firefox :)

**Comment by z3ntu** [comment]
Video:
Dimensions: 608 x 336
Codec: MPEG-4 Video
Framerate: 25 frames per second
Bitrate: 509 kbps

**Comment by dularion** [comment]
here is an overview of codecs & browsers https://en.wikipedia.org/wiki/HTML5_video#Browser_support 
I'll add that to the readme too

**Comment by z3ntu** [comment]
But actually the video file IS MPEG-4 video...

**Comment by dularion** [comment]
"The adaptive bitrate streaming standard MPEG-DASH can be used in Web browsers via the HTML5 Media Source Extensions (MSE)[16] and JavaScript-based DASH players." I have not added those extensions. But I will look into it. The best format in my experience is h.264 (most mp4 and mkv files)

**Comment by z3ntu** [comment]
And do you know if there is already support for x265 video files in Chrome 45? Or can I test this?

**Comment by dularion** [comment]
This is one of my files for example: 
http://grab.by/JftM

I can see that the "kind" says MPEG-4 movie, but the important part is the codec further below.

**Comment by z3ntu** [comment]
Ubuntu says at the .mkv x265 files "Unknown" everywhere^^

**Comment by dularion** [comment]
x265 is pretty new afaik, not even sure if ffmpeg can convert it properly (which I would use to convert). I dont think its supported by chrome yet.

**Comment by dularion** [comment]
I just read the following: "Both of these codecs are still a ways off from any sort of widespread adoption. The specs aren't even finalized, as far as I know."

**Comment by z3ntu** [comment]
http://www.libde265.org/blog/2014/04/10/libde265-js-javascript-hevch-265-bitstream-decoder/
maybe?

**Comment by dularion** [comment]
Thats pretty awesome, I'll take a look if I can implement that without breaking regular viewing :P

**Comment by z3ntu** [comment]
And it works with ~60fps at my pc http://strukturag.github.io/libde265.js/

**Comment by z3ntu** [comment]
Okay .mkv x265 encoded KINDA works. Audio works, video is black... Okay :100: / :100:
