### ISSUE TITLE
Cannot delete video with viewing status

### ISSUE THREAD

**Issue by Flex101** [dularion/streama#110]
I recently tried to delete a video, however when the list refreshed the movie was still there.

I tried to delete the entry from the video table manually but it failed because of a constraint lock, from the video id being in the viewing _status table. Deleting the entry from this table allowed me to delete the entry from the video table.

I believe this constraint was what was causing the delete from the web interface to fail (silently) too.

**Comment by dularion** [comment]
Oh good ticket! I will fix it asap :)
