### ISSUE TITLE
Cannot play videos using player - directly works

### ISSUE THREAD

**Issue by ialexpw** [dularion/streama#111]
I seem to be having trouble streaming video files using the video player...

It just shows the loading icon constantly and will not load the video as below;

http://s3.paq.nz/Screen-Shot-2015-12-31-15-33-19-CSU56Cg30P.png

I get this in the browser debugger (FF);

http://s3.paq.nz/Screen-Shot-2015-12-31-15-31-30-gPMUhdOvsq.png

If I follow the direct link to the video I can view them in my browser, just not through the video player.. If you think a login will help debug this I'll be happy to add one for you.

I have tried both MP4 and WebM.

Thanks

**Comment by dularion** [comment]
Oh that's strange! There seems to be a server error of some kind. Are there any server errors in the server log?

**Comment by ialexpw** [comment]
For the tomcat server, there are no errors there... I cannot seem to see anything wrong, it has loaded once or twice now that I've tried it a lot, but mainly it does not. It always loads directly though which is odd.

**Comment by dularion** [comment]
So sometimes the video loads and sometimes it doesnt?

**Comment by dularion** [comment]
A login wouldnt hurt to debug. maybe you can pm me via gitter (see project readme)

**Comment by thesupergeek** [comment]
I can confirm I am having this same issue. When I select the video through the player, it will play the loading animation endlessly, but when I right click and hit the "View Video" button, it plays immediately. I will PM you my server credentials so you can take a look and confirm.

**Comment by dularion** [comment]
Hi! I just debugged your page with the login you PMed me, and for me the video plays in the player... Weird! I use chrome on my laptop (OSX) to play the video. What do you use?

**Comment by thesupergeek** [comment]
I use firefox, but I can give it a shot with chrome this afternoon.

**Comment by thesupergeek** [comment]
It appears to work under Google Chrome, and Chromium, but not firefox,
iceweasel, or midori. I do not have a mac, so I cant try Safari, and I do
not have Windows installed so I can't try IE, so I am afraid I will have to
leave that to someone else.

I am using Fedora 23 GNU/Linux, so it may work in those browsers on other
os's.

-Nate

**Comment by dularion** [comment]
i tried looking at the file on your server again but i guess you revoked the rights. Thats alright! but can you let me know if you uploaded a firefox friendly video with the right encoding? For reference https://support.mozilla.org/en-US/kb/html5-audio-and-video-firefox

**Comment by thesupergeek** [comment]
Sorry, I changed my admin password. You can continue to access my server
using the credentials "test@test.com" and the password is password.

When I drag my encoded MP4s to Firefox and play them that way, they work
great. I also talked with a friend, and he is on an older version of safari
on OS X and he has the same issue with loading it from streama, but it
works with the regular video file.

I do not think it is an issue with the encoding and codec, because when you
right click and hit play video it plays well in any browser, as far as I
know. I would suspect it is some web script or maybe some CSS that breaks
compatibility with these other browsers.

Let me know what you think!

-Nate

**Comment by coolnow** [comment]
I'm having the same issue using Safari 9.1.1 on OSX 10.11 (El Capitan). However, i cannot play videos even using the "preview" functions in "manage files". However, the test video streams perfectly when accessed via local storage (drag drop into safari) and other web servers (apache, nginx). 

Everything works fine on Chrome though. Although, on iOS, both Safari and Chrome fail to play the videos, suggesting an inherent incompatibility with webkit, as AFAIK, iOS web browsers are limited in the engines they can use.

Summary: videos fail to stream on Safari via streama, both using the player and trying to preview it. However, video file is perfectly fine, works with other software (including Plex via the download feature).

**Comment by dularion** [comment]
Yea ok, this is something Ive been struggling with a lot.. 
I will try around as soon as i can and get back to you.

**Comment by coolnow** [comment]
Thank you, your project is literally exactly what i needed. I've been contemplating learning to program to build something like this, and finding this project is helping me learn tons of new stuff. Thanks!

**Comment by dularion** [comment]
So for anyone who is interested: 
Every bit of research that I can find tells me, that the 2 main causes of this problem are (1) the server doesnt accept range headers and/or (2) the server doesnt send a proper mime type (content-type header) back. Now in my case, both of those things seem 100% correct, also if I compare to a video hosted by apache I can't spot any differences. 
these are the headers from streama 
![Streama video response headers](http://i.imgur.com/ZB6Wh5x.png)
these are the headers from apache 
![Streama video response apache](http://i.imgur.com/eJcsv4O.png)


any help is appreciated.. this is totally mind gobbling...

**Comment by dularion** [comment]
thanks       @lclc98
