### ISSUE TITLE
Automated Torrent Downloads (Suggestion)

### ISSUE THREAD

**Issue by adaminsane27** [dularion/streama#124]
Like with the add episodes, a way to have the web app download the episodes to the selected folder (default data/streama) from selected Torrent Sites.

**Comment by dularion** [comment]
Unfortunately, I don't want to get involved in torrenting and the like. For that reason I will not be implementing that feature at this point. However, I see that there is a need for this so I will soon be programming a file-crawler. With that, you will be able to aquire the video files any way you wish and place them in a particular folder and the application will automatically generate the movies and shows based on those files.

**Comment by dularion** [comment]
Unfortunately, I don't want to get involved in torrenting and the like. For that reason I will not be implementing that feature at this point. However, I see that there is a need for this so I will soon be programming a file-crawler. With that, you will be able to aquire the video files any way you wish and place them in a particular folder and the application will automatically generate the movies and shows based on those files.

**Comment by dularion** [comment]
Will that be satisfactory?

**Comment by z3ntu** [comment]
I also don't think this should be a torrent-front-end. @adaminsane27 If you want to watch torrented videos with streama, you have to manually download them and add them. PopcornTime (or similar) is probably what you want.

**Comment by Ivshti** [comment]
The legal implications of a torrent client (or even worse, crawler) integrated into a movie/series-focused application aren't ideal because it shows specific intent.

I also don't recommend it
