### ISSUE TITLE
Trailer link for recommended movie

### ISSUE THREAD

**Issue by LorenzoGarbanzo** [dularion/streama#139]
Another nice convenience, a fast way of getting more info on the recommendation.

**Comment by dularion** [comment]
Currently, the recommended movies dont show up at all. But I agree that this would be a useful enhancement

**Comment by dularion** [comment]
![image](https://cloud.githubusercontent.com/assets/936076/25650425/0e7e1a9a-2fdd-11e7-9e1a-7f12f8e3efda.png)

**Comment by DerHerrHerr** [comment]
This should work now

**Comment by dularion** [comment]
fixed in v1.1
