### ISSUE TITLE
Add source : NAS

### ISSUE THREAD

**Issue by jcolfej** [dularion/streama#14]
It's really an interesting project !
Is it planned to support network peripherals as a NAS for example ?
It is unfortunate to have to copy files (movies / series) a second time ...

**Comment by dularion** [comment]
That sounds interesting, but actually I don't know so much about NAS. How does the operating system see the storage? is it like a mounted drive? in that case it works great with it, because you can set the upload-location to anything you want that is recognizable by the system as a valid path. If it works differently, I guess I would have to implement some sort of API for this. 
Regarding the copying of the files: A file-crawler is in the works, meaning in a future update of streama you will be able to configure a file-system location that will be crawled by the application. Files will be found and recognized through a naming-convention and they will be added as shows/episodes/movies automatically.

**Comment by dascandy** [comment]
That's pretty much what you'd need for a NAS. It's typically a mountable network drive, so you'd just get a mounted folder locally present with content already in it.

Would be nice if you can set it to "store" files there too - so you can upload from anywhere to your NAS as backing store.

**Comment by dularion** [comment]
The ability to store there is already available today, you just need to change the storage path configured in the config.groovy. I will make this setting more accessible through the interface soon. But for now you could change the value there, make sure tomcat has read/write permissions to your target folder, and you should be good to go

**Comment by jcolfej** [comment]
The operating system see the storage as a mountable network drive.
It's could also be a FTP :)

Personally, I have a server (in a hoster) that can launch Streama.
But, my films and series are in my house on my NAS.
It'd be cool to use Streama with "external source", no ?

**Comment by dularion** [comment]
Oh you mean like that? Interesting.. I actually have no idea how to get something like that in place without first saving it on the server (requiring you to use bandwidth to transfer it there) and then from there uploading into the NAS.. and each time it plays a file also fetching from nas and routing through the server. But I know a guy who is really good with this kind of stuff. Maybe he has some ideas :)

**Comment by mrjovanovic** [comment]
@jcoifej
If your NAS can be seen by the network that your server is on, you can mount it as a directory in your file-system. Then you could set that location in config.groovy. NFS supports that out of the box and works quite well (if you have the required bandwith). 

@dularion
I think it would make sense to leave NAS mounting to the filesystem. No need for an additional interface, as all popular interfaces (NFS, Samba, SSH) can be mounted easily in GNU/Linux.

**Comment by dularion** [comment]
Well in that case that functionally is already in place. Easier for me :)

**Comment by gkiko** [comment]
The project is going to become really big and hard to maintain with all these supported storage types (_AWS S3_, _Google Drive_, etc)

It would be better if Streama only supported local file system. Consider that I need to include my _Google Drive_ library. In that case I will write __[fuse](http://fuse.sourceforge.net/)__ module, that will mount the remote cloud storage into my local file system.

So Streama provides beautiful interface to display library and watch movies. Users wtire/reuse __fuse__ modules to meet their needs.

**Comment by dularion** [comment]
Agreed! Sounds like a good plan!

**Comment by rodti** [comment]
I think @gkiko nailed it.  Most if not all external or remote storage devices can be mounted in some way. That shouldn't be Streama's problem.

**Comment by Jeronimo95** [comment]
Agreed, file-mounting is not a streama issue and is up to the user to mount the files locally for streama to access.
