### ISSUE TITLE
Playing a video doesn't work after changing Base URL to something else and then back to original

### ISSUE THREAD

**Issue by LorenzoGarbanzo** [dularion/streama#142]
"There seems to be a problem adding the video-file to the player. This is most likely due to a codec-problem. Try converting it to a compatible HTML5 codec, remove the currently attached file and re-add it. If the codecs are fine, check the error log of the server."
 -> Problem fixed after removing the last /-character from the base url. (working url: http://localhost:8080)

**Comment by jsniemela** [comment]
This happens because the getFileSrc function in UploadService adds another forward slash. Currently the default Base URL already has a forward slash at the end, so it doesn't work.

**Comment by dularion** [comment]
Fixed
