### ISSUE TITLE
Fetching tv-show information doesn't seem to end

### ISSUE THREAD

**Issue by LorenzoGarbanzo** [dularion/streama#145]

**Comment by dularion** [comment]
What exactly did you try to do?

**Comment by jsniemela** [comment]
Hey,

Whenever I use "Fetch all episodes for a season", I see the loading animation, but the actual results don't appear until I click another link and then go back to the TV Shows page. It seems to work otherwise, but the page isn't updated after it's ready.

**Comment by jsniemela** [comment]
There's a new small bug with the update where it creates a "season 0" when fetching episodes for season 1. It doesn't seem to happen when adding a later season before the first one or if the show already has one of the later seasons added before season 1. Also, the page doesn't fully update when adding a later season, it only shows the "re-fetch season" and "delete season" buttons until switching to another page and back.
