### ISSUE TITLE
Make episode navigator play buttons bigger

### ISSUE THREAD

**Issue by asmartin** [dularion/streama#147]
The whole interface of streama is fantastic and very polished! However one thing I think would make it easier to use (especially on mobile devices) is to may the play button next to each episode on the little popup list that appears on the player controls easier to click. Right now it seems like I have to click in just the right spot to trigger it playing the desired episode. Making the area where you can click to play larger and easier to select would be great!

**Comment by dularion** [comment]
Thank you for your kind and thoughtful feedback! I will improve the above asap :)

**Comment by dularion** [comment]
fixed :)

**Comment by asmartin** [comment]
I tested this out and it works well, thanks!
