### ISSUE TITLE
Cursor won't hide

### ISSUE THREAD

**Issue by Deathknife** [dularion/streama#151]
The cursor won't hide, unless its over the bottom bar, which then the bar won't hide. If the mouse is on video, it wont hide but instead will look like "click", and clicking pauses/resumes the video.

**Comment by dularion** [comment]
Yea I've noticed this too, it started with the feature to click for play/pause. I'll look into it. Until then, if you don't care too much about the click feature I think by disabling it in your user profile the cursor should hide again. But either way I'll look into fixing it asap.

**Comment by Deathknife** [comment]
Thanks for the quick reply. I don't mind disabling that feature for it, but where can I do that? I can't seem to find anything regarding this.

**Comment by Deathknife** [comment]
Thanks for the quick response, however this doesn't fix it. I can no longer play/pause while clicking on the video, like it should be, but the cursor won't disappear.

**Comment by dularion** [comment]
fixed it now!
