### ISSUE TITLE
It's possible to create a movie or "other video" that cannot be edited or deleted

### ISSUE THREAD

**Issue by jsniemela** [dularion/streama#153]
In Other videos it happens when leaving the name empty and in movies it actually seems to happen even if everything is written correctly when using the manual adding. This doesn't seem to be an issue with TV shows.

Edit: This actually breaks the whole application, because it doesn't start at all without touching the SQL server. I deleted the whole database and it works again, but it probably would have been enough to just delete the invalid videos from there.

**Comment by dularion** [comment]
So wait, you created a movie via add manually and that breaks everything? In that case I have to check that out asap!

**Comment by dularion** [comment]
Should be fixed now!

**Comment by jsniemela** [comment]
It's still possible to create a broken video in Other videos by leaving the name empty, but I don't think it breaks the application anymore.

**Comment by dularion** [comment]
Now it shouldn't be possible to create them without a name anymore
