### ISSUE TITLE
Invite don't work with Gmail

### ISSUE THREAD

**Issue by frederic2ec** [dularion/streama#155]
Hi,
The invite doesn't work with Gmail. I tested with 2 account and the email it's not received.

Thank you!

**Comment by dularion** [comment]
have you checked the spam account?

**Comment by frederic2ec** [comment]
Ok,
It take a long time to receive. But it possible to change the email message, and the email sender?

Thank you!

**Comment by dularion** [comment]
Only via code at the moment, But this is a good feature to include in a future commit. 
UserController.groovy line 95 - 99
