### ISSUE TITLE
No funciona la aplicación (Not run the app)

### ISSUE THREAD

**Issue by davidlf13** [dularion/streama#157]
OS:  os x 10.9.5

java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

Log errors: http://pastebin.com/kFRethQZ

**Comment by z3ntu** [comment]
Please use something like pastebin or github's gists for posting stacktraces/logs. Thank you!

**Comment by davidlf13** [comment]
Ok. Sorry! i am noob.
Error: http://pastebin.com/i0ReKKMb

**Comment by dularion** [comment]
Hi! 
This is a problem with your mysql. It seems that you used the wrong credentials? By Default, the application asks for a mysql connection on localhost with username "root" and no password. What do you have?

**Comment by davidlf13** [comment]
these are my config files. http://pastebin.com/kFRethQZ
Can you send me your config?

**Comment by z3ntu** [comment]
Is your username/password both 'root' in mysql?

**Comment by davidlf13** [comment]
Yes

**Comment by z3ntu** [comment]
So your normal connection works (eg via terminal)? Do you have a database called "streama"?

**Comment by davidlf13** [comment]
Yes. but I dont understand why it does not work or I do wrong...=S

**Comment by z3ntu** [comment]
And can you please edit your original post to remove the stacktrace/log and include the pastebin link there? Thanks :)

**Comment by davidlf13** [comment]
What would someone be so kind to send me your config?

**Comment by z3ntu** [comment]
I don't have streama installed/configured right now.

**Comment by dularion** [comment]
I can send you my config file but it depends so heavily on your system setup that I'm not sure what good that will do.
Can you please send a screenshot that shows your database setup, either from phpmyadmin, the console or some other means of visualizing your databases?

**Comment by davidlf13** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/17600304/13907108/38c970ca-eee7-11e5-84e2-a17b2dbe3cba.png)
user: root
pwd: root

**Comment by dularion** [comment]
Ok thanks, I see that everything seems in order. If you look at the tables of the streama database, have any tables been created or is it empty?

**Comment by davidlf13** [comment]
is empty.

**Comment by dularion** [comment]
Can you temporarily try to remove the password from the database? I suspect that the changes to the config file didn't work.

**Comment by davidlf13** [comment]
I deleted the password does not work. I get the same error. Do I need to download any .jar? Is it correct my DataSource.groovy file? I would like to see your settings.

**Comment by dularion** [comment]
Well my datasource is this one: https://github.com/dularion/streama/blob/master/grails-app/conf/DataSource.groovy

**Comment by dularion** [comment]
How did you edit the datasource in the first place?

**Comment by davidlf13** [comment]
Yes. This is correct to connect the database?

dataSource {
    pooled = true
    jmxExport = true
    driverClassName = "org.h2.Driver"
    username = "sa"
    password = ""
}
or this is correct?
dataSource {
    pooled = true
    jmxExport = true
    driverClassName = "com.mysql.jdbc.Driver"
    username = "root"
    password = "root"
    url = "jdbc:mysql://localhost:3306/streama"
}

Do I need to download any .jar to connect the database?

**Comment by dularion** [comment]
No, the h2.Driver is the wrong one. 
It is this one that is used for you when running via run-war: 

    production {
        dataSource {
          dbCreate = "update"
          driverClassName = "com.mysql.jdbc.Driver"
          dialect = org.hibernate.dialect.MySQL5InnoDBDialect
          url = "jdbc:mysql://localhost:3306/streama"
          username = "root"
          password = ""


Note the production closure. If you want to edit one, it is this one. 

And you do not need to download any .jar, it is all part of the package.

**Comment by davidlf13** [comment]
I want to think that is not a error DataSource.groovy file. It is an error..multiple SLF4J bindings.
do i need to download Apache Maven??
Could I see your configuration files BuildConfig.groovy and Config.groovy, please? Thanks!!!

**Comment by dularion** [comment]
https://github.com/dularion/streama/blob/master/grails-app/conf/BuildConfig.groovy
https://github.com/dularion/streama/blob/master/grails-app/conf/Config.groovy


If you suspect it's the slf4j maybe look here 
https://github.com/dularion/streama/issues/102
https://github.com/dularion/streama/issues/13

**Comment by davidlf13** [comment]
The problem is that when I run the run-war command the .m2 folder is created with the jar:file: /Users/Davidlf/.m2/repository/org/grails/grails-plugin-log4j/2.4.4/grails-plugin-log4j -2.4.4.jar file and :/Applications/MAMP/htdocs/demos/streama/target/work/tomcat/webapps/ROOT/WEB-INF/lib/grails-plugin-log4j-2.4.4.jar. Conflict occurs.

**Comment by davidlf13** [comment]
You can give by closed the subject. I've solved the problem. 
The problem was in the /etc/mysql/my.cnf file, the lines (skip-external-locking and bind-address = 127.0.0.1) were commented.

Thank you for your assistance.

**Comment by z3ntu** [comment]
You can close the issue yourself.
