### ISSUE TITLE
People can't logout

### ISSUE THREAD

**Issue by frederic2ec** [dularion/streama#158]
Hi,
Here an error, if the people want to logout this error happened...
![Error](http://puu.sh/nQgVr/8360f4f8fd.png)

Thank.

**Comment by Flex101** [comment]
I'm getting this message every time I view the dashboard with a non-admin account

**Comment by dularion** [comment]
Oh really? Damn. Will look into that asap

**Comment by dularion** [comment]
Partially fixed with latest commit

**Comment by dularion** [comment]
Fixed the message in the bottom right. But I can't reproduce the logout issue. It works for me. Can you check to make sure your base path is correct?

**Comment by ManuGithubSteam** [comment]
Can't reproduce on 1.07 for me :-)

**Comment by dularion** [comment]
Pls reopen if problem persist in latest release
