### ISSUE TITLE
folder-crawling to discover files

### ISSUE THREAD

**Issue by dularion** [dularion/streama#16]
This is then programmed as an optional alternative to uploading files manually. This will be dependant on a naming convention of the files and folders. I will be using the [KODI naming convention](http://kodi.wiki/view/Naming_video_files/TV_shows) as a template for Streama.

**Comment by fiddlerwoaroof** [comment]
Could a manual workflow be added as well? i.e. specify a directory that contains movie files on the server and then, through the admin interface, get the information from theMovieDB and select which file in the directory corresponds to the movie?

**Comment by z3ntu** [comment]
@fiddlerwoaroof :+1:

**Comment by dularion** [comment]
That could work.  I was thinking about a sort of File Browser also, with folders and files, that can be used to add files to episodes/movies. This could be step1. And then I would implement crawling files based on a naming convention and auto-generating the content. But the file browser might still be necessary at times due to some sort of failure in the mapping of the file name and content.

**Comment by kevincox** [comment]
This is critical to my usage. I already have a setup to manage my media files and I would like streama to act as a viewer. Uplaoding everything manually is way too much work. It would be really cool if the names could be automatically guessed but that might be diffcult. Manually mapping folders/files to shows/movies is probably good enough.

**Comment by stonie08** [comment]
I'd also like to see a file browser of some sort. Some videos (like family videos,...) aren't available in the movie db anyway so it'd be sufficient to access them through a file browser for playback.
My suggestion would be to offer a view that let's you access, browse and play files from the "Local Video Files" directory specified in the settings.
Selecting a folder could also be used to query additional information from the movie db, iff available (and maybe caching it) using the way it's been done for the bulk add.
If there's a cover.(jpg|png|...)-image in that folder it could be displayed in addition to the results from the movie db.

This way it wouldn't necessary (for some users) to add files manually (or nowadays even in bulk), but rely on existing directory structures without building a separate database, but still profiting from the additional information from the movie db.

**Comment by dularion** [comment]
This issue has been adressed in this release: https://github.com/dularion/streama/releases/tag/v1.2.3_beta

**Comment by dularion** [comment]
I like your idea @stonie08 but please make a separate issue for it :)
