### ISSUE TITLE
Upload progress missing from movie page

### ISSUE THREAD

**Issue by Flex101** [dularion/streama#160]
If you upload a movie by dragging and dropping the file onto the correct space on a particular movie's page (rather than using the manage files window), no upload progress percentage is shown. The file still uploads fine, and the page updates correctly when the upload is complete to show the play button, but there is no indication an upload is in progress.

This used to work fine, I believe the bug crept in during the movie page update.

**Comment by dularion** [comment]
Yes, you are totally right! I'll fix it asap
