### ISSUE TITLE
Can not start streama server in Tomcat

### ISSUE THREAD

**Issue by TheJoe49** [dularion/streama#164]
I am have the same problem that #162 is having and I thought I might try to show it from my point of view.

![image](https://cloud.githubusercontent.com/assets/16162727/14323776/898bcabe-fbe7-11e5-957d-fe519cfbfe6c.png)

I copied the log from the _catalina.out_ file after I started Tomcat and after I launched the streama server from within tomcat.

After starting Tomcat - http://pastebin.com/jDXgRPbX

After starting Streama - http://pastebin.com/YiY0R37k

**Comment by dularion** [comment]
From your logs it seems that hibernate has a problem creating the tables in the database. 
Can you check the following:
1. Is mysql running?
2. Are the login credentials correct? Default user root, no password
3. If you didn't use root user, make sure that mysql user has writing privileges to the streama db 
4. Make sure the mysql db is created for localhost, not localhost IP or similar


Let me know if any of that helps you

**Comment by TheJoe49** [comment]
Yes mysql is running but I am using MariaDB. I don't know if that would that effect any thing.
Yes the login is correct.
I think it does.
I think it is.
Also where it says path is streama supposed to be at / or in the install directory

**Comment by dularion** [comment]
Oh boy.. It might very well be MariaDB. Never tried it with that. 
What do you mean by your last question?

**Comment by TheJoe49** [comment]
In the picture I uploaded, under applications the fist one says it's path is "/" I was wondering if that was right or if it should be the path to where I installed streama.

**Comment by paulchabotca** [comment]
**Its definitely not MariaDB**, as I was able to get the app running ( it does fail, but not like this)

**Comment by paulchabotca** [comment]
Check your database settings. If you look in your logs 

_**Table "ROLE" not found;**_

and other such errors. It looks like either the database for streama was not created or the application can not find it.

**Comment by TheJoe49** [comment]
The database is there. How would I make sure that it can be found?

**Comment by dularion** [comment]
What / means, it that the application will run on server root, meaning yourIpAddress:8080 . If it wouldnt run on root, it would be something like yourIpAddres:8080/streama. This depends on the name the .war file has in your tomcat webapps folder. 
How exactly are you deploying streama? are you loading the war into the manager gui?

**Comment by dularion** [comment]
Can you check which tables have been created by the application? Maybe drop the streama database and recreate it and restart the application...

**Comment by TheJoe49** [comment]
The .war file is just named ROOT. I am running streama through tomcat. And no tables have been crated.

**Comment by dularion** [comment]
Can you tell me which steps you took to set it up?

**Comment by dularion** [comment]
would you mind trying out the new simpler setup with grails 3 ? just to see if that works for you ? https://github.com/dularion/streama/releases/tag/v1.0.0

**Comment by gkiko** [comment]
Closing the issue. Please open a new one if you experience same problem with _grails3_ version of streama.
