### ISSUE TITLE
Cant view show info/additional eps without admin rights ?

### ISSUE THREAD

**Issue by d000000h** [dularion/streama#165]
Im having a problem, when i invite a user without the admin/content manager rights he can view some of the vidoes but he cant click on the info button to view the other episodes ?

This is the message that shows when he tries to click the i button for more info (the other eps)
![streama-cant-click-info-button-no-rights](https://cloud.githubusercontent.com/assets/10897164/14556372/4863c3bc-02f8-11e6-962d-803ccc50845a.png)

This is the way i created the user?
![streama-invite-screen-create-user](https://cloud.githubusercontent.com/assets/10897164/14556373/48658b34-02f8-11e6-985e-e1bfd2793765.png)

As you can see the user has no role? so he should be able to view videos?
![streama-user-list-no-role](https://cloud.githubusercontent.com/assets/10897164/14556374/48688370-02f8-11e6-9965-a89b27ec41ed.png)

What am i doing wrong ? or is this a bug ? 

I want some users just to view the videos and not be able to edit remove stuff etc.

I had to remove some of my images i hope you can understand my problem :)

**Comment by d000000h** [comment]
Im also looking for tips on how to customize the layout of the website so i can make it more of my own ? mayb remove the streama branding etc. ? any pointers on how to add functionality to the website ? i would love to have a shoutbox and some polls in it (and a donation bar :P )

which files should i edit to add my own javascript/html codes?

**Comment by dularion** [comment]
Ok so regarding the first thing, that's a bug! Thank you! I will look into that asap. But I'm a little strapped for time so might not get to it too soon

**Comment by dularion** [comment]
Regarding your second point, it depends on what you want to change.. The logo can be exchanged in the Index.gsp and color changes and other customizations require css knowledge. As the project used SCSS you might need to add that. I can in the future add a way to change branding and add custom CSS in the settings but right now you need to know some stuff to do it :(

**Comment by d000000h** [comment]
Thanks a lot for you quick response :) i will be watching out for a update for this bug :) and ill dive into the css code to see if i can get it to do what i want :)

**Comment by dularion** [comment]
It's best to leave it open for me, so I remember to do it ;)

**Comment by d000000h** [comment]
Really need this bug fixed so i can start modding my layout :)

any chance you have a bitcoin adress i can donate to to speed up this fix ? im not very rich but i like this script so much and i want to thank you for your hard work :)

**Comment by dularion** [comment]
Hi! Thanks for the offer. This is my Transaction ID: 17rCUEX6KYQ8ZM4w39ttEUL7SUDnGCpcWq

**Comment by d000000h** [comment]
Its not much :) but have some coffee on me :)

**Comment by dularion** [comment]
Thank you ! Ill get on it asap :)

**Comment by dularion** [comment]
Should work properly now! Let me know if it doesn't

**Comment by d000000h** [comment]
Still the same error when i try to pres the I button on the frontpage (to see aditional episodes for a show)

You do not have the rights to carry out this action

i hope my screenshots will explain better for you the problem :)

![2](https://cloud.githubusercontent.com/assets/10897164/14636226/782dff60-062a-11e6-8294-810aaf8f7d39.jpg)
![1](https://cloud.githubusercontent.com/assets/10897164/14636227/782eaaaa-062a-11e6-88f6-cee98488952d.jpg)

This user i login with has no role selected (so no admin-contentmanager) 

Enabled has been ticked (can log in and view videos)

**Comment by d000000h** [comment]
this is what shows when i click the i button with a admin account

![3](https://cloud.githubusercontent.com/assets/10897164/14636396/7d58d414-062b-11e6-8196-58172729d32b.jpg)

**Comment by dularion** [comment]
Are you sure you pulled & restarted the application? I created the scenario as you described, created a user without any rights, had the same error and fixed the error for me.

**Comment by dularion** [comment]
This commit took care of it: https://github.com/dularion/streama/commit/01ece81bd6e152a0d574ad02969580450fa9193f
