### ISSUE TITLE
Base URL conflict...

### ISSUE THREAD

**Issue by frederic2ec** [dularion/streama#166]
Hi,
It's possible to deactivate the "Base URL" functionnality because it making conflict with my "www.domain.com" and my "domain.com". It's very embarrasing for people joining with my "domain.com" because my base URL it's "www.domain.com".

Thank you.

**Comment by dularion** [comment]
Do you mean you want a redirect in place for wow to non-www? You can do that with an nginx or Apache hooked infront of the tomcat. Or what do you mean? You need the base url because with it the link in the email and some other stuff is created...
