### ISSUE TITLE
Stuck on Compile the Streama Root.war step

### ISSUE THREAD

**Issue by eGolono** [dularion/streama#181]
Hi, I've been keeping an eye out on this awesome project for a while now with hopes of setting it up and trying it when I had some free time. I was finally to get around to doing that and I followed the instructions to set this up on a virtual Ubuntu server.

However, I'm stuck on the "Compile the Streama Root.war" step. Specifically, when I run the "git clone" command, I am unable to connect to the server and receive the following message:

> Warning: Permanently added 'github.com,192.30.252.128' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository

Now to be honest, I am fairly new at this and I'm not even sure why this step requires connecting to another server but I was going along with it.

Lastly, I'd like to thank you for making this application! I look forward to using it to watch content with friends.

**Comment by z3ntu** [comment]
Use the http clone version, not the SSH version.

**Comment by dularion** [comment]
Oh sorry, this is something that I'll have to adjust in the docs! Thanks @z3ntu

**Comment by eGolono** [comment]
Thanks for the quick response! I managed to get to the last few steps but unfortunately I'm only getting a blank screen after starting tomcat up. I did receive the `INFORMATION: Server startup in X ms` message . 

Initially, I realized that I forgot to add the password of the root account of mysql to the `DataSource.groovy` file. I went through the file and filled in the password in the two sections that mentioned mysql and its root account.

I restarted the server and tried again but the blank page remains the same. After looking through the issues, I also tried adding /streama to the end of the URL but to no avail.

**Comment by dularion** [comment]
What's your stacktrace?

**Comment by eGolono** [comment]
Sorry if this is the wrong information but even after some searching, I am not sure how to obtain the stack trace. From what I've seen others post I think it may be information within the tomcat7 logs.

There are several already several log files in the logs directory and they are quite lengthy so I just took a piece of one from yesterday.

http://pastebin.com/MKqhJ3Sy

**Comment by dularion** [comment]
would you mind trying out the new simpler setup with grails 3 ? just to see if that works for you ? https://github.com/dularion/streama/releases/tag/v1.0.0

**Comment by eGolono** [comment]
That worked perfectly! Thank you for creating this simpler approach. Just to verify, it is ok to run the service with a mutliplexer like screen to keep it up on a remote server, correct?

**Comment by dularion** [comment]
That should be fine for now. If you're running into issues, however, then I can tinker around with a plugin that I found that wraps the war so that it can be run as a standalone service. The approach you're suggesting is yet untested with this version of the app. So you're my first beta tester for that ☺️

**Comment by z3ntu** [comment]
So closed?

**Comment by eGolono** [comment]
Cool, I'll play around with it and let you know if I find any issues. :smile:  One last thing: regarding user invitations, is there a way to create an account outside of sending an email invitation? I am unfamiliar with setting up a mail server and have run into some trouble with getting the invitations sent.

I tried a hacky, simple method of configuring sendmail that allowed me to send emails from the terminal (though they got put into spam). Unfortunately, when I send out an invitation, it isn't received.

**Comment by dularion** [comment]
Yea, after you invite them, in the list of users, there is the unique link for them to use to set their password. You can just link that to them :)

**Comment by eGolono** [comment]
Strangely, the invite link field is blank for all of the invitations that I tried sending. I made sure that the base URL is set to the address of the login page but the links are still not showing on the Users page.

**Comment by dularion** [comment]
Did you enable the users? (There's a checkbox)

**Comment by eGolono** [comment]
Yup, I also just noticed that the roles aren't showing up either. [Here's a screenshot of what the page shows.](http://i.imgur.com/M9LxOA2.png)

**Comment by dularion** [comment]
Hm, this may be a grails 3 bug. I'll look into it and get back to you

**Comment by dularion** [comment]
fixed with release 1.0.1 
https://github.com/dularion/streama/releases/tag/v1.0.1

**Comment by dularion** [comment]
For any future issues with this version, please create new issues :)
