### ISSUE TITLE
Video won't upload :[BUG]

### ISSUE THREAD

**Issue by DevLight1** [dularion/streama#183]
So i'm guess it a bug. I am able to upload with ip address but not in the domain name of the website?

**Comment by dularion** [comment]
What exactly do you mean by that? Did you change the base path in the settings?

**Comment by DevMega** [comment]
Yes i change the base path and it will only upload with the ip address but im only able to view the video with the url ?

**Comment by dularion** [comment]
It sounds like something is wrong with the settings. What is the error message that you see when you try to view it via url?

**Comment by DevMega** [comment]
No it just stay stuck around 3% to 9%

**Comment by dularion** [comment]
Can you open the developer console (f12) and try again and make a screenshot of the error message? Alternatively grant me temporary access to your installation

**Comment by DevMega** [comment]
![capture](https://cloud.githubusercontent.com/assets/8704760/15853808/41c2dc44-2c6c-11e6-93c0-40390f101b54.PNG)

**Comment by dularion** [comment]
Thank you! Can you check if get any output in the server log?

**Comment by dularion** [comment]
You're welcome to try the BETA build with grails3
