### ISSUE TITLE
Allow new users without an email address

### ISSUE THREAD

**Issue by ericalbers** [dularion/streama#188]
It appears it only allows you to 'invite' users by their email addresses.
Not good when its children in a house, who have no email addresses.
You have to create a bogus email, then hand edit the username and password in the mysql tables directly.
Very poor.

**Comment by z3ntu** [comment]
The title should be "Allow new users without an email address"

**Comment by dularion** [comment]
oh, good point!

**Comment by moduhlize** [comment]
Maybe a work around would be to do what Netflix does and have one email be used to register but your account can have multiple people accounts so multiple family members can use. That way you could maybe sort movies by age.
