### ISSUE TITLE
Cannot install without a moviedb account

### ISSUE THREAD

**Issue by ericalbers** [dularion/streama#189]
You must register for a moviedb account in order to use the program it will NOT work without an API key.
So the NSA/everyone can see what your watching.
I modded mine to fix this, will fork.

**Comment by z3ntu** [comment]
You know, the the API key is only used for information about new shows you add...?

**Comment by dularion** [comment]
I'd appreciate a PR for this :)

**Comment by SajeOne** [comment]
duplicate of #125 as well. If you could submit a pull request with your custom version I would greatly appreciate it. :)

**Comment by moeinrahimi** [comment]
it would be awesome if moviedb was optional and there was alternative services

**Comment by dularion** [comment]
It would be optional with 1.0.11

**Comment by Jeronimo95** [comment]
Duplicate of #125
