### ISSUE TITLE
aws s3 storage

### ISSUE THREAD

**Issue by gcnonato** [dularion/streama#190]
any chance for an aws s3 storage addon? also, how do i change from port 8080 to 80 on the 1.0.1?
cheers

**Comment by dularion** [comment]
No plugin planned for now, but definitely something for the list! Until further notice you can mount your s3 with Ubuntu and then just reference the mounting path in the streama settings. 
Regarding port : I haven't tried this and I'm not at my pc right now, but try if adding SERVER_PORT=80 before or after the environment setting works for you.

**Comment by gkiko** [comment]
Agree. Mounting S3 on your file system is the most straightforward solution.

You can give it a try [link](https://fullstacknotes.com/mount-aws-s3-bucket-to-ubuntu-file-system/)

**Comment by dularion** [comment]
Please reopen if this option doesnt work for you for some reason.
