### ISSUE TITLE
Translate the application

### ISSUE THREAD

**Issue by robsonolivesa** [dularion/streama#193]
I would like to translate the application for my language, Portuguese (PT-BR). How can I do this?

**Comment by dularion** [comment]
Thank you for wanting to contribute! 
First of all you'll need to make a fork. Then, in your forked version you need to make a copy of the file `grails-app/assets/javascripts/translations/EN_us.js` In the same directory and call it PT_br.js. Make all necessary translations there. 
In line 5 of that file make sure to call the translation pt.
Then head on over to `/grails-app/assets/javascripts/translations/streama.translations.js` and add the string 'pt' to the available languages array. 
In the user profile it should now show up as selectable from a dropdown list. Choose it and test! If you find any parts that still need translating let me know. I chose to limit translations only to the Frontend of the application for now, the admin area is English.

**Comment by dularion** [comment]
I've added a comprehensive Guide. I will link to it from the readme. thanks! 
https://github.com/dularion/streama/wiki/Translating-the-app
