### ISSUE TITLE
Testing of v1.0.1

### ISSUE THREAD

**Issue by jendib** [dularion/streama#198]
After testing 1.0.1 I got some issues:
- I can't add a new show: https://gist.github.com/jendib/45cb8a0150bafa81a851ed65d97ea377
- Video files in my upload directory don't show anywhere

**Comment by dularion** [comment]
Thanks for testing!
I'll look into the first point, but regarding the second I need more information ... Don't show where? Do you have a log? What exactly is and isn't happening? Did you use the no-mysql environment or mysql?

**Comment by jendib** [comment]
I used the no-mysql env.
On the initial setup screen, I entered "/downloads" as upload directory. This directory already contains my video files.
I expected those videos to show up in the "file manager" screen (maybe not?).
No other logs about this.
Maybe I'm mistaken about how to add already existing video files?

**Comment by dularion** [comment]
awww.. what youre describing is a feature that isnt yet implemented :( I will try to get around to that soon, though...

**Comment by dularion** [comment]
hi, please try release 1.0.2! 
https://github.com/dularion/streama/releases/tag/v1.0.2

**Comment by jendib** [comment]
The no-mysql profile is still "production-no-mysql"?
Because I get this error with 1.0.2.
It's trying to init a H2 database with the MySQL driver :)
```
ERROR org.apache.tomcat.jdbc.pool.ConnectionPool - Unable to create initial connections of pool.
java.sql.SQLException: Driver:com.mysql.jdbc.Driver@7f497f7c returned null for URL:jdbc:h2:mem:streama;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
```

**Comment by dularion** [comment]
oh youre absolutely right. let me fix that real quick

**Comment by dularion** [comment]
updated the broken v1.0.2 now. sorry !

**Comment by jendib** [comment]
Thanks.
I still have the NullPointerException when I click on the "Save Show" button here:
![image](https://cloud.githubusercontent.com/assets/2623413/16541712/03774e92-408b-11e6-90e2-c8a673fcd3ef.png)

Logs:
https://gist.github.com/jendib/e1505055cee8eec12953d47a675ff618

**Comment by dularion** [comment]
hm, weird! I'm not getting this.. ill try to deploy with h2 and see if that makes any difference...

**Comment by jendib** [comment]
I can give you access to my local Streama instance if you want.
I'm running it inside a Docker container with Debian Jessie and Java 8 (the Oracle JVM).

**Comment by dularion** [comment]
that would be nice, yea!

**Comment by dularion** [comment]
you can PM me on gitter if you want

**Comment by dularion** [comment]
actually, i could reproduce using the .war, so no need for access!

**Comment by dularion** [comment]
all right, please try v1.0.3
https://github.com/dularion/streama/releases

**Comment by jendib** [comment]
Still the same error :(
https://gist.github.com/jendib/249a7669f9598279678b4ff77537b8d1

**Comment by dularion** [comment]
argh...

**Comment by dularion** [comment]
i gotta check it out later then, gotta run

**Comment by dularion** [comment]
fixed!
