### ISSUE TITLE
Add licensing

### ISSUE THREAD

**Issue by DavidVentura** [dularion/streama#2]
Hi
I liked the interface and would like to fork it, could you add a license so I can know if this is viable

**Comment by dularion** [comment]
Good thinking! I could've added it on creation of the github project, but I missed that part. Do you know of any automated way I can add one to an existing repo? I'll also google it a bit and see what I come up with.

**Comment by meisam-mulla** [comment]
I think it's as simple as choosing how you'd like to license it and uploading a copy of said license called license.md to the project root.

**Comment by dularion** [comment]
Added it now
