### ISSUE TITLE
BETA - Error 500 when starting app

### ISSUE THREAD

**Issue by dularion** [dularion/streama#201]
Originally opened by @robsonolivesa in #195 

> http://pastebin.com/s3s1FLt7

> the steps are in the paste. Thanks

**Comment by dularion** [comment]
I had the same issue when running it from a different folder than where the .war file resides. But from your pastebin I can see that you do run it from the same directory. 
Which Java version are you using?

**Comment by robsonolivesa** [comment]
robson@robson-SVF:~$ java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by robsonolivesa** [comment]
I solve changing the .WAR file to a different directory, into the home folder.

Thanks!
