### ISSUE TITLE
Movies not working with external URL

### ISSUE THREAD

**Issue by calvinturbo** [dularion/streama#204]
Even with a short external URLs, movies are not working in the latest beta build :(
TV series and other videos do work with external URLs.

Javascript error: http://i.imgur.com/tYktGEp.png
There is no (visible) Java error in my console.

possible duplicate of #202

**Comment by dularion** [comment]
hopefully this fixes it: https://github.com/dularion/streama/releases/tag/v1.0.5

**Comment by calvinturbo** [comment]
Fixed indeed :)
