### ISSUE TITLE
Movie source file doesn't get attached

### ISSUE THREAD

**Issue by gkiko** [dularion/streama#207]
Local video file gets lost after attaching it to the movie.

How to reproduce:

1. Add a movie from _Manage Content_->_Movies_
2. Add video source by clicking _No Video File yet!_ button
3. Select _Upload_ tab and click _Drop files or Click to Choose_
4. Select any mp4 file. It will get attached. And you will see this link if you inspect _preview_ button with Chrome dev tools:
`
<a target="_blank" href="http://localhost:8080/file/serve/19.mp4" class="btn btn-xs btn-primary">preview</a>
`
5. Refresh the page and click _No Video File yet!_(another :bug:)
6. Inspect same _preview_ button. But this time no `href` link is provided and the old link returns `{"message":"Not Found","error":404}` if you try to navigate to that page in another tab

I'm using regular mysql instance. No exceptions detected in Chrome or Grails console

**Comment by dularion** [comment]
Thanks, will look into it asap

**Comment by dularion** [comment]
fixed in  v1.0.6
