### ISSUE TITLE
No option to delete Other Videos

### ISSUE THREAD

**Issue by Igglybuff** [dularion/streama#208]
Beta v1.0.5 - unlike TV Shows and Movies, there is no options button in the Other Movies page of the content manager.

Essentially just missing the button which displays these options:

![options](https://cloud.githubusercontent.com/assets/8899226/17514717/0a84cf34-5e2c-11e6-8ded-b35dd048b513.png)

**Comment by dularion** [comment]
True! Its not on the top of the list, but definitely a todo down the road. Thanks!
