### ISSUE TITLE
Streama Grails3 version Build failed

### ISSUE THREAD

**Issue by jamroks** [dularion/streama#213]
Hi,

I tried to build the project from the Grails3 Branch, every task in the build goes well until it reaches the :compileGsonViews,  which produces the following Error : 

```
Exception in thread "main" org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
streama_episode_show_gson: 11: [Static type checking] - No such property: id for class: java.lang.Object
 @ line 11, column 18.
        nextEpisode {id episode.getNextEpisode()?.id }
                    ^
```

Please any help would be great ;-), to figure out what this error is about ? 

cheers

**Comment by jamroks** [comment]
By the way i use this command to build the project : gradle build -x test --stacktrace

note the -x option to skip the "test" phase. 

it has something to do with the show.gson file in the grails-app/views/episode/show.gson .
:compileGsonViews fail compiling this file.

**Comment by gkiko** [comment]
Hi, can you provide mode details, like your OS and Java version?

**Comment by dularion** [comment]
Ill look into it soon, I think I know what might be the cause

**Comment by gkiko** [comment]
`-x test` parameter doesn't change anything. In either way I get

```
Exception in thread "main" org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
streama_episode_show_gson: 11: [Static type checking] - No such property: id for class: java.lang.Object
 @ line 11, column 18.
   	nextEpisode {id episode.getNextEpisode()?.id }
                    ^
```

**Comment by gkiko** [comment]
After some research I found out that the result of `episode.getNextEpisode()` is Objet type. So if we can type cast it to `Episode` that will solve compilation error.
```
nextEpisode {id {((Episode)episode.getNextEpisode())?.id}}
```

**Comment by jamroks** [comment]
Thanks for looking into it. I use Mac OSX El Capitan 10.11.5 on a MacBook Pro .
The java version is : 

java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)

Let me know if you need more details

**Comment by jamroks** [comment]
i've just tested to build to build integrating your fixe in the code . now the compilation passes the 
:compileGsonViews  phase. 
but when i run the produced artefact streama-0.1.war and try to access the application at : 
http://localhost:8080 , the login screen never appear , i'm left with a black screen and the Logo "streama" in the upper right hand corner of the screen, don't seem to work ...

**Comment by gkiko** [comment]
streama works for me as intended

How do you run the application? Do you use gradle to produce _war_ and then upload to tomcat?

**Comment by jamroks** [comment]
I use this command to build the project with Gradle : 

1- gradle build -x test 
2- cp application.yml build/libs/
3- cd build/libs
4- java -jar streama-0.1.war
5- browse http://localhost:8080

the page appear with just the blue logo "Streama"  
<img width="856" alt="screen shot 2016-08-20 at 17 13 34" src="https://cloud.githubusercontent.com/assets/357258/17832018/85ce8c2c-66f9-11e6-8fc2-39559c18d5be.png">

**Comment by gkiko** [comment]
I followed your steps and the application works correctly. Is your mysql database running and configured correctly?

If you just want to experiment with the application I suggest that you take a look at [docker image](https://hub.docker.com/r/gkiko/streama/). Right now I'm working to automate the image build.

**Comment by jamroks** [comment]
Okay this is Odd because i'm not using mysql but the h2 db embedded , that's i just copy the application.yml file provided in the release without any modification since it's configured by default to use h2
as for docker image i'll look into it

**Comment by gkiko** [comment]
This is step 4 output `INFO streama.Application - The following profiles are active: production` and we require mysql in production environment

**Comment by jamroks** [comment]
okay thanks , good catch ! ;-)
i do i change that to development ? is it via the yaml config file ?

**Comment by gkiko** [comment]
maybe try this `java -jar -Dgrails.env=production-no-mysql streama-0.1.war`

**Comment by jamroks** [comment]
Still no luck with that command you provided. the strange thing is when i try to run the application with the war file provided in the Release section v1.0.6.BETA, it just take this simple command for everything to work :  ( application.yml in the same folder as streama-1.0.6.war) 

java -jar streama-1.0.6.war 

and the application works perfectly i can login and so on .

Don't really know what i'm missing here

**Comment by jimmer74** [comment]
Just a me-too...

Built this on El-capitan with the following:

------------------------------------------------------------
Gradle 3.1
------------------------------------------------------------

Build time:   2016-09-19 10:53:53 UTC
Revision:     13f38ba699afd86d7cdc4ed8fd7dd3960c0b1f97

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_102 (Oracle Corporation 25.102-b14)
OS:           Mac OS X 10.11.6 x86_64

Using the official 1.0.6 release build I can deploy this successfully using h2db on my macbook air just by running the java -jar command, or on my QNAP by doing the same.

I have tried running the version I built on my Mac (using the JAVA command line and also using Tomcat as suggested above) and by using the command line on my QNAP and I get the same logo/blank screen with no login on every platform/method I listed. The official release will run fine using any of these methods

Since the 1.0.6 pre-built version there have been fixes for the internal server error when trying to edit a movie/show, so I'm hoping this is a quick/easy fix in the code or a minor wrinkle of trying to build it on a mac...

**Comment by gkiko** [comment]
I noticed that _streama_ does *not* work on gradle 2.13. Generated war structure differ a lot. I suspect our gradle properties file needs some modifications.

![image](https://cloud.githubusercontent.com/assets/2578308/21976140/d1bbb618-dbe9-11e6-8882-b8875880c3c4.png)
