### ISSUE TITLE
Playback not working on iOS

### ISSUE THREAD

**Issue by fedexsca** [dularion/streama#214]
Two things not workin on iOS:
- Playback (remains on loading animation, never starts to play movies, series or videos) 
- Menu (even if the categories button works correctly, the dropdown dont open on click - Cant logout)

**Tested on:**
Devices: iPhone 5s & iPhone 5
iOS version: 9.3.4
Web browsers: Safari for iOS, Firefox for iOS, Chrome for iOS

**Comment by ManuGithubSteam** [comment]
Are your video files compatible with Iphones ?
Many encoders have special checkboxes for i* compatibility...

Do the files work in a normal chrome browser ?

**Comment by dularion** [comment]
Unfortunately this is truly the case for any ios device, and I can't figure it out. I've tested the same video file served through Apache and served through grails3 and it works on Apache and not through grails. I've compared all the http headers and can't see any difference. I'm a bit stuck... Any help would be greatly appreciated!

**Comment by dularion** [comment]
thanks @lclc98
