### ISSUE TITLE
Blank Page / 404

### ISSUE THREAD

**Issue by williamstorm** [dularion/streama#220]
Tried installing over 8+ times, all i get is a blank page and if im lucky a 404 error.
Anyone help?
Im on ubuntu 14

**Comment by williamstorm** [comment]
can someone login to the server and try install?

**Comment by z3ntu** [comment]
Any console output?
If you really can't do it, you should try the docker image.

**Comment by williamstorm** [comment]
whats the docker image?

**Comment by z3ntu** [comment]
https://hub.docker.com/r/gkiko/streama/

**Comment by williamstorm** [comment]
how does one install this?

**Comment by gkiko** [comment]
I'm closing this issue as it seems to be resolved.
For internal server error refer to issue 217

**Comment by z3ntu** [comment]
#217 for the lazy ones.

**Comment by gkiko** [comment]
I didn't want this issue to be related to 217 :sad:

**Comment by z3ntu** [comment]
sry :( deleted my comment although I think it still persists.

**Comment by williamstorm** [comment]
its an annoying error that wont resolve no matter what i do

**Comment by gkiko** [comment]
@williamstorm try new docker image

**Comment by williamstorm** [comment]
now to login is blank screen with the new updated docker

**Comment by gkiko** [comment]
I've pushed manually built docker image under tag `latest`. There is difference between my and travis's build environment that's why images built by travis fail
