### ISSUE TITLE
Update info..

### ISSUE THREAD

**Issue by ExtremeCopycat** [dularion/streama#229]
Hey.

Is there going to be any updates on this soon? 

I'm realy waiting for the FILE BROWSER

**Comment by gkiko** [comment]
Hi @ExtremeCopycat 
Which task are you referring?

and it would be better to keep questions on gitter 😬

**Comment by ExtremeCopycat** [comment]
I dident know about gitter, sorry for that.

And i have all the files on the same server as the streama server. So i was wondering when the file browser would get out. If i use the system as it is now i would end up with double of all tne files

**Comment by gkiko** [comment]
This issue can be related to [this one](https://github.com/dularion/streama/issues/16)

I think that your problem can be solved by using _Local Video Files_ field in admin settings
> If you already have a directory with your videos, put it here and you will be able to choose them when creating movies or TV shows.

**Comment by ExtremeCopycat** [comment]
i added the directory to my local files to "Second Directory".
I dident understand exactly how to make this work. is there any way to get some help with this?

Do i need to do something special with the folder i have my movies in. Rigt now i have the top folder called "MOVIES" and under it i have a folder for each movie. In that folder i have the movie file and subtitles and some text files. 

Any help is appreciated

**Comment by ExtremeCopycat** [comment]
And should i run v0.3.2 or v1.0.6?

**Comment by gkiko** [comment]
Use the new one - v1.0.6.
I will close this issue as file browser for two directories are is already implemented
