### ISSUE TITLE
A way to display a users created password, when you don't have a mailserver

### ISSUE THREAD

**Issue by z3ntu** [dularion/streama#23]
suggestion above!

**Comment by dularion** [comment]
I think thats great! was thinking about displaying their "invitation-link" that is sent out with the mail, since i don't store the password in the database, just the hash

**Comment by dularion** [comment]
I display it now as part of the user-management. If you copy-paste the link and navigate to it you can set the password. if you use incognito-mode you can even start their login-session afterward and try it out.

**Comment by dularion** [comment]
Reopen if you wish for more changes in that area.

**Comment by z3ntu** [comment]
I will take a look at it, thanks!
