### ISSUE TITLE
Bugs in 1.0.6

### ISSUE THREAD

**Issue by ExtremeCopycat** [dularion/streama#230]
Just showing some of the bugs i found in 1.0.6

## Dashboard Highlights
With one highlight
![image](https://cloud.githubusercontent.com/assets/22444528/20534573/fbffba24-b0e1-11e6-82c4-eecfa490544f.png)

with two highlight 
![image](https://cloud.githubusercontent.com/assets/22444528/20534620/1c1f4f86-b0e2-11e6-8cba-9839162f5e75.png)

Ass you can se when i have one the info text is all messed up and there is no second photo. But on twho theyr on each other with yhe you can see.

## Enter an video after attaching file
After i have attached a file to the movie i can't go in to the movie again. It just keep loading and saying "An internal error occured".
![image](https://cloud.githubusercontent.com/assets/22444528/20534805/d86cee96-b0e2-11e6-8772-41015da5db8e.png)
and the console window for it keeps saying this:
![image](https://cloud.githubusercontent.com/assets/22444528/20534874/1d9d102c-b0e3-11e6-9304-74231ebef052.png)

## Showing admin button on every user
So i made a new user to see how it all looked as a regular user and then i saw that the admin button is always showing.
![image](https://cloud.githubusercontent.com/assets/22444528/20535000/8d008782-b0e3-11e6-95e1-5e311c8743f3.png)
And when i press it it sends me to "http://localhost:8080/#/settings/settings" but then just sends me back to the main page.

## Invite link
When i make a new user the user have to crate a password through a link. But the page that popps up is a little messed.
![image](https://cloud.githubusercontent.com/assets/22444528/20535135/05d33e98-b0e4-11e6-8250-8102e985f2aa.png)
The only thing that looks okei on this page is the password form

I will update with more when i find it. And things that would be cool to have.

I hope you could read all this, my english is not the best so,,,, good luck xD

**Comment by ExtremeCopycat** [comment]
## Search does not work
I can write something in the box but nothing happens. when i press enter it pop ups a little box that just keeps loading. And it gives me the error message "An internal error occurred" down in the corner.
![image](https://cloud.githubusercontent.com/assets/22444528/20543862/bfff2ff2-b107-11e6-9eed-60d6f911af2e.png)
There is a small gray box under the search. Is there supposed to show the movies there?
![image](https://cloud.githubusercontent.com/assets/22444528/20543888/de38d39c-b107-11e6-8241-c06bc4b004ad.png)
When i den press enter this poops ups and just keep loading

**Comment by gkiko** [comment]
Which version of browser did you use?
Where can I find the search box?

**Comment by ExtremeCopycat** [comment]
I'm using Google Chrome  54.0.2840.99 m (if you ment that kinde browser)
The searh box is just left for the dashboard button

**Comment by dularion** [comment]
Hi! Thanks for these bug reports, I'll take a look :)

**Comment by dularion** [comment]
So i fixed it all except the Movie Internal Server Error bug.  I cant recreate it unfortunately. 
Steps I tried: 
- create movie
- attach video file by drag and drop
- reload page

in that moment, I can still load the page no problem. Could you describe the steps to reproduce this?

**Comment by dularion** [comment]
https://github.com/dularion/streama/releases/tag/v1.0.7
