### ISSUE TITLE
Subscription Center - Like netflix allow people to purchase access

### ISSUE THREAD

**Issue by mosquedaoscar** [dularion/streama#231]
It would be interesting to give the opportunity to people who want to sell their own videos, create a paid access system, with paypal

**Comment by z3ntu** [comment]
Duplicate of #221

**Comment by mosquedaoscar** [comment]
It is not duplicated because it does not support downloads or file sharing, only paid access!

**Comment by z3ntu** [comment]
> Subscription Center - Like netflix allow people to purchase access

#221 is a list of features the person wants to see implemented.

**Comment by mosquedaoscar** [comment]
I would particularly like to see this modification implemented

**Comment by chopraaa** [comment]
Pointless modification that will only be used for personal benefit.

Move on. Much more important things to work on.

**Comment by Jeronimo95** [comment]
I agree with @chopraaa. I'm going to close this for the same reason I closed #159. I don't think streama should be the one adding the Subscription system. If people want to use streama as a base for something like that they can integrate it themselves.
