### ISSUE TITLE
war / grails3 1.0.7

### ISSUE THREAD

**Issue by ibrainventures** [dularion/streama#237]
If i execute the war file it terminates with

./streama-1.0.7.war: 1: ./streama-1.0.7.war:FC▒I: not found
./streama-1.0.7.war: 2: ./streama-1.0.7.war: Syntax error: ")" unexpected

1.0.6 is still running fine on the same machine / setup

**Comment by ManuGithubSteam** [comment]
Hmm there is not much to go on but as the output is screwd i would guess its a locale issue.

Do you have tomca7 and apache2 installed ?

**Comment by dularion** [comment]
try again with 1.0.8 please and report back.
