### ISSUE TITLE
Batch Add Files

### ISSUE THREAD

**Issue by popey456963** [dularion/streama#241]
I have a number of films I'd like to add to Streama and at the moment adding multiple files at once is a bit of hard work.  Am I missing something?  Or is this something that might be added at a later date.

**Comment by ManuGithubSteam** [comment]
How do you do it till now ?
I also have no way for batch adding found....
Thanks

**Comment by popey456963** [comment]
I add them one by one @ManuGithubSteam!

**Comment by stemid** [comment]
I think it would be pretty hard to implement since it's hard to predict filenames of files to add, but at least if the file browser could remember which folder it was last in for each show/movie then it would make it slightly easier. That is a simple feature to implement too.

**Comment by phi1-h** [comment]
Maybe it is possible to select a whole folder and upload all playable movies ? I've done something like this in python.

**Comment by dularion** [comment]
Sure, but what do you connect them with? For this we need an auto-detect feature like in xbmc. But I think I have an idea... What if, via a file browser, could select something like 'scan this folder for naming patterns' and then it uses several regex patterns to fetch name / season number / episode number from the file names and then, in a modal dialog, displays the possible results and by confirming the modal you batch create all the matched meta data as well as attach all the files respectively...?

**Comment by popey456963** [comment]
Alternatively just let the user choose the names for all of them in a large list.  Similar to the one used for just one, however with one for every single file chosen.

That'd require less algorithms and would still improve the situation incredibly.

**Comment by phi1-h** [comment]
I like the idea of scanning for regex patterns! I think the user should choose if the files are movies or episodes. This is an huge advantage for anyone who has more than 10 movies!

**Comment by prwilliam** [comment]
I use tinyMediaManager to organize my movies / shows. It does the searching (after the filename) in different movie databases pretty well. Could it be a reasonable approach to import the db from tmm?

**Comment by Silent-Hunter** [comment]
Honestly, why not have the option to simply organize the shows/movies based on the folder/filenames they already have? I keep all my videos organized, with a folder for show name, subfolders for seasons, and each file has the season and episode number.

I kept expecting Streama to automatically have all the videos selectable, but if I have to add each one manually that will take me days!

Is there no way to simply have an option to add the files with the folder/filenames?

**Comment by untotren** [comment]
Perhaps reading the Emby open source file crawler may help?  I even have xml file info for each file, I can share some info with the dev on how I do this if needed?

**Comment by dularion** [comment]
theres something like this under development. check https://github.com/dularion/streama/tree/v1.1_bulk_create

**Comment by dularion** [comment]
I am finally done! phew --- added the PR: https://github.com/dularion/streama/pull/425
