### ISSUE TITLE
BETA 1.07: Can't login for a long time/ Automatic logout

### ISSUE THREAD

**Issue by ManuGithubSteam** [dularion/streama#244]
Hi

Ok so here is what i do:

dynas:86 -> gives me the login window
Login with admin/admin
I got a few seconds to work like add a movie or so...
After that few seconds the server will behave sketchy like no guessing from moviedb or so. It will be unresponsive.
So i press F5 -> im back at the login window.

So basically i get logged out of the server after a few seconds and that not even in a proper way so that i get redirected to the login screnn....

Im unsing 1.07 beta, localy deplyoed/autostartet.
Browser Firefox

Any ideas how to stay longer logged in ?

Thanks

**Comment by dularion** [comment]
This sounds pretty bad. Let me try to reproduce and get back to you. In the meantime, can anyone else confirm this?

**Comment by ManuGithubSteam** [comment]
Ok this seems to be a Brwoser issue. I used chromium now for the day and i stay logged in for at least 2 hours :-)
