### ISSUE TITLE
"Local file" not sorted

### ISSUE THREAD

**Issue by ManuGithubSteam** [dularion/streama#245]
Hi

When adding local files, the folders in the main folder are not sorted. At least not after A-Z which would make the most sense for finding a specific file.

Thanks

**Comment by dularion** [comment]
Thank you for this, makes perfect sense! 
I'll add this asap :)

**Comment by ManuGithubSteam** [comment]
I googled around and i think a simple .sort() in the line   $scope.localFiles = data; to   $scope.localFiles = data.sort();
should do it.

However i was not able to build the newest grails3 source so i can not test this. :-(

**Comment by dularion** [comment]
fixed in https://github.com/dularion/streama/releases/tag/v1.0.9_1
