### ISSUE TITLE
Question: How to compile the grails3 branch ?

### ISSUE THREAD

**Issue by ManuGithubSteam** [dularion/streama#246]
Hi 
I'm in the process of translating streama to German. However, i can not test the new grails3 branch as there is no grails to build it.

Ho do i build the new grails3 branch ?

[manuel@phobos streama]$ grailsw war ROOT.war -Dgrails.env=production
bash: grailsw: command not found

(grails is installed on my arch box)

Thanks!

**Comment by ManuGithubSteam** [comment]
Edit:

It does not seem possible to extract and put back togehter a war file as the files are in compiled form in it. So i see no way to test my translation for now.

I'm curious how the grails3 branch is compiled :-)

**Comment by gkiko** [comment]
see .travis.yml file on docker branch

**Comment by ManuGithubSteam** [comment]
Thanks gkiko

I looked at the file but it seems to be used to build and or deploy a docker of streama. I dont want to do this. How is this file related?

I want to create a .war file out of the grails3 branch. However the command to build the .war file from the master branch (as written in the wiki/readme) does not work.

Do you know how to build a war file out of the grails3 branch ?

Thanks

**Comment by gkiko** [comment]
Sorry, I forgot that default command was missing from .Travis.yml: gradle
assemble

**Comment by ManuGithubSteam** [comment]
Thank you! Now it actually tries to build something but it fails:

[manuel@phobos streama]$ gradle assemble

FAILURE: Build failed with an exception.

* Where:
Build file '/mnt/data/DIY_NAS/STREAMA/streama/build.gradle' line: 26

* What went wrong:
A problem occurred evaluating root project 'streama'.
> Failed to apply plugin [class 'io.spring.gradle.dependencymanagement.DependencyManagementPlugin']
   > Could not create task of type 'DependencyManagementReportTask'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 13.065 secs
#

Any Ideas ?

**Comment by lclc98** [comment]
I ran ./gradlew build and it outputs a streama-*.war, which I renamed to ROOT.war and moved to tomcat7

**Comment by ManuGithubSteam** [comment]
Thanks this worked :-)

It builds now but there is no build/lib folder. Where did the .war file go ?? 

Any ideas ?

**Comment by lclc98** [comment]
It might be build/libs
