### ISSUE TITLE
Webapp says Base Path is saved, but does not save; refuses to play videos

### ISSUE THREAD

**Issue by jwcrawley** [dularion/streama#249]
Webapp will not save my actual IP address as listed above, and defaults back to http://localhost:8080. 
 
Error after setup:

You video get's included using the wrong Base Path, but you are browsing the page via "http://192.168.1.178:8080/". Make sure you set the correct Base Path in the settings and that you are using it to browse the application.

Fix: Going into MySQL,  database="strema"    table="settings"    settings_key="Base Url" and set it to http://192.168.1.178:8080 . Doing so makes the videos now play as they should.

**Comment by lclc98** [comment]
If you are running it in tomcat7 are you getting any error's in their logs?

**Comment by jwcrawley** [comment]
I did the standard Linux install. My only differences is I have my data directory in /opt/movies with appropriate permissions.

I don't know if Tomcat is the standard used. I followed the guide here : https://github.com/dularion/streama/wiki/Local-Streama-Setup

**Comment by lclc98** [comment]
Ok, do you have any logs for it?

**Comment by jwcrawley** [comment]
I do, but it's a whole bunch of API call fails to that movie database. I've fixed that. 

Like I said, it's verifying the Base Path, but not saving it into MySQL. It's changing other content - I'm watching it from mysql console.

**Comment by jwcrawley** [comment]
Since I directly modified the DB in the stated "FIX" localtion at my root comment, etherying is functioning normally.

**Comment by ManuGithubSteam** [comment]
Hmm i do not see this issue (with 1.07).

I have a local nas on 192.168.0.100 (diynas) and i use streama on Port 86 and it works fine from the start.

My base url http://diynas:86

I had to change the port in the application.yaml file tho.

I don't use the tomcat deploy method, as it seems to lead to crashes on my setup and interferes with some functions. I just use the war file locally with ./*.war

**Comment by dularion** [comment]
please try installing with https://github.com/dularion/streama/wiki/Getting-started-with-v1 and reopen this if the problem persists. if so, please provide installation details, like jdk version, ubuntu version etc.
