### ISSUE TITLE
Streama 1.0.8 No login possible, window not shown

### ISSUE THREAD

**Issue by ManuGithubSteam** [dularion/streama#250]
Hi

I just wanted to try out the new 1.08 release. It starts up fine but there is no login window on the blackish streama background to login into it.

![screenshot_20170115_131828](https://cloud.githubusercontent.com/assets/3456994/21962429/118838d0-db26-11e6-8b4a-79452a1a24af.png)

Affected browsers so far:

Chrome
Chromium
Firefox

root@diynas:/nas/server/streama# INFO streama.Application - Starting Application on diynas with PID 3659 (started by root in /nas/server/streama)
DEBUG streama.Application - Running with Spring Boot v1.3.3.RELEASE, Spring v4.2.5.RELEASE
INFO streama.Application - The following profiles are active: production

Configuring Spring Security Core ...
... finished configuring Spring Security Core

INFO streama.Application - Started Application in 34.578 seconds (JVM running for 40.397)
Grails application running at http://localhost:86 in environment: production

**Comment by dularion** [comment]
Oops. Will take a look later

**Comment by jasonbiddle** [comment]
Jo

**Comment by jasonbiddle** [comment]
Hi sexy

**Comment by dularion** [comment]
Uploading fix in new release now

**Comment by dularion** [comment]
https://github.com/dularion/streama/releases/tag/v1.0.9

**Comment by dularion** [comment]
hm something is still not right. will investigate further when i find the time. in the meantime, ill take v1.0.8 and 1.0.9 back offline

**Comment by dularion** [comment]
Try again now :)
