### ISSUE TITLE
Docker Installation Error (Windows)

### ISSUE THREAD

**Issue by r0f1** [dularion/streama#251]
Hi, 
I downloaded, configured (with [this](https://dularion.github.io/streama/) configuration) and started a mysql container and started the streama container with this command

    docker run -d --name=“streama” -p 8080:8080 -p 4000:4000 -v /data:/data -e “MYSQL_HOST=mysqlhost” -e “MYSQL_PORT=3306” -e “MYSQL_DB=streama” -e “MYSQL_USER=streama” -e “MYSQL_PASSWORD=streama” whatever/streama

However, I get an error message.

    ERROR spi.SqlExceptionHelper  - Table "ROLE" not found; SQL statement: ...

What am I doing wrong?

[Screenshot](https://imgur.com/a/z3VFw)
[Full error message](http://pastebin.com/vY1eu1Wk)

**Comment by gkiko** [comment]
`whatever/streama` image is no longer maintained. Please see this one [gkiko/streama](https://hub.docker.com/r/gkiko/streama/)

**Comment by atom2ueki** [comment]
@gkiko can you share how you made this image (Dockerfile) or how can I made this docker image with a link database, e.g. MySql, because most of use case, the container require restart, data cannot just lost

**Comment by gkiko** [comment]
To build docker image run `docker build -t gkiko/streama:latest .`
Current image does not support setting database connection string without editing `grails-app/conf/application.yml`.

To point the grails app to your external MySql installation edit Dockerfile and application.yml. In Dockerfile change this line `CMD ["-Dgrails.env=production", "-jar", "streama.war"]` and in application.yml update your database url.

Not very convenient 😕
