### ISSUE TITLE
can't get it start 

### ISSUE THREAD

**Issue by xiaomingfuckeasylife** [dularion/streama#252]
when i run ./grailws run-war . then he give me this as a return  Zabit (SIGKILL) . i have no idea what the heck is this . can anyone give me a hand .

**Comment by ManuGithubSteam** [comment]
Hi

just download the newest release and start it with: ./streama*.war

I belive the newest bugfix release 1.09 must be compiled first but you can try with 1.08 first. If that works. Wait till 1.09 gets publised as a war file or compile it yourself. How to do that is answerd in an closed issue (How to compile grails3 branch)

**Comment by dularion** [comment]
The 1.0.8 is stable again I believe

**Comment by dularion** [comment]
please try https://github.com/dularion/streama/wiki/Getting-started-with-v1 and reopen if it doesnt work
