### ISSUE TITLE
Subtitle background opacity

### ISSUE THREAD

**Issue by pronetbr** [dularion/streama#253]
Hello, there! Congratulations on this app.

Is there any way to make the subtitle background transparent? 

Thank you!

**Comment by ManuGithubSteam** [comment]
AFAIK the subtitle is a mp4 feature and not an overlay so it is not possible at the moment but there are plans to make it an overlay and then is should be no biggy.

**Comment by dularion** [comment]
Yup!

**Comment by pronetbr** [comment]
That's great!! Thank you.
