### ISSUE TITLE
grailsw: JAVA_HOME environment variable is not set

### ISSUE THREAD

**Issue by imkimchi** [dularion/streama#255]
![image](https://cloud.githubusercontent.com/assets/13452168/22000122/7f5d2cea-dc0b-11e6-9c00-60f42b0ed336.png)

It says the error when I try to execute `make` command.
This is all of the error I got below.

`./grailsw war Dockerfile/tomcat/ROOT.war -Dgrails.env=docker
grailsw: JAVA_HOME environment variable is not set
make: *** [grails] Error 1`

**Comment by dularion** [comment]
I'm not sure about the dockerfile as it was contributed from other devs, but have you tried executing the current 1.0.8? see https://github.com/dularion/streama/wiki/Getting-started-with-v1

**Comment by pronetbr** [comment]
Hey there, imkimchi.

I also got this error from my first try, but easily fixed it by adding manually the "JAVA_HOME" (using as value the Java SDK folder) for my system variables. 

Hope it helps!

**Comment by imkimchi** [comment]
Solved problem!
