### ISSUE TITLE
1.0.9 local file adding does not work anymore

### ISSUE THREAD

**Issue by ManuGithubSteam** [dularion/streama#259]
Hi

I just downloaded 1.08. It shows up internally as 1.09.

However, i can not add local files anymore. There is an undefined error and the icon/tab whatever does not show anymore:

![screenshot_20170117_173348](https://cloud.githubusercontent.com/assets/3456994/22029775/d78a2a96-dcdb-11e6-9080-a2ad297d47d8.png)

Any ideas ?

**Comment by dularion** [comment]
Hm this works for me, running by execution with openjdk8. 
can you tell me what the output of the browser and server log are? also, is it maybe a permission issue? please go back into the settings and re-validate the local file directory.

**Comment by ManuGithubSteam** [comment]
Hmm,
Well i have write permission on the directory. As i execute streama with root this whould not be the issue. 0r does it have to be a special user like tomcat7 ?

I get this when i try to revalidate:

![screenshot_20170117_190649](https://cloud.githubusercontent.com/assets/3456994/22033386/9c9f77da-dce8-11e6-89b9-b1c0b44d9e33.png)

I use oracle java. Where are the server logs ?

Thanks

**Comment by dularion** [comment]
That's not the error. Hm something is quite strange. Any way you could give me access to the application so I can debug?

**Comment by dularion** [comment]
Are you using admin or another user?

**Comment by ManuGithubSteam** [comment]
I use admin. I only ran it locally in my network. Where are the server logs located to give to you ?
What else on info do you need ?
Thnanks

**Comment by dularion** [comment]
The server logs are below the output you sent me, the part about the application running. If there is nothing there, then it isn't an error, but something ujintentislly wrong in a piece of code. Only, I don't have the issue and I just deployed it last night with the current 1.0.8

**Comment by dularion** [comment]
Could you look me up on gitter? We could chat about the issue

**Comment by ManuGithubSteam** [comment]
on it :-)
