### ISSUE TITLE
No video and (null) after upload when attempting to stream.

### ISSUE THREAD

**Issue by thesupergeek** [dularion/streama#26]
After uploading a video in a format compatible with HTML5, I am unable to play the video. There is no video, and the "time left" section says (null) which tells me that it is not correctly reading/indexing the uploaded media. I know it correctly uploads, because it shows up something like: 4f78d9fb11b331580933dc1b6e85e5186eb4edb32a4b41451a39b18c15ef1aec.mp4 in /data/streama, but the video player is unable to play it. Also, the name for the file listed next to the play bar is incorrect, and not the one I uploaded. Here is what I see after upload: http://i.imgur.com/izHOqt1.png?1

If there is any way to dump Grails log files, let me know and I will do that.

thank you.

**Comment by dularion** [comment]
How did you test whether it is html5 compatible? did you do the quick-and-dirty test of opening a new browser tab and dragging it in, and seeing if the default player shows up?

**Comment by thesupergeek** [comment]
Yes, and all three video I tried did.

**Comment by dularion** [comment]
Hmmm.. What kind of javascript errors do you have?

**Comment by dularion** [comment]
Btw, others have used https://gist.github.com/ to send me stacktraces

**Comment by thesupergeek** [comment]
http://imgur.com/w3EuuMI

Lots of resource not found errors.

Failed to load resource: the server responded with a status of 400 (Bad
Request)
http://localhost:8080/streama/file/serve/70b20bfb23310abff57417c290a3944ba8746a068ef5255a1d08ccd811522aa7.mp4
Failed to load resource: net::ERR_CONNECTION_REFUSED
http://192.168.0.46:8080/streama/viewingStatus/save.json?currentTime=0&runtime=NaN&videoId=4
Failed to load resource: the server responded with a status of 406 (Not
Acceptable)
application-f0aae69eb699cbdbed2a8f29352847a6.js:379 GET
http://192.168.0.46:8080/streama/viewingStatus/save.json?currentTime=0&runtime=NaN&videoId=4
406 (Not Acceptable)(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:379l @
application-f0aae69eb699cbdbed2a8f29352847a6.js:375B.f @
application-f0aae69eb699cbdbed2a8f29352847a6.js:373(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:408k.$eval @
application-f0aae69eb699cbdbed2a8f29352847a6.js:423k.$digest @
application-f0aae69eb699cbdbed2a8f29352847a6.js:420k.$apply @
application-f0aae69eb699cbdbed2a8f29352847a6.js:424(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:383
application-f0aae69eb699cbdbed2a8f29352847a6.js:379 GET
http://192.168.0.46:8080/streama/viewingStatus/save.json?currentTime=0&runtime=NaN&videoId=4
406 (Not Acceptable)(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:379l @
application-f0aae69eb699cbdbed2a8f29352847a6.js:375B.f @
application-f0aae69eb699cbdbed2a8f29352847a6.js:373(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:408k.$eval @
application-f0aae69eb699cbdbed2a8f29352847a6.js:423k.$digest @
application-f0aae69eb699cbdbed2a8f29352847a6.js:420k.$apply @
application-f0aae69eb699cbdbed2a8f29352847a6.js:424(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:383
application-f0aae69eb699cbdbed2a8f29352847a6.js:379 GET
http://192.168.0.46:8080/streama/viewingStatus/save.json?currentTime=0&runtime=NaN&videoId=4
406 (Not Acceptable)(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:379l @
application-f0aae69eb699cbdbed2a8f29352847a6.js:375B.f @
application-f0aae69eb699cbdbed2a8f29352847a6.js:373(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:408k.$eval @
application-f0aae69eb699cbdbed2a8f29352847a6.js:423k.$digest @
application-f0aae69eb699cbdbed2a8f29352847a6.js:420k.$apply @
application-f0aae69eb699cbdbed2a8f29352847a6.js:424(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:383
application-f0aae69eb699cbdbed2a8f29352847a6.js:379 GET
http://192.168.0.46:8080/streama/viewingStatus/save.json?currentTime=0&runtime=NaN&videoId=4
406 (Not Acceptable)(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:379l @
application-f0aae69eb699cbdbed2a8f29352847a6.js:375B.f @
application-f0aae69eb699cbdbed2a8f29352847a6.js:373(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:408k.$eval @
application-f0aae69eb699cbdbed2a8f29352847a6.js:423k.$digest @
application-f0aae69eb699cbdbed2a8f29352847a6.js:420k.$apply @
application-f0aae69eb699cbdbed2a8f29352847a6.js:424(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:383
application-f0aae69eb699cbdbed2a8f29352847a6.js:379 GET
http://192.168.0.46:8080/streama/viewingStatus/save.json?currentTime=0&runtime=NaN&videoId=4
406 (Not Acceptable)(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:379l @
application-f0aae69eb699cbdbed2a8f29352847a6.js:375B.f @
application-f0aae69eb699cbdbed2a8f29352847a6.js:373(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:408k.$eval @
application-f0aae69eb699cbdbed2a8f29352847a6.js:423k.$digest @
application-f0aae69eb699cbdbed2a8f29352847a6.js:420k.$apply @
application-f0aae69eb699cbdbed2a8f29352847a6.js:424(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:383
application-f0aae69eb699cbdbed2a8f29352847a6.js:379 GET
http://192.168.0.46:8080/streama/viewingStatus/save.json?currentTime=0&runtime=NaN&videoId=4
406 (Not Acceptable)(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:379l @
application-f0aae69eb699cbdbed2a8f29352847a6.js:375B.f @
application-f0aae69eb699cbdbed2a8f29352847a6.js:373(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:408k.$eval @
application-f0aae69eb699cbdbed2a8f29352847a6.js:423k.$digest @
application-f0aae69eb699cbdbed2a8f29352847a6.js:420k.$apply @
application-f0aae69eb699cbdbed2a8f29352847a6.js:424(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:383
application-f0aae69eb699cbdbed2a8f29352847a6.js:379 GET
http://192.168.0.46:8080/streama/viewingStatus/save.json?currentTime=0&runtime=NaN&videoId=4
406 (Not Acceptable)(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:379l @
application-f0aae69eb699cbdbed2a8f29352847a6.js:375B.f @
application-f0aae69eb699cbdbed2a8f29352847a6.js:373(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:408k.$eval @
application-f0aae69eb699cbdbed2a8f29352847a6.js:423k.$digest @
application-f0aae69eb699cbdbed2a8f29352847a6.js:420k.$apply @
application-f0aae69eb699cbdbed2a8f29352847a6.js:424(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:383
application-f0aae69eb699cbdbed2a8f29352847a6.js:379 GET
http://192.168.0.46:8080/streama/viewingStatus/save.json?currentTime=0&runtime=NaN&videoId=4
406 (Not Acceptable)(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:379l @
application-f0aae69eb699cbdbed2a8f29352847a6.js:375B.f @
application-f0aae69eb699cbdbed2a8f29352847a6.js:373(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:408k.$eval @
application-f0aae69eb699cbdbed2a8f29352847a6.js:423k.$digest @
application-f0aae69eb699cbdbed2a8f29352847a6.js:420k.$apply @
application-f0aae69eb699cbdbed2a8f29352847a6.js:424(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:383
application-f0aae69eb699cbdbed2a8f29352847a6.js:379 GET
http://192.168.0.46:8080/streama/viewingStatus/save.json?currentTime=0&runtime=NaN&videoId=4
406 (Not Acceptable)(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:379l @
application-f0aae69eb699cbdbed2a8f29352847a6.js:375B.f @
application-f0aae69eb699cbdbed2a8f29352847a6.js:373(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:408k.$eval @
application-f0aae69eb699cbdbed2a8f29352847a6.js:423k.$digest @
application-f0aae69eb699cbdbed2a8f29352847a6.js:420k.$apply @
application-f0aae69eb699cbdbed2a8f29352847a6.js:424(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:383
application-f0aae69eb699cbdbed2a8f29352847a6.js:379 GET
http://192.168.0.46:8080/streama/viewingStatus/save.json?currentTime=0&runtime=NaN&videoId=4
406 (Not Acceptable)(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:379l @
application-f0aae69eb699cbdbed2a8f29352847a6.js:375B.f @
application-f0aae69eb699cbdbed2a8f29352847a6.js:373(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:408k.$eval @
application-f0aae69eb699cbdbed2a8f29352847a6.js:423k.$digest @
application-f0aae69eb699cbdbed2a8f29352847a6.js:420k.$apply @
application-f0aae69eb699cbdbed2a8f29352847a6.js:424(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:383
application-f0aae69eb699cbdbed2a8f29352847a6.js:379 GET
http://192.168.0.46:8080/streama/viewingStatus/save.json?currentTime=0&runtime=NaN&videoId=4
406 (Not Acceptable)(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:379l @
application-f0aae69eb699cbdbed2a8f29352847a6.js:375B.f @
application-f0aae69eb699cbdbed2a8f29352847a6.js:373(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:408k.$eval @
application-f0aae69eb699cbdbed2a8f29352847a6.js:423k.$digest @
application-f0aae69eb699cbdbed2a8f29352847a6.js:420k.$apply @
application-f0aae69eb699cbdbed2a8f29352847a6.js:424(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:383
application-f0aae69eb699cbdbed2a8f29352847a6.js:379 GET
http://192.168.0.46:8080/streama/viewingStatus/save.json?currentTime=0&runtime=NaN&videoId=4
406 (Not Acceptable)(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:379l @
application-f0aae69eb699cbdbed2a8f29352847a6.js:375B.f @
application-f0aae69eb699cbdbed2a8f29352847a6.js:373(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:408k.$eval @
application-f0aae69eb699cbdbed2a8f29352847a6.js:423k.$digest @
application-f0aae69eb699cbdbed2a8f29352847a6.js:420k.$apply @
application-f0aae69eb699cbdbed2a8f29352847a6.js:424(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:383
application-f0aae69eb699cbdbed2a8f29352847a6.js:379 GET
http://192.168.0.46:8080/streama/viewingStatus/save.json?currentTime=0&runtime=NaN&videoId=4
406 (Not Acceptable)(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:379l @
application-f0aae69eb699cbdbed2a8f29352847a6.js:375B.f @
application-f0aae69eb699cbdbed2a8f29352847a6.js:373(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:408k.$eval @
application-f0aae69eb699cbdbed2a8f29352847a6.js:423k.$digest @
application-f0aae69eb699cbdbed2a8f29352847a6.js:420k.$apply @
application-f0aae69eb699cbdbed2a8f29352847a6.js:424(anonymous function) @
application-f0aae69eb699cbdbed2a8f29352847a6.js:383
application-f0aae69eb699cbdbed2a8f29352847a6.js:379 GET
http://192.168.0.46:8080/streama/viewingStatus/save.json?currentTime=0&runtime=NaN&videoId=4
406 (Not Acceptable)

**Comment by dularion** [comment]
does it work if you try to access it directly? 

http://localhost:8080/streama/file/serve/70b20bfb23310abff57417c290a3944ba8746a068ef5255a1d08ccd811522aa7.mp4

**Comment by thesupergeek** [comment]
Works like you would expect it to.

**Comment by dularion** [comment]
Ok, this is very strange idea, but: some people suggest that this may have to do with adblock? Do you have it running? and if so, could you disable it as a test?

**Comment by thesupergeek** [comment]
I have disabled adblock, no luck, but I found the issue. Streama's
JavaScript is looking at localhost to provide the file, but I am accessing
it on a remote server. When you have me that link, where it said
"localhost" I assumed you meant the ip the server was running from, so I
replaced it with that. I do not know much about JS, but AFAIK, it runs
client side, so when it looks for filename at localhost, instead of the
servers IP, it will find nothing because in most cases, the javascript is
not running the same place as the file is hosted.

**Comment by thesupergeek** [comment]
Sorry, english is not my first language, so that may be hard to understand.
I will try again.

The javascript is looking for hosted video file xxxx@localhost, but since
it is running on a pc that is not the server where the file is hosted, it
is looking in the wrong spot. It should be looking at xxxx@serverip.

**Comment by dularion** [comment]
Aha! That gets us closer to the issue :) go into `grails-app/conf/Config.groovy` and edit line 121 (or line 124, depending on how you run it. To be safe, just put the path in both)

**Comment by thesupergeek** [comment]
yep, that works great, but that really seems like a very bad way to go
about it. Is there a way to autodetect that? Or maybe I could write a
python script that could ask the user and configure those settings and run
./grailsw run-war on first setup.

**Comment by dularion** [comment]
I can add that url to the settings actually. In my most recent commit I added some base settings like the storage path and the api-key. Ill add the base url right away :)

**Comment by thesupergeek** [comment]
Alright, good plan, thank you.

**Comment by dularion** [comment]
Added it now with commit https://github.com/dularion/streama/commit/e9545287f618b404ced61f8d6f3378aa999c5ce9

**Comment by dularion** [comment]
Is this issue closed?

**Comment by dularion** [comment]
Please reopen if problem persists
