### ISSUE TITLE
Bittorrent Support - Feature Request

### ISSUE THREAD

**Issue by xlogik** [dularion/streama#262]
Hi All,
I have an "feature request" which consist of using the BitTorrent protocol as a media source for adding additional content.  This could be done by using something like webTorrent (https://github.com/feross/webtorrent) or Peerflix (https://github.com/mafintosh/peerflix) to integrate the streaming of audio/video.

**Comment by imkimchi** [comment]
This is a absolutely good idea. I would be working on this feature.

**Comment by xlogik** [comment]
@imkimchi 
Sweet! How's the development coming along? Were you able to get it working? If so, when do you think you'll be able to make a pull request? I would love to test this feature!

**Comment by imkimchi** [comment]
I don't have enough time to work on it lately, probably next week!

**Comment by xlogik** [comment]
Sweet, I look forward to testing it!

**Comment by joshjames** [comment]
I have this of sorts.. but using a bittorrent proxy service.. I have coded an add-on that allows me to load a torrent in to the library, it will then pass the torrent to the proxy service which outputs the file direct over Http, which then loads the file in to the library and adds the movie/show.
the benefit of doing it like this is I can start watching it immediately.(less than 10 seconds from loading the torrent to watching it)

**Comment by Jeronimo95** [comment]
Closing as we're not going to support features that may directly violate copyright laws.
