### ISSUE TITLE
Refresh the page after uploading a video - Feature Request

### ISSUE THREAD

**Issue by imkimchi** [dularion/streama#263]
![jan-17-2017 23-04-58](https://cloud.githubusercontent.com/assets/13452168/22050514/7b38672a-dd09-11e6-8dd2-4010564e155b.gif)

I just found that the page still says `No Video file yet` Even though I just uploaded a video file for the movie so I had to refresh the page manually. I want it to refresh the page automatically after user uploads a video so the page can fetch the video data. Would you like to add this feature in your project? I would implement this feature if you say yes :)

**Comment by dularion** [comment]
Great issue, with a gif and everything! included in next build :)
