### ISSUE TITLE
SocketException

### ISSUE THREAD

**Issue by jamierocks** [dularion/streama#27]
2015-07-31 23:48:07,707 [http-bio-8080-exec-7] ERROR errors.GrailsExceptionResolver  - SocketException occurred when processing request: [GET] /streama/file/serve/0be7417b0f62c279058c2159b12f431e12b03ac8bb53bd6c7510a8841f535ce3.m4v

Full stack trace - http://hastebin.com/yekiyufure.avrasm

This exception is thrown upon the launch of a TV Show.

This could just be that you don't have support for m4v's, or I have set Streama up wrong.

**Comment by dularion** [comment]
This is what someone else said who had a similar issue: 

It turns out that this error was occurring because the app is running on a server behind a load balancer, which is attempting to cache files that pass through it. It's unable to cache the larger files as it has limited disk space, and the download fails.

Could this apply for your situation?

**Comment by jamierocks** [comment]
Not that I'm aware of.

I'm just running with grails run-war

**Comment by dularion** [comment]
Oh wait. I just read the beginning. Its the bug listed in known issues in the bottom of the readme file: 
`getOutputStream() has already been called for this response`

This is merely cosmetic and nothing to worry about. The fact that your file does not play has most likely to do with the codec. Did you do the quick-and-dirty test of opening a new browser tab and dragging it in, and seeing if the default player shows up? If the file downloads instead, its not compatible.

**Comment by jamierocks** [comment]
Okay, I think I found the issue then. While Chrome will happily load the file, it won't play the file :|

**Comment by dularion** [comment]
What exactly do you mean? Does the browser-tab test show that the file is actually compatible, but streama doesnt get it?

**Comment by jamierocks** [comment]
As in if I navigate to the file, it doesn't play.

**Comment by dularion** [comment]
So it is a codec issue then, if I understand you correctly. A quick fix is to use HandBrake for conversion to H.264. It is super high on my feature list to add automatic conversion in the future :)

**Comment by jamierocks** [comment]
Yep. Using Handbrake as we speak.

**Comment by jamierocks** [comment]
OK, it would actually be a case of itunes having DRM management on their m4v's :|

**Comment by dularion** [comment]
oh.. :/ Thats unfortunate ... :(
