### ISSUE TITLE
language drop down

### ISSUE THREAD

**Issue by mazzucato** [dularion/streama#270]
options of the language dropdown menu

![aa](https://cloud.githubusercontent.com/assets/9062249/22168618/9d1d2dae-df4c-11e6-924b-d60a14422538.png)

**Comment by mazzucato** [comment]
highlights dropdown too

**Comment by dularion** [comment]
Hi, thanks for your feedback. Which browser and operating system is this?

**Comment by ManuGithubSteam** [comment]
i see the same thing in chromium on arch linux. But its not a big issue i think....

**Comment by mazzucato** [comment]
chrome in debian jessie

**Comment by dularion** [comment]
thanks @ddannewitz
