### ISSUE TITLE
Faster movie adding - small requests

### ISSUE THREAD

**Issue by ManuGithubSteam** [dularion/streama#273]
Hi Dularion,

I just came around to test the new 11 release :-) Works great so far.

As i deleted my mysql database i have to readd some movies and i noticed some things that would improve workflow for adding files faster:

1. Remember what was chosen in the File upload dialog. If i used local file last time, i want streama to remember that. This saves one click :-) THANK you for the search feature btw!

2. When i just added a movie file and clicked close. Chances are high i want to add another one...

There should be ticking box "Bulk Add"  in the moviedb search filed. If this is ticked, instantly after adding a movie and clicking close, the moviedb seach filed opens and you can add another movie.

What do you think ?

**Comment by dularion** [comment]
Hi! 
Check out this issue: https://github.com/dularion/streama/issues/241

**Comment by dularion** [comment]
You're welcome to add what you've written here to the other issue
