### ISSUE TITLE
How can i develop in the new version?

### ISSUE THREAD

**Issue by robsonolivesa** [dularion/streama#275]
When I try to import to GGTS it is not working, how do I develop it in the new version?

**Comment by dularion** [comment]
What's ggts? Best is to use intellij IDEA and open the build.gradle file in the directory. That way you initialize everything with gradle. Then, on the right, in the list of gradle tasks you gotta choose application > build app (not 100% sure about the last step, will supply Screenshots shortly)

**Comment by robsonolivesa** [comment]
I think there must be some difficulty with IDE. Thank you for your help.

**Comment by robsonolivesa** [comment]
GGTS is Groovy Grails Tool Suite, a IDE.

**Comment by robsonolivesa** [comment]
GGTS is Groovy Grails Tool Suite, a IDE.

**Comment by robsonolivesa** [comment]
Thank you for your help, it work!

**Comment by jguerinet** [comment]
@dularion I would recommend putting those instructions in the README to potentially help others who may want to contribute. I've never used Grails before and had no idea how to get the code running into I randomly stumbled upon this issue. (I would also mention that you should supply a valid application.yml file and put the right file name in bootRun in the build file).

**Comment by dularion** [comment]
Hi! Ive made a tutorial on this: https://www.youtube.com/watch?v=hn9grcWbBFM&t=11s

**Comment by jguerinet** [comment]
Completely missed that, thanks for the link!
