### ISSUE TITLE
Possibility to add/see movies in other languages

### ISSUE THREAD

**Issue by ManuGithubSteam** [dularion/streama#276]
Hi

I have German and English movies. For now there is no way to know if the audio of the movie is in English or German.

I propose a language flag and a possibility to set a default language and change it in the settings.

This way we can see in the details of he movie what language it is.

Thanks

**Comment by dularion** [comment]
Thank you for your post. There is already an open issue for this here https://github.com/dularion/streama/issues/225 
Can you please add your use case to that issue? Then I will close this as a duplicate
