### ISSUE TITLE
IMDB Links are broken

### ISSUE THREAD

**Issue by z3ntu** [dularion/streama#28]
For me they all point to http://www.imdb.com/title/ .

**Comment by dularion** [comment]
True! Will get right on it

**Comment by dularion** [comment]
This has now been resolved, IMDB ids will now be fetched and saved when a movie or show are saved. To update existing shows & movies, navigate to http://localhost:8080/streama/bulk/fetchImdbIdForAllMoviesAndShow

**Comment by dularion** [comment]
Please close this issue if everything worked out.

**Comment by z3ntu** [comment]
Works!
