### ISSUE TITLE
Amazon S3 Storage

### ISSUE THREAD

**Issue by AKPWebDesign** [dularion/streama#280]
It would be cool if there was an option to use [Amazon S3](https://aws.amazon.com/s3/) for file storage. (*Note: This is not Amazon Cloud, which I've seen mentioned in another feature request.*)

**Comment by gkiko** [comment]
Hi! I suppose you have already seen my answer [here](https://github.com/dularion/streama/issues/14#issuecomment-152086560).

Can't fuse handle the problem you are facing?

**Comment by AKPWebDesign** [comment]
I hadn't seen that answer, actually, so thanks for pointing that out. That's a good enough solution for me.
