### ISSUE TITLE
Text pulled from TheMovieDB contains unsupported characters

### ISSUE THREAD

**Issue by Flex101** [dularion/streama#284]
I recently added a number of episode descriptions to TheMovieDB using copy and paste.
I didn't notice that the text contained angled quotation marks which have [unique character codes](http://practicaltypography.com/straight-and-curly-quotes.html).
These characters are supported by TheMovieDB but not by Streama.

The characters used to be converted to straight quotation marks (") when imported into Streama, however now they are turned in this ���.

**Comment by dularion** [comment]
Hm, what collation does your database have?

**Comment by Flex101** [comment]
I don't think it has anything to do with my database because some episode descriptions I have now have the angled quotations in them and Streama is displaying them fine. So I was wrong when I said Streama doesn't support the characters, it does. But something about the process of pulling the descriptions from TheMovieDB has changed, which now causes the angled quotations to be converted ��� along the way.

**Comment by Flex101** [comment]
Ok I have just refetched some episodes and the ��� have disappeared. Looks like the problem was on TheMovieDB's side. Sorry!

**Comment by Jeronimo95** [comment]
This was fixed in #536
