### ISSUE TITLE
TV shows can't read number of episodes in Manage Content area

### ISSUE THREAD

**Issue by Flex101** [dularion/streama#285]
_**This maybe because I am still using the mysql data source with 1.0.11 rather than the new h2.**_

Every show in the TV Shows section under Manage Content has the red triangle in the bottom right corner and shows [blank]/[blank] uploaded when hovered over.

![image](https://cloud.githubusercontent.com/assets/15659112/22408709/3f20ab7e-e675-11e6-91f9-b1fae69c8736.png)

None of my shows are empty and most are fully populated

**Comment by dularion** [comment]
There is a pre-release, if you want to test it

**Comment by Flex101** [comment]
Looks much better in v1.0.19 (from the release page).
However, I think the total number of episodes maybe including deleted episodes.
I have a number of shows showing a few episodes too many,

**Comment by dularion** [comment]
Oh good catch!

**Comment by dularion** [comment]
Added in the v1.0.20 prerelease
