### ISSUE TITLE
German/Deutsch Streama install tutorial

### ISSUE THREAD

**Issue by BenRoe** [dularion/streama#287]
Hello,
i created a german tutorial how to install and setup streama. Maybe it's useful for not english speaking people.
[https://maker-tutorials.com/eigene-streaming-seite-wie-netflix-mit-streama-und-einem-raspberry-pi-3/](https://maker-tutorials.com/eigene-streaming-seite-wie-netflix-mit-streama-und-einem-raspberry-pi-3/)

**Comment by bastilimbach** [comment]
@BenRoe please check you markdown. The link isn't working correctly. It should be `[ Link name ](https://maker-tutorials.com/eigene-streaming-seite-wie-netflix-mit-streama-und-einem-raspberry-pi-3/)`

**Comment by BenRoe** [comment]
thx for the hint. i have edit it.

**Comment by dularion** [comment]
Thanks! You are welcome to add it to the wiki of this project, that way it lasts longer than through an issue!
