### ISSUE TITLE
Question about Shows errors

### ISSUE THREAD

**Issue by ManuGithubSteam** [dularion/streama#289]
Hi

I recently added my first show to streama, but in the management tab, they show up greyish and with an error. However the shows work in the dash window.

![screenshot_20170131_191212](https://cloud.githubusercontent.com/assets/3456994/22478409/faaf3642-e7e9-11e6-8018-b584c42ac948.png)

What does this error mean ?

Thanks

**Comment by Flex101** [comment]
Duplication of issue #285

**Comment by dularion** [comment]
closed for duplication
