### ISSUE TITLE
Video Player Error

### ISSUE THREAD

**Issue by snorlex** [dularion/streama#291]
There seems to be a problem adding the video-file to the player. This is most likely due to a codec-problem. Try converting it to a compatible HTML5 codec, remove the currently attached file and re-add it. If the codecs are fine, check the error log of the server and the base URL in the settings. 

How do i fix this

**Comment by d000000h** [comment]
make sure the video you are adding is html5 video, you might need to convert your video with handbrake to MP4 with the tag Web optimized selected and it will work fine

**Comment by snorlex** [comment]
thanks ill try it out

**Comment by dularion** [comment]
report back if it doesnt work!
