### ISSUE TITLE
Add clear licensing information to files and README

### ISSUE THREAD

**Issue by MagicFab** [dularion/streama#3]
It would be very useful to know what license this is published under (GPLv3, etc.), both in the README and file headers. Thank you for sharing your work.

**Comment by InfernoZeus** [comment]
There's a LICENSE.md file. Isn't that enough?

**Comment by dularion** [comment]
Fixed in this issue: https://github.com/dularion/streama/issues/2

**Comment by dularion** [comment]
Or is this maybe not enough?

**Comment by MagicFab** [comment]
LICENSE.MD is fine, but having this in the description too helps find it and share it faster/easier. It's up to you , this is just a suggestion.

**Comment by dularion** [comment]
I added a reference to the readme now, too. Thanks :)
