### ISSUE TITLE
Can't Install - Errors on Packaging Exception

### ISSUE THREAD

**Issue by Serubin** [dularion/streama#30]
Errors on Packaging Exception while running ./grailsw war ROOT.war and on ./grailsw run-war

The error is: org.codehaus.groovy.grails.compiler.PackagingException: Error occurred processing message bundles: Error starting Sun's native2ascii.

All the requirements are installed. Any ideas?

**Comment by dularion** [comment]
Do you have a longer stacktrace or is this it? also, could you echo out your JAVA_HOME for me? `echo $JAVA_HOME`

**Comment by dularion** [comment]
also, run `java -XshowSettings:properties -version` and paste it here

**Comment by dularion** [comment]
also, I found this: http://www.morkeleb.com/2009/04/04/grails-error-starting-suns-native2ascii/   maybe you have the same issue?

**Comment by Serubin** [comment]
Ah - I think that's it. When I've used java i the past I've always had JAVA_HOME pointing to the jre within the jdk (I think that's what maven likes). Thanks for your help!!
