### ISSUE TITLE
Base URL: if changed to a hosted website - the invite link is broken

### ISSUE THREAD

**Issue by CodeFromCirc** [dularion/streama#301]

**Comment by dularion** [comment]
What do you mean by "default link"?

**Comment by CodeFromCirc** [comment]
I may have done a typo.
What I meant is:
If I change the Base URL, nothing works with the base link (e.g. the email invite link)
Sorry for the typo though.

CodeFromCirc (CircuitRCAY)

**Comment by dularion** [comment]
I'm not sure I am following you.. can you give me an example with example urls just to clarify your issue?
