### ISSUE TITLE
Minimum requirements

### ISSUE THREAD

**Issue by lupoalberto12** [dularion/streama#306]
Hi,
I'm looking for a "CMS" for local video streaming and I found this.
I like it, but I would like if this can work on a Raspberry Pi 2 Mod B (Quad Core @ 900MHz, 1Gb of Ram).
So, which are the minimum requirements?
Can I use it for max two contemporary users?
Thanks.
Bye!

**Comment by lupoalberto12** [comment]
PS.: if I'll use it, I'll translate it in Italian ;) .

**Comment by gkiko** [comment]
Your heap space will run out before the app even launches. At least that's what I get for my 1gb Raspberry :disappointed:

**Comment by lupoalberto12** [comment]
@gkiko even if with swap?
Thanks.

**Comment by gkiko** [comment]
I don't remember if I had swap enabled. You'd better try it yourself.

**Comment by lupoalberto12** [comment]
Thanks.

**Comment by dwalkr** [comment]
I'm running this on an AWS EC2 instance with 512MB - after allocating 2G for swap I was able to get it up and running with no problem

**Comment by gkiko** [comment]
I was deploying streama docker image on 512mb+swap ec2 instance and it was
constantly crashing.

**Comment by lupoalberto12** [comment]
I'm writing Raspbian lite on a SD and I'll try.
Cross fingers.

**Comment by lupoalberto12** [comment]
A night to start it, two hours for a login.
Raspberry Pi2 Mod B, 1GB of RAM + 2GB of SWAP (only 16MB for GPU).
I'm sad.
Thanks anyway.
Bye!

**Comment by lupoalberto12** [comment]
Update: I'm using it on a t2.micro (1 core, 1GB of RAM): it's works like a charms.
So, do someone use it on a Raspberry Pi Mod 3?
I would like bring it in local.

@dularion: it's fantastic, good work!
Bye!

**Comment by dularion** [comment]
Please reopen if there are any more questions/suggestions
