### ISSUE TITLE
Search Show from TheMovieDB Not Working

### ISSUE THREAD

**Issue by danbamboo** [dularion/streama#310]
I noticed that when on the 'Manage Content' page, under TV Shows, the search bar does not populate a list of shows from 'TheMovieDB'.  
![screen shot 2017-02-25 at 9 39 29 pm](https://cloud.githubusercontent.com/assets/6924516/23341801/d67d0bb0-fc0b-11e6-9914-b09bcd7e56d8.png)

This functionality is working when I search for Movies correctly:
![screen shot 2017-02-26 at 10 12 34 am](https://cloud.githubusercontent.com/assets/6924516/23341822/20180446-fc0c-11e6-937e-efcb35b373c1.png)

However, searching for the show 'The OA', I get no results when typing the exact string into the search bar:
![screen shot 2017-02-26 at 10 15 47 am](https://cloud.githubusercontent.com/assets/6924516/23341845/919078f6-fc0c-11e6-8280-c4146f0fc7d1.png)

Now, there is a workaround when I choose 'Create new Show' and search from TheMovieDB, then the show is populated:
![screen shot 2017-02-25 at 9 40 16 pm](https://cloud.githubusercontent.com/assets/6924516/23341835/56dedb44-fc0c-11e6-9f8f-d64e71b03853.png)

I peeked at the source code and could not find any immediate errors.  It does seem like this functionality is setup to be working. 

I really enjoy this project, thanks for all the hard work!

**Comment by mongomay69** [comment]
Manage Content is meant to look at what you've uploaded, it has no need to populate from the MovieDB

**Comment by danbamboo** [comment]
The title of the search bar states "Search Shows from collection or
TheMovieDB", which indicates that it should be doing a lookup from
theMovieDB.  In addition, this functionality works with the Movie search
bar in Manage Content, as pointed out in the issue report.  Also, the
support for doing a MovieDB lookup does seem to be in place in this
location.

If for some reason we didn't want to do a MovieDB search here, than at the
least I believe the search text should read something different (i.e
"Search Shows from collection") to avoid confusion.

Thanks.

**Comment by dularion** [comment]
yes agreed! this is an oversight on my part
