### ISSUE TITLE
File upload failed

### ISSUE THREAD

**Issue by Anderzenn** [dularion/streama#312]
Hello, I'm honestly not sure how to report this issue so I'm just gonna put it like this:
I'm trying to upload a movie file (of type .mkv) does Streama not support this file type? Or am I having some other issue.

Here's a screenshot:
![Image of upload fail](http://i.imgur.com/ongtrts.png)

**Comment by Anderzenn** [comment]
Update: I tried converting to mp4 but it still gives me the same message.

**Comment by dularion** [comment]
Hm this has nothing to do with the file type, the error lies somewhere else. What is the entire stacktrace? Please dont paste it directly here but instead use http://pastebin.ca/

**Comment by Anderzenn** [comment]
Hey, sorry for the slow reply, been busy. I'm not entirely sure how to get the stacktrace, could you do a quick tutorial or something :P ?

**Comment by Anderzenn** [comment]
I got a work-around fix, I believe it's a bug with Windows.
Here's what I did.
![What I did](http://image.prntscr.com/image/cea1888c6ad64574ba9595ee8faf935a.png)

**Comment by Anderzenn** [comment]
It seems this was a mistake on my end. I had forgotten to create the directory it was supposed to save the uploaded files it.
