### ISSUE TITLE
Base URL validation seems to be broken for some cases

### ISSUE THREAD

**Issue by jguerinet** [dularion/streama#317]
I normally have my base URL set to my external IP address in order to access my local Streama instance remotely. But, ever since base URL validation was added, this URL is no longer validated. Any local IP address seems to work perfectly.

**Comment by dularion** [comment]
will attempt to fix this, please let me know if it worked for you

**Comment by jguerinet** [comment]
Confirmed it's fixed! Thank you!

**Comment by CodeFromCirc** [comment]
That should have fixed my issue at issue number #301, but my issue has been less clear. Sorry @dularion for the error in grammar.
