### ISSUE TITLE
Version-Number not displayed in .16

### ISSUE THREAD

**Issue by ManuGithubSteam** [dularion/streama#320]
Hi

the version field is cut of. So in streama you can not see the version anymore.

![screenshot_20170303_112958](https://cloud.githubusercontent.com/assets/3456994/23547772/c37e8082-0004-11e7-8f40-bbf3e8d809e3.png)

Thanks

**Comment by diwalker** [comment]
I enjoyed that, just the logo,if she took the v would look even better

**Comment by mazzucato** [comment]
i liked it too, the version number was removed since .13

**Comment by dularion** [comment]
Actually, its a mistake in the code, but I can make it optional through settings :) but first, i gotta fix the bug that causes this ;)

**Comment by diwalker** [comment]
I liked it :) something cool would also change the Logo and Header, without recompiling the .war directly from the settings for who is Admin
