### ISSUE TITLE
dropdown menu

### ISSUE THREAD

**Issue by mazzucato** [dularion/streama#322]
profile settings language dropdown menu white on google chrome

**Comment by Anderzenn** [comment]
Just adding a screenshot to help clarify the issue.

![image](https://cloud.githubusercontent.com/assets/12025450/23585169/fbc68e76-0176-11e7-857f-78cd474a9f9d.png)

**Comment by dularion** [comment]
👍 
will fix in next release

**Comment by dularion** [comment]
There is a pre-release, if you want to test it

**Comment by mazzucato** [comment]
sure
