### ISSUE TITLE
after login bug

### ISSUE THREAD

**Issue by mazzucato** [dularion/streama#324]
if you change the logo, after login you're redirected to the logo image instead of the dashboard

**Comment by mazzucato** [comment]
still going to the logo directory

**Comment by dularion** [comment]
I think maybe because you had the broken .war in between, your uploaded logo is missing the IsPublic flag. Could you check in the database, in the table "file" if the requested image has the boolean isPublic set to true? alternatively, reupload the image.

**Comment by mazzucato** [comment]
`DEBUG grails.app.services.streama.UploadService - [isPublic:true, file:org.springframework.web.multipart.support.StandardMultipartHttpServletRequest$StandardMultipartFile@7c014925, controller:file, format:json, action:upload]`

so when you login, the login button redirect you to the logo directory like "localhost:8080//file/serve/4225.png"

**Comment by mazzucato** [comment]
sorry im oppening lots of issues... i really like your project so im testing it in a hard way

**Comment by dularion** [comment]
is there any way I could look at the project? if so, PM me on gitter

**Comment by mazzucato** [comment]
sure

**Comment by dularion** [comment]
So this seems to have to do with the trailing "/" at the end of the base url. I will look into it and publish a fix asap

**Comment by dularion** [comment]
There is a pre-release, if you want to test it
