### ISSUE TITLE
Video not showing

### ISSUE THREAD

**Issue by Anderzenn** [dularion/streama#325]
So I (finally) managed to get a file uploaded and able to "play" I can hear the sound but I can't see the video, the video is of mp4 but all I hear is the sound, I can't see the video. I checked the file in the file directory and that one is working fine.

My CMD isn't giving me any errors aswell.

![image](https://cloud.githubusercontent.com/assets/12025450/23577904/3cd0d608-00cb-11e7-9c44-c3b15e69c06f.png)

**Comment by dularion** [comment]
Can you do the typical html5-video check? [see this section in the FAQs](https://github.com/dularion/streama/wiki/Getting-started-with-v1#11-video-playback)

**Comment by Anderzenn** [comment]
I feel so dumb now!
No it doesn't, I thought html5 could read all mp4 formats. Guess not!

**Comment by Anderzenn** [comment]
I converted the file to another mp4 and it's working flawlessly now :)

**Comment by Anderzenn** [comment]
This was a mistake on my end, apologies.
