### ISSUE TITLE
Redirection after completing signup

### ISSUE THREAD

**Issue by z3ntu** [dularion/streama#33]
When you complete the signup process http://10.0.0.1:8080/streama/invite?uuid=SOME_UUID , then they get redirected to http://localhost/<andtheURL> , which should be the Base-URL from the settings.

**Comment by dularion** [comment]
Thanks! will look into it

**Comment by dularion** [comment]
I cannot reproduce this unfortunately. Maybe it was fixed when I removed the baseURLs from the config file. You you check again?

**Comment by z3ntu** [comment]
Unfortunately (or for me fortunate) I am for one week in Cologne (Gamescom), maybe I can get it to work on my laptop and try to reproduce :)

**Comment by dularion** [comment]
nah, no hurry :) have fun at gamescom!

**Comment by z3ntu** [comment]
Thanks :+1:

**Comment by noahp78** [comment]
Can confirm this, Have example.com:8080 as streama base. 
login works, but video playback doesn't. 
(it tries to load from localhost instead of local path).

**Comment by dularion** [comment]
could you copy-paste the entire path where it looks for the video file? I have an installation where it runs under http://46.101.209.74:8080 (this is the demo page I am working on) and files are served from this url: 
http://46.101.209.74:8080/file/serve/1e809df97f60abbeaf3dc459e9431d6f0fe2015594585564a1ad6a2947aceb09.mp4

**Comment by noahp78** [comment]
Nevermind, I'm stupid :-1:

**Comment by dularion** [comment]
haha :D I am sure you are not! :) And shall no more bugs befall you!

**Comment by noahp78** [comment]
Just hit this error. removing the backslash doesn't work (same result as this) when trying to load a video:

http://example.com:8080//file/serve/0a3cca556bc225a34c33270435c2c9e53ba198559e3e512cf902962a2d726ef1.mp4 404 (Not Found)

**Comment by dularion** [comment]
so in your settings it says "http://example.com:8080", not "http://example.com:8080/"? could you go to the settings page and do a hard f5 to see if that is really the case? It might not have saved correctly

**Comment by noahp78** [comment]
It didn't save correctly.

Awesome work btw :+1:

**Comment by dularion** [comment]
Thanks! Im looking to implement a lot more features in the future :)

**Comment by dularion** [comment]
Please reopen if problem comes up again.
