### ISSUE TITLE
Mistake in the English translation

### ISSUE THREAD

**Issue by Anderzenn** [dularion/streama#331]
It seems there is a mistake in the english translation under "FILE_MISSING:"
It says "There is a problem with this content. It seems you removed the associated video file from it.. **Share this with your friends to have a synchronized watching experience with them!**"

**Comment by dularion** [comment]
Thanks!

**Comment by dularion** [comment]
There is a pre-release, if you want to test it

**Comment by Anderzenn** [comment]
I believe it should be fixed now :)
