### ISSUE TITLE
v.0.18 Adding of local files not possible anymore/ Settings changes not recognised

### ISSUE THREAD

**Issue by ManuGithubSteam** [dularion/streama#333]
Hi Dularion,

In the new 18 version it is not possible to add local files anymore. The browser does not show anymore.

![screenshot_20170305_160305](https://cloud.githubusercontent.com/assets/3456994/23588474/28e066ce-01be-11e7-9b44-866a776b1a08.png)

The path is correct and does exist. However i can not change the directory to another. Streama does not recognise when i type in a new path in settings. So it does not allow me to save the new settings.

Thanks

**Comment by ManuGithubSteam** [comment]
Edit: 
Here is the console output:

root@diynas:/nas/server/streama# chmod +x streama-1.0.18.war 
root@diynas:/nas/server/streama# htop
root@diynas:/nas/server/streama# nano /usr/local/bin/start_streama 
root@diynas:/nas/server/streama# start_streama 
/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java: no process found
root@diynas:/nas/server/streama# INFO streama.Application - Starting Application on diynas with PID 5092 (started by root in /nas/server/streama)
DEBUG streama.Application - Running with Spring Boot v1.3.8.RELEASE, Spring v4.2.8.RELEASE
INFO streama.Application - The following profiles are active: production
ERROR grails.boot.config.tools.ClassPathScanner - The application defines a Groovy source using the default package. Please move all Groovy sources into a package.

Configuring Spring Security Core ...
... finished configuring Spring Security Core


root@diynas:/nas/server/streama# WARN grails.app.services.streama.TheMovieDbService - could not load genres this time, Server returned HTTP response code: 429 for URL: https://api.themoviedb.org/3/genre/tv/list?api_key=262be6474e91bbc32388e1ba5e7d9b2d
WARN grails.app.services.streama.TheMovieDbService - could not load fullMeta for TV SHOW this time, Server returned HTTP response code: 429 for URL: https://api.themoviedb.org/3/tv/6909?api_key=262be6474e91bbc32388e1ba5e7d9b2d
WARN grails.app.services.streama.TheMovieDbService - could not load fullMeta for TV SHOW this time, Server returned HTTP response code: 429 for URL: https://api.themoviedb.org/3/tv/6909?api_key=262be6474e91bbc32388e1ba5e7d9b2d
INFO streama.Application - Started Application in 35.67 seconds (JVM running for 37.887)
Grails application running at http://localhost:86 in environment: production

**Comment by dularion** [comment]
The path validation is fixed. For the other error, can you please send me the network request result when opening that modal?

**Comment by ManuGithubSteam** [comment]
Hmm it works this time... Don't know what was wrong...

![screenshot_20170307_164139](https://cloud.githubusercontent.com/assets/3456994/23664158/13795460-0355-11e7-9e05-2d4014cf0602.png)

**Comment by dularion** [comment]
glad it worked now
