### ISSUE TITLE
Does not load CSS when hosted 

### ISSUE THREAD

**Issue by robsonolivesa** [dularion/streama#335]
After generating the .war file and doing the deploy, it does not load the css and javascript files.  Has anyone had this problem yet?

**Comment by robsonolivesa** [comment]
The problem is that the "assets" folder is not included in the .war file.

**Comment by dularion** [comment]
are you building it yourself?

**Comment by robsonolivesa** [comment]
Yes, im doing a test with genre segregation by user.

**Comment by dularion** [comment]
In order to build a proper war file you need to run ‘gradle assemble‘ or if you don't have it installed then `./gradlew assemble`

**Comment by robsonolivesa** [comment]
Thanks! You solve my problem.
