### ISSUE TITLE
Blank screen hosted aplication

### ISSUE THREAD

**Issue by robsonolivesa** [dularion/streama#338]
Has anyone hosted the application? I hired a VPS but after the login screen the system shows a blank page.

Characteristics:
- Ubuntu 16.04
- JDK 1.8.120
- Grails 3.1.14

Running with "./streama.war"

**Comment by robsonolivesa** [comment]
I have no messages at the console application.

**Comment by bayuanderas** [comment]
Who are you?

Pada tanggal 10 Mar 2017 21.59, "robsonolivesa" <notifications@github.com>
menulis:

**Comment by dularion** [comment]
Which version of streama are you trying to run? Or: Did you compile it yourself? In which case, did you use gradle assemble? 
When you say: no console output, does the literally mean 0 output? That seems highly unlikely

**Comment by robsonolivesa** [comment]
I am running version 1.0.19 but I have changed the application.yml file with the host database information (password only). I generated the .war file through the "gredlew assemble" command.
On the console, no message appears after "Grails application running at http://localhost:8080 in environment: production", that is, no error is printed.

**Comment by robsonolivesa** [comment]
Work's fine with H2 database, with mysql no.

**Comment by robsonolivesa** [comment]
The problem is in the .war file. Running through intellijidea works perfectly, after deploy the system gets stopped on a blank page in the url /login/auth.

**Comment by robsonolivesa** [comment]
The problem is in file generation. WAR, even making the original source code of the application (1.0.18) and deploying it, the system continues with the same error. Assets are not in the app after deploy. But the Intellij Idea works perfectly.

**Comment by robsonolivesa** [comment]
I will open a new  issue .
