### ISSUE TITLE
Streama Demo Page

### ISSUE THREAD

**Issue by dularion** [dularion/streama#34]
Am I correct in assuming that there is general interest for this? I would then populate everything with trailers.

**Comment by fisle** [comment]
Demo is always a good idea, IMO.

**Comment by TuckerWhitehouse** [comment]
:+1:

**Comment by z3ntu** [comment]
:+1:

**Comment by sdiwo** [comment]
+1

**Comment by dascandy** [comment]
Also add the Blender Foundation movies, which are (I think) free to host for this purpose. I think there are a few in 4k even - if you can spare the bandwidth. Look for "Big Buck Bunny" or "Sintel" among others.

**Comment by dularion** [comment]
Good idea! Just added trailers now, but some of them are such poor quality .. Will look into those!

**Comment by dularion** [comment]
Ok, I created it now :) http://dularion.github.io/streama/
I also added it to the readme

**Comment by stramel** [comment]
:+1: @dularion great work!

**Comment by z3ntu** [comment]
Close?
