### ISSUE TITLE
Error when Logging in as anyone other than admin

### ISSUE THREAD

**Issue by mongomay69** [dularion/streama#343]
currently running version 1.0.19, has the same problem on 1.0.18

You do not have the rights to carry out this action popup when you log in

Console: Failed to load resource: http://exampledomain.com/settings.json the server responded with a status of 403 ()

![mongo](https://cloud.githubusercontent.com/assets/25631290/24012635/0edf6a5a-0a55-11e7-8620-2f8155e42804.png)
![desctop screenshot](https://cloud.githubusercontent.com/assets/25631290/24012857/eaa61ee4-0a55-11e7-9741-ac96f0b839df.png)

**Comment by dularion** [comment]
Oh this is pretty critical. Thank you
