### ISSUE TITLE
file browser should remember the last folder

### ISSUE THREAD

**Issue by mongomay69** [dularion/streama#347]

**Comment by dularion** [comment]
Hm, the question would then be: How does the file-browser behave? I guess it has a "fake" root directory, populated by all the folders that you added or something.. 
This does not seem like a super easy feature, but definitely one for the roadmap. Until then, why not use linux linking to access files from other locations?

**Comment by ManuGithubSteam** [comment]
Hi dularion,

It would help tremendously if the streama file browser would remember the lase folder a video was added from. This would speed up adding videos a great deal as for now only one master location can be added.

Thanks

**Comment by dularion** [comment]
I agree with that. This will be added to the version shortly, as it was pointed out before

**Comment by dularion** [comment]
Added in the v1.0.20 prerelease
