### ISSUE TITLE
1.0.20 Doesn't allow recursive file searching

### ISSUE THREAD

**Issue by mongomay69** [dularion/streama#348]
![pic1](https://cloud.githubusercontent.com/assets/25631290/24327046/f48e6944-1193-11e7-94ae-bfcb0502dcec.png)
![pic2](https://cloud.githubusercontent.com/assets/25631290/24327047/f61c4506-1193-11e7-8326-9210586baa23.png)
![pic4](https://cloud.githubusercontent.com/assets/25631290/24327050/f9bf88c6-1193-11e7-8f07-f91ae4fcd913.png)
![pic3](https://cloud.githubusercontent.com/assets/25631290/24327048/f75997c0-1193-11e7-948f-781217df91f0.png)

i know it's pre release, just wanted to let you know

**Comment by dularion** [comment]
Hi! Thanks for reporting this. I am not sure I am following what you mean. What do you mean by recursive? the search-bar in the top only searched in the current directory.

**Comment by mongomay69** [comment]
usually i just have a folder in my D drive that holds my movies, each of those movies is it it's own folder so i can easily separate them, in this version it didn't detect the movie file unless i gave it the specific local video file path where as before i could just define my general folder and search through to find the movie folder i wanted to add

**Comment by dularion** [comment]
Are you talking about the search input above? Do you want to be able to type something in there and it searches through the fs starting at the folder defined in the settings? This would be new functionality, but yeah, I can see the value 
.. I'll see what I can do

**Comment by mongomay69** [comment]
![pic1](https://cloud.githubusercontent.com/assets/25631290/24335031/d23bc25a-1243-11e7-9bbd-499f87254fbe.png)
i have each of them in their own folder but when i click on their folder in this newest version the movie doesn't pop up

**Comment by mongomay69** [comment]
and i meant recursive as in i defined the general popcorn time folder but it doesn't allow me to search in the folders inside that folder

**Comment by mongomay69** [comment]
if you want to check it out i can give you access

**Comment by dularion** [comment]
No you are absolutely rgiht! sorry for the confusion. Fixed in v1.0.21 now

**Comment by mongomay69** [comment]
thanks
