### ISSUE TITLE
Error playing file

### ISSUE THREAD

**Issue by Duckbuster** [dularion/streama#349]
> ERROR org.grails.web.errors.GrailsExceptionResolver - MissingPropertyException occurred when processing request: [GET] /file/serve/3.webm
> No such property: fis for class: streama.FileService. Stacktrace follows:
> groovy.lang.MissingPropertyException: No such property: fis for class: streama.FileService
>         at streama.FileService.$tt__serveVideo(FileService.groovy:75)
>         at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:96)
>         at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
>         at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
>         at streama.FileController.serve(FileController.groovy:153)
>         at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:222)
>         at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:187)
>         at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
>         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961)
>         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895)
>         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
>         at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)
>         at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
>         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:316)
>         at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
>         at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
>         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
>         at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
>         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
>         at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:53)
>         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
>         at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:157)
>         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
>         at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
>         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
>         at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205)
>         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
>         at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:62)
>         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
>         at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91)
>         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
>         at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
>         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
>         at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213)
>         at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
>         at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
>         at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)
>

**Comment by Duckbuster** [comment]
Using v1.0.20.
Tried to play an uploaded webm and a local file converted to mp4 via included ffpmeg command.

**Comment by Duckbuster** [comment]
Just tried version 1.0.19 and it works.

**Comment by dularion** [comment]
Can you check in the v1.0.21 prerelease?

**Comment by Duckbuster** [comment]
I think I build it, but I can't find the .war file. Any help? I have never done this gradle stuff.

**Comment by dularion** [comment]
check the releases page https://github.com/dularion/streama/releases

**Comment by dularion** [comment]
Please reopen if problem persists
