### ISSUE TITLE
IRC Channel?

### ISSUE THREAD

**Issue by richraid21** [dularion/streama#35]
Is there currently any way to collaborate/talk about streama in real time? I really like the potential of this project..

**Comment by thomasleveil** [comment]
https://gitter.im/ ?

**Comment by dularion** [comment]
:+1: for gitter.im! did not know about this

**Comment by richraid21** [comment]
Sounds good to me

**Comment by dularion** [comment]
I added a gitter chatroom link to the readme now (under Roadmap). Not sure if anyone can join if I have to invite people?

**Comment by thomasleveil** [comment]
anyone can join, no invite required

**Comment by z3ntu** [comment]
Close?

**Comment by dularion** [comment]
I'd say so. OP?
