### ISSUE TITLE
Can't browse subfolder of local file path.

### ISSUE THREAD

**Issue by Duckbuster** [dularion/streama#350]
When I try to browse to a subfolder of my local file path, It gives this error:

> The video file must be contained in the Local Video Files setting.

Using Version 1.0.21

**Comment by mongomay69** [comment]
if you grabbed the release early in the day she already put in a fix for it, try downloading it again

**Comment by dularion** [comment]
as @mongomay69 suggests, please try v1.0.21 again. Ive made some last minute adjustments to that release, as can be seen in the changelog.
