### ISSUE TITLE
ERR_CONTENT_LENGTH_MISMATCH 

### ISSUE THREAD

**Issue by jguerinet** [dularion/streama#352]
Hi (again), 

Every time I watch a video I get the error above, and one of two things happen: 
1) The video just blacks out and I have to refresh the page to restart it at which point it goes back to normal
2) The video freezes for about half a second but the audio continues to go so there is a lag between the 2 unless I refresh the page, at which point it goes back to normal
This happens on average about 4 times for a 20 min standard resolution video. 

I checked the console and I get ERR_CONTENT_LENGTH_MISMATCH about 4-5 times before one of these 2 things happen, so I am assuming it's because Chrome doesn't know how to handle the extra bytes it gets and decides to start a mutiny against me. 

Has this happened to you before? I know absolutely nothing about video and the html5 player, but after Googling the issue a question on SO seemed to have the same problem as me: http://stackoverflow.com/questions/22989556/html5-video-err-content-length-mismatch 

Please let me know if I can help with anything at all, like I said this is out of my area of expertise but I'll try my best! And thanks again for such a wonderful open source project.

Thanks, 
Julien

**Comment by dularion** [comment]
This seems a very special problem. Here are a few things you can do to help: 
Check to make sure to provide all the info listed here: 
https://github.com/dularion/streama/wiki/How-to-report-a-bug

Also, does the error occur with all kinds of videos or just one / a few? 

And lastly, can I have either the file you are experiencing issues with or access to your system (login to streama and ssh). for credentials, you can write on gitter.

**Comment by jguerinet** [comment]
Hi, 

Sorry for the delay, I was trying different things on my end to try to fix it. 
Most of my videos are either avi which won't play in the player, or mkv, which will play but very often start skipping 2-3 minutes in. So I thought I would go through the (painful) process of converting them to mp4, which up until now didn't show any problems with the player (I had some videos that were mp4 by default and they seemed to work fine). 
I converted them using Handbrake, I pretty much used the standard settings. I've tried checking the "Web Optimized" box as well on Handbrake. It seems like every video coming out of Handbrake is experiencing this problem (I haven't tried all of them since there are hundreds of them, but I have tried maybe 5-10 of them and they consistently have the issue). 
Here's all of the extra info: 
system: Windows 10 (Version 1607)
browser: Chrome (Version 56.0.2924.87)
os: Windows
other systems: Only tried on Chrome
streama: v1.0.21
using release: yes

I've sent you some example files on Gitter.

Thanks!

**Comment by jguerinet** [comment]
I'm going to close this as this doesn't seem to be happening anymore. I believe that it was a problem with Chrome and not Streama. For future reference, I'm currently on v59.0.3071.115 of Chrome and haven't seen any playback problems (only tried mp4, have not verified with mkv). 

Thanks
