### ISSUE TITLE
Disable Login

### ISSUE THREAD

**Issue by Qasimmodo** [dularion/streama#353]
Hey, is there a way you can completely disable the login system?

**Comment by dularion** [comment]
For what purpose exactly?

**Comment by jwcrawley** [comment]
I second this idea. 

I have this behind our network, and I would like this service available for anyone on my network. It's one less login/password to deal with. And frankly, Streama just works. 

It would be a great boon to be able to turn off the authentication layer, and be a nice happy HTML5 player for anyone on our network.

**Comment by jwcrawley** [comment]
Greetings, Dularion!

Do you have any further progress on making a flag to ignore login? (Or perhaps a autologin=[user] )

I've tried digging in this codebase, but I've no experience here, aside running it. But I have over 1.4TB of data being served through Streama :)

**Comment by diyarit** [comment]
I wan't the same thing when you open the site shows you the content without having to login

**Comment by Jeronimo95** [comment]
Added in 44a737721d80fba8a7627b5b60a2a757a56e9b73
