### ISSUE TITLE
Changing password

### ISSUE THREAD

**Issue by z3ntu** [dularion/streama#37]
another suggestion

**Comment by dularion** [comment]
I like it, though I am wondering: The typical approach is to send an email to the user and let him fill out a new password through a unique link. How could we recreate this for those that don't want to use a mail server?

**Comment by z3ntu** [comment]
just a page with 

    Old password: 
    New password:
    Confirm password:

?

**Comment by dularion** [comment]
Yea, you are right. I was only thinking about the password lost functionality. But of course, a simple change could be like you describe about. Password lost IS more complicated though..

**Comment by dularion** [comment]
A complete profile Update & Password change is now included as of commit https://github.com/dularion/streama/commit/6b0cc6c40247d2c923c545b3608c91a7fe91a7e9

Added bonus: Users can now choose favoriteGenres. This paves the way for adding a category in the dashboard for "Things you might like to watch"

**Comment by z3ntu** [comment]
Nice
