### ISSUE TITLE
ERROR org.springframework.boot.SpringApplication - Application startup failed

### ISSUE THREAD

**Issue by jmourace** [dularion/streama#370]
Hi, I am trying to compile the streama and I get the error 
ERROR org.springframework.boot.SpringApplication - Application startup failed
Can you help me solve this?
thank's

**Comment by jmourace** [comment]
Solve. Thanks

**Comment by Varunperla** [comment]
How did you solve this? Please help me! I'm stuck at the same place @jmourace
