### ISSUE TITLE
Base URL is invalidating my .tech domain

### ISSUE THREAD

**Issue by rayonaboat** [dularion/streama#382]
I've used Streama since 1.0.9 and had my Base Url set. Now I'm on 1.1 and I cannot enter any .tech domain. Using older TLDs, like .com or .org, is working. A workaround I've found is downgrading to 1.0.16, setting the domain, and upgrading back to latest version.

**Comment by dularion** [comment]
Ugh.. WIll look into it. Maybe Ill remove the validation again -.-

**Comment by kevincox** [comment]
Yeah, validating URLs is probably much more work then it is worth :) If you want some method to check it it might be best to just generate a link that the user can click on to make sure it goes to the right place.

**Comment by Jeronimo95** [comment]
Fixed in Jeronimo95/streama@14bb904321d3db2b37b5abbc9a44d2a9c5b75543.
