### ISSUE TITLE
local videos issue

### ISSUE THREAD

**Issue by Le0nardZelig** [dularion/streama#384]
Hi!
Whenever I try to play a local video I get this error message: 
"You video get's included using the wrong Base Path, but you are browsing the page via "http://xx.xx.xx.xx:8080" (where xx is my internal ip). Make sure you set the correct Base Path in the settings and that you are using it to browse the application."

I really can't figure it out: filepath is right, so what is this about?

Thanks!

**Comment by Shrinks99** [comment]
You need to set the base url to your internal ip in the Streama settings.  The base url is the url that you will use to access streama through, in your case it will most likely be 192.168.x.x .

**Comment by vinigfer** [comment]
Worked for me! I believe this issue can be closed.

**Comment by Le0nardZelig** [comment]
Solved! Thanks dude :)
