### ISSUE TITLE
Issue with adding/editing new tv shows (manually)

### ISSUE THREAD

**Issue by redraskal** [dularion/streama#386]
I am really confused right now. For whatever reason, when I try editing a show (this only happens with 2+ shows in the table), the show name, description, and images are copied over to the other tv shows that already exist. This only occurs with tv shows, not movies and other videos on the latest release.
**Edit:** This issue only occurs when adding/editing a manually added tv show.

**Comment by dularion** [comment]
Is there any way you can record this behaviour as a gif or an mp4?

**Comment by dthims** [comment]
this happens with me. mine is only one - anytime i try to add a second tv show, it overwrites the first show -  issue #399. on movies it works fine. just tv shows has this problem
