### ISSUE TITLE
Do u have plans for connect with google account?

### ISSUE THREAD

**Issue by astlanox** [dularion/streama#391]
Hi dularion.

Thank you for providing awesome software.

I really hope to add my video uploaded to Google Drive or Google Photos to my streama.
I tried Extra URL function, but sadly google drive is not supported.
Do u have a plan for connect with Google account?
Is it means MEDIA CRAWLER?

Thanks.

P.S.
I posted duplicate postings.
Im sorry.

**Comment by dularion** [comment]
Please look at this issue: https://github.com/dularion/streama/issues/60
