### ISSUE TITLE
Rename, Remove or Create new category

### ISSUE THREAD

**Issue by adelmosilva** [dularion/streama#394]
Good Morning.
First of all, congratulations for the excellent project.
Second, I would like to remove existing categories or rename them, or add new categories to Streama. Would it be possible?
In time, where can I get new templates?

Once again, congratulations on the incredible project.

**Comment by vaguiners** [comment]
great

**Comment by vaguiners** [comment]
Hang on. Are you talking about the genres?

It is easy to edit, add and remove genres on DB. The problem is that for some reason it is impossible to add or remove genres of shows on DB.

http://i.imgur.com/QZtKe8F.png

**Comment by ManuGithubSteam** [comment]
@vaguiners  
Good to know! Thanks man!
