### ISSUE TITLE
ERROR grails.boot.config.tools.ClassPathScanner 

### ISSUE THREAD

**Issue by dthims** [dularion/streama#395]
using debian stretch. tried both versions of jave and that message pop-up. ERROR grails.boot.config.tools.ClassPathScanner - The application defines a Groovy source using the default package. Please move all Groovy sources into a package. found this url, but it didn't say what the fix was - https://github.com/dularion/streama/issues/259. also, when using ssl and i try to launch or preview a video, get an error about the base url being wrong. http works fine though. like your product, tia

**Comment by PiperMp3** [comment]
Seen it, I have it on every launch of Streama as the service.

No idea what it is, no idea how to fix it - but to me it aint causing issues.

Would be cool with a reason and fix for it though. Clogs up my logs.
