### ISSUE TITLE
MKV files with no sound

### ISSUE THREAD

**Issue by michelpf** [dularion/streama#397]
I tried two video files and both plays OK the video, but no sound. MP3 files were OK with video and sound, in my environment.

**Comment by dularion** [comment]
Hi,
This is a common problem. With HTML5 you need to watch both the video and the audio Codec. H264 and AAC work reliably. You could use something like handbrake to convert them.

**Comment by ManuGithubSteam** [comment]
I seen this also before its the wrong codec in the file. Please re encode your files and close the issue here :-)

**Comment by michelpf** [comment]
I really enjoy it, but with Plex I don't have issues like that for my files... :(
Thanks for fast response, @dularion and congratulations for your remarkable project.

Following next updates. :)
