### ISSUE TITLE
tv shows

### ISSUE THREAD

**Issue by dthims** [dularion/streama#399]
when you create the first show, it goes in fine. but when you add a second show, it overwrites the first show. has anyone had this problem? tiz

**Comment by PiperMp3** [comment]
Not seen this issue before - Either permission issue, or conflict in Streama's file I'd imagine.
Getting any errors? Any logfiles? What OS you got Streama on?
I'd recommend a reinstall?
Start from scratch. Ensure your PC - whatever you have Streama running on is updated, fully healthy and otherwise is good.

**Comment by dthims** [comment]
ERROR grails.boot.config.tools.ClassPathScanner - The application defines a Groovy source using the default package. Please move all Groovy sources into a package 

this message pops-up. don't know if its relevant. did it on a different machine and it did the same thing. can always create the first one, but it won't create a second one. it always overwrites

**Comment by dularion** [comment]
Can you attach a video of this behavior? 
Can you screenshot your database settings for the TV show table? Is the id set to Auto-increment there? Are you using h2 or mysql or another? The error on startup is irrelevant

**Comment by dthims** [comment]
[streama.zip](https://github.com/dularion/streama/files/1158855/streama.zip)

not using mysql. its a real basic system. did 644 to the upload directory. besides that, everything else was untouched. tia

**Comment by dularion** [comment]
Oh ok! this happens WITHOUT a tmdb key? then it is definitely narrowed down!

**Comment by Jeronimo95** [comment]
Seems to have been caused because `TvShow.findByApiId(null)` would return the first item in the DB, causing subsequent `save()` calls to overwrite the first. Checking for `data.apiId != null` before calling  `findByApiId` in `TvShowController` prevents this.

Fixed in PR shown above.
