### ISSUE TITLE
Found binding in ... ERROR

### ISSUE THREAD

**Issue by z3ntu** [dularion/streama#40]
| Running Grails application
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
| Error SLF4J: Class path contains multiple SLF4J bindings.
| Error SLF4J: Found binding in [jar:file:/home/luca/.grails/wrapper/2.4.4/grails-2.4.4/dist/grails-plugin-log4j-2.4.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
| Error SLF4J: Found binding in [jar:file:/home/luca/Programs/streama/target/work/tomcat/webapps/streama/WEB-INF/lib/grails-plugin-log4j-2.4.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
| Error SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
| Error SLF4J: Actual binding is of type [org.slf4j.impl.GrailsSlf4jLoggerFactory]
Configuring Spring Security Core ...
... finished configuring Spring Security Core
| Server running. Browse to http://localhost:8080/streama
| Server running. Browse to http://localhost:8080/streama

**Comment by xcy7e** [comment]
Me too having this issue. Running on Windows 10 using XAMPP and JDK7

**Comment by gkiko** [comment]
Same issue on OSX
```
| Grails Version: 3.0.9
| Groovy Version: 2.4.5
| JVM Version: 1.7.0_55
```

**Comment by dularion** [comment]
Reopen if the problem persists.
