### ISSUE TITLE
Database in use under Cluster

### ISSUE THREAD

**Issue by PiperMp3** [dularion/streama#401]
Hi!

Just an heads-up.
Got Streama running on "node01" with replication of files over to node02.
Node01 delivers the actual service just fine, however when starting Streama again on node02 there is an error as long as Node01 service still runs.

"ERROR org.apache.tomcat.jdbc.pool.ConnectionPool - unable to create initial connections of pool"
"org.h2.jdbc.JdbcSQLException: Database may be already in use: null. Possible solutions: (duuh) Close all other connection(s); user the server mode [90020-192]"
Now, I am not fully 100% if it's due to the port 8080 being the same on both Nodes,  or if its due to the file being pulled and written to at the same time.

Will be changing the port on one of them to use another - will get back to you with results.

**Comment by PiperMp3** [comment]
Right, so it's most likely the Port conflict.
Now, my sample_application.yml file does not actually do anything. If I change any values in it - Say the port, save, restart Streama, the effects does not take place.

Starts over and over on default port 8080 - regardless of what the .yml file say.

Any suggestions?

**Comment by PiperMp3** [comment]
And yes, the .yml file is right next to the streama.war file

**Comment by dularion** [comment]
You need to rename it to application.yml

**Comment by dularion** [comment]
However, the error indicates that the problem lies elsewhere, namely that the database is already in use.

**Comment by PiperMp3** [comment]
For sure, in use.
As the files are synced across two nodes, both nodes would be "Using" the same files.

Tried to change the port anyway - Same error, so yes, whenever node01 is using the db, node02 can't.
Anyway we can make it multi-use? Allow it to be read and written to at the same time?

**Comment by PiperMp3** [comment]
Nvm, I answered my own question - MySQL solved that issue.
