### ISSUE TITLE
Make file chooser remember source

### ISSUE THREAD

**Issue by ManuGithubSteam** [dularion/streama#403]
Hi Dulorion,

Now the add local file remember location feature helps a great deal  with adding tv shows as i start over in the same folder and just have to click the episode. 

But it would help  tremendously if the file chooser would remember that the last i clicked was "Local File" and not jump to upload all the times :-) 

Also an auto close after adding the episode would be handy (configurable tick box in the file chooser) :-)

This should be easy to implement and would help a great deal :-)

What do you think ?

**Comment by dularion** [comment]
These are great features! Will implement asap

**Comment by dularion** [comment]
![image](https://user-images.githubusercontent.com/936076/29479051-60419842-8470-11e7-8a8d-9671eff5b5f7.png)
