### ISSUE TITLE
Modification to systemd service

### ISSUE THREAD

**Issue by ares-fortress** [dularion/streama#407]
I have followed a tutorial on how to install streama on CentOS 7 (https://www.howtoforge.com/tutorial/how-to-install-streama-on-centos-7/). I would like to share my modification on creating streama systemd service on ubuntu 16.04.

in the tutorial
[Unit]
Description=Streama Server
After=syslog.target
After=network.target

[Service]
User=root
Type=simple
ExecStart=/bin/java -jar /opt/streama/streama.war
Restart=always
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=Streama

[Install]
WantedBy=multi-user.target

my java binary is installed at /usr/bin/java and streama is located at /home/streama/

so my setup is 

[Unit]
Description=Streama Server
After=syslog.target
After=network.target

[Service]
User=root
Type=simple
WorkingDirectory=/home/streama/
ExecStart=/usr/bin/java -jar /home/streama/streama.war
TimeoutStartSec=120
Restart=on-failure
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=Streama

[Install]
WantedBy=multi-user.target

with 3 additional modifications.
1) Working directory -> WorkingDirectory=/home/streama/
2) java location -> ExecStart=/usr/bin/java -jar /home/streama/streama.war
3) systemd will reload service after 120 seconds after failure to start -> TimeoutStartSec=120

hope this will help somebody.

**Comment by dularion** [comment]
Oh this is great! Can you maybe add it as a wiki page? that way its more searchable

**Comment by ares-fortress** [comment]
will do
