### ISSUE TITLE
Won't launch

### ISSUE THREAD

**Issue by macmeister1967** [dularion/streama#413]
Exception in thread "main" java.lang.UnsupportedClassVersionError: streama/Application : Unsupported major.minor version 52.0

macOS Sierra 10.12.6, letest Java RE 8 update 102 & 144 ?!

**Comment by Jeronimo95** [comment]
What's the output of `java -version` on your system?

**Comment by macmeister1967** [comment]
java -version
    java version "1.6.0_65"
    Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
    Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

This is my Legacy java install to get Adobe CS6 working...

I just installed 1.8.0_144, but have not restarted yet...

BRB

**Comment by Jeronimo95** [comment]
If java 6 is your default, you'll probably need to run it with `/path/to/java1.8/java -jar streama-[version].war` I'm not sure where java is installed on macOS, have a look in `/Library/Java/JavaVirtualMachines/` or `/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/`

**Comment by macmeister1967** [comment]
Many thanks, got it working but it does not playback HEVC x265 files, so I will have to stick with my current video player box. Many thanks for the prompt replies and accurate info.

**Comment by Jeronimo95** [comment]
Currently only formats that your browser supports work. Video transcoding/conversion is on the todo list.
