### ISSUE TITLE
http://dularion.github.io/streama Windows Intructions Are Not Clear

### ISSUE THREAD

**Issue by toast-gear** [dularion/streama#419]
I couldn't get streama running based on the instructions on https://dularion.github.io/streama/ for windows. The instructions here are much clearer https://github.com/dularion/streama/wiki/Getting-Started-(Windows)

Either the instructions for Windows on https://dularion.github.io/streama/ should be removed and direct the user to the wiki page or they should include the full command of 

java -jar streama-[version].war.

The former option makes the most sense to me so there's no duplication.

**Comment by Jeronimo95** [comment]
I've updated the page to link directly to the wiki for Windows,
