### ISSUE TITLE
Tor Implementation?

### ISSUE THREAD

**Issue by CKkio23** [dularion/streama#420]
Got it up and working but when i use Tor it cannot fetch the video since it uses Localhost and not onion address. Can you add Tor or a bypass for usage with Tor?

**Comment by Jeronimo95** [comment]
I'm confused as to what the issue is. Can you provide more details of the issue?

**Comment by CKkio23** [comment]
Sorry once you try to view on Tor it says i cannot view the video due to the base url being different. i need a work around or a way for this to work. Thanks.

**Comment by Jeronimo95** [comment]
In Settings set your Base URL to the .onion address you are accessing streama from.

**Comment by CKkio23** [comment]
That doesn't work at all. Since it uses localhost and not the onion address.

**Comment by Jeronimo95** [comment]
Alright, I don't think TOR will work with the current implementation then. The good news is that I'm going to be changing the Base URL system which will fix this and similar issues (#334).
