### ISSUE TITLE
Windows install directions need update for correct username

### ISSUE THREAD

**Issue by Syndaryl** [dularion/streama#427]
The windows install directions at https://github.com/dularion/streama/wiki/Getting-Started-(Windows) say

> head to http://localhost:8080/, sign in with this account: username & password: admin, and you're set for your free self-hosted Netflix!

But this is not the account. The linux instructions have:

> Step 4 - Login
> the first thing you will see when opening the URL is a login screen. Use username admin and password admin to log in.

And this combination works on a Windows server.

**Comment by Jeronimo95** [comment]
It's not wrong, `username & password: admin`; i.e. both `username` and `password` is `admin`. But I agree that it's not as clear as the linux instructions, so I've updated it to match.
