### ISSUE TITLE
can you add subtitle and multiple resolution for movie

### ISSUE THREAD

**Issue by muhanadali100** [dularion/streama#428]
first , thx for streama

1- Can you add subtitles upload for movies

2- Can you add multiple resolution like (720p,1080p) for same movie

**Comment by dularion** [comment]
Subtitles in movies already work, just upload:  

![image](https://user-images.githubusercontent.com/936076/30183805-08869628-941c-11e7-9a1b-11a2ad1bbaf8.png)

**Comment by dularion** [comment]
The other part is a duplicate of this: https://github.com/dularion/streama/issues/225
