### ISSUE TITLE
You do not have the rights to carry out this action.

### ISSUE THREAD

**Issue by z3ntu** [dularion/streama#43]
even though I have the roles "Admin, Content Manager" and I see "TV Shows" & "Movies"...
EDIT: i have already opened sooo many issues :laughing:

**Comment by dularion** [comment]
Where? What are you doing?

**Comment by z3ntu** [comment]
I am on the admin page and clicking "TV Shows" or "Movies" and I get the error message in the lower right corner

**Comment by dularion** [comment]
oh yea.. that is a springsecurity "feature", changing roles does not apply until you logout and back in.

**Comment by z3ntu** [comment]
and I relogged an I have two "Admin" buttons on the main page... lol

**Comment by dularion** [comment]
yep that is fixed, like 2 minutes ago

**Comment by z3ntu** [comment]
... :D

**Comment by dularion** [comment]
does it work if you log out and back in?

**Comment by z3ntu** [comment]
trying

**Comment by z3ntu** [comment]
double admin is gone

**Comment by z3ntu** [comment]
and i can acess tv shows & movies, either it works directly, or add a warn message!

**Comment by dularion** [comment]
yea.. good idea. or forcing a logout.

**Comment by z3ntu** [comment]
but please with a warning ... :)

**Comment by z3ntu** [comment]
okay anyways, good night! :D

**Comment by dularion** [comment]
fixed with https://github.com/dularion/streama/commit/8893cba44ce455c0027030595d7d7b322243799b

**Comment by z3ntu** [comment]
Fixed in a README.MD commit? Lol

**Comment by dularion** [comment]
haha oops 
https://github.com/dularion/streama/commit/3de424b1c2910c1eb04a3c4d8b578630b572d4ba
