### ISSUE TITLE
How can I make it work automatically when running Ubuntu

### ISSUE THREAD

**Issue by muhanadali100** [dularion/streama#430]
How can I make it work automatically when running Ubuntu ?

**Comment by Jeronimo95** [comment]
Follow step 8-10: https://github.com/dularion/streama/wiki/Installing-as-a-service-from-Git-on-Ubuntu-16.04

Make sure you update the lines 

```
WorkingDirectory=/data/streama/
ExecStart=/data/streama/streama.war
```

to point to your streama install.

**Comment by muhanadali100** [comment]
it's not working with ubuntu 14.04

systemctl: command not found
