### ISSUE TITLE
How can I make it work automatically when running Ubuntu 14.04

### ISSUE THREAD

**Issue by muhanadali100** [dularion/streama#431]
How can I make it work automatically when running Ubuntu 14.04

systemctl: command not found

**Comment by Jeronimo95** [comment]
We don't currently have a instructions for 14.04 but you should just be able to create an Init script for streama. There are a lot of tutorials for this, one is below.

https://mobiarch.wordpress.com/2014/05/16/creating-an-init-script-in-ubuntu-14-04/
