### ISSUE TITLE
proplems

### ISSUE THREAD

**Issue by muhanadali100** [dularion/streama#432]
proplem 1 : Images do not appear

https://imgur.com/9JyscIp

proplem 2 : Why can not I upload a picture of the episode

https://imgur.com/cKu9pZ3

proplem 3 : You can add delete for TV shows and add the adjustment to the sequence of movies from the main settings and make the order automatically since the last movie was uploaded to the oldest film upload

https://imgur.com/Q1uvKei

**Comment by dularion** [comment]
1: fixed (v1.4.1 RC2)
2: fixed (v1.4.1 RC2)
3. I dont quite understand this problem. what does "You can add delete for TV shows" mean?
