### ISSUE TITLE
Live Videos - How can I share the code?

### ISSUE THREAD

**Issue by lstarkgv** [dularion/streama#434]
Hello,

I was able to integrate live streaming videos. How can I share the code? I'm new to GitHub.

regards

**Comment by Jeronimo95** [comment]
## Create a Fork

Click the "Fork" button at the top of the page. Once you've done that, you can use your favorite git client to clone your repo or use the command line:

```shell
# Clone your fork to your local machine
git clone https://github.com/com:USERNAME/streama.git
```

## Doing Your Work

### Create a Branch
Whenever you begin work on a new feature or bugfix, it's good to create a new branch. Not only is it proper git workflow, but it also keeps your changes organized and separated from the master branch.

To create a new branch and start working on it:

```shell
# Checkout the master branch - you want your new branch to come from master
git checkout master

# Create a new branch named newfeature (give your branch its own simple informative name)
git branch newfeature

# Switch to your new branch
git checkout newfeature
```

Now, make whatever changes you want to.

## Commit the changes

```shell
# Commit the changes
git commit -m "New Feature"
```

Push them to github

```shell
git push
```

## Submitting a Pull Request

Once you've committed and pushed all of your changes to GitHub, go to the page for your fork on GitHub, select your development branch, and click the pull request button. If you need to make any adjustments to your pull request, just push the updates to GitHub. Your pull request will automatically track the changes on your development branch and update.

**Comment by lstarkgv** [comment]
OK thank you very much...

I will do it !
