### ISSUE TITLE
Like "Flix" Local

### ISSUE THREAD

**Issue by mrangel-jr** [dularion/streama#437]
@dularion , Como eu poderia utilizar a ferramenta mas sem a integração com a base de dados do the moviedatabase ? Existe algum form para cadastro dos dados dos vídeos que irei realizar o upload ? Caso não tenha, alguma orientação de como alterar para eu atender minhas expectativas ? Valeu !

**Comment by dularion** [comment]
Hi, I will answer you in English as it is easier for me. Please use a tool like google translate if need be.   
Currently you can actually use streama without themoviedb integration. just leave the API key out and you should be good to go. Whenever you enter data for a movie or show it is saved in your local database and any movies you upload are stored on your own server. Note that themoviedb does not change that behaviour, all it does is allow for movie/tv data to be fetched remotely, facilitating the input of movies and shows greatly!

**Comment by mrangel-jr** [comment]
Thanks a lot @dularion! Another question please ... Can I create subcategories into Streama ? It's useful to me, i have many videos and it's more easy to classify.

**Comment by Jeronimo95** [comment]
Closing as not an issue & no response.
