### ISSUE TITLE
Latest Pre-release not loading

### ISSUE THREAD

**Issue by daVinciCEB** [dularion/streama#442]
Hi,
I followed the exact instructions as well as the video tutorial, but the application is simply not loading at all in my remote server.

After running `sudo java -jar streama-1.2.3_beta.war`, I see the following output:

```
INFO streama.Application - Starting Application on pisskid-streama with PID 16359 (started by root in /data/streama)
DEBUG streama.Application - Running with Spring Boot v1.3.8.RELEASE, Spring v4.2.8.RELEASE
INFO streama.Application - The following profiles are active: production
ERROR grails.boot.config.tools.ClassPathScanner - The application defines a Groovy source using the default package. Please move all Groovy sources into a package.

Configuring Spring Security Core ...
... finished configuring Spring Security Core

```

At this point nothing moves, and I've been waiting for over an hour and there still is nothing loading.

I'm wondering what specs are necessary for the application to run?

I'm running this on a simple DigitalOcean Ubuntu server, 1GB of RAM, 1 CPU, 30GB of data on disk.

**Comment by dularion** [comment]
oh unfortunately 1gb ram is not enough .. :( 
2gb at least afaik

**Comment by daVinciCEB** [comment]
Ah well, then in that case it makes sense to why it didn't work :)

I'll upgrade the server and see if it works then.

Can we add in to the Wiki/Readme some minimum machine requirements?

**Comment by Jeronimo95** [comment]
Created wiki page
