### ISSUE TITLE
Local Video Files needs write permissions

### ISSUE THREAD

**Issue by oliver-cfc** [dularion/streama#444]
When I add a dir to the 'Local Video Files' section in 'Settings' it tells me: _The directory could not be accessed by the application. Please make sure that the directory exists and that you set the correct permissions._

The app is running on an rpi3 with a MySQL backend as 'streama'
```
streama   1180   984  0 23:02 pts/1    00:00:00 /bin/bash ./streama-1.1.war                                                                                                                   
streama   1191  1180 30 23:02 pts/1    00:06:48 /usr/bin/java -Dsun.misc.URLClassPath.disableJarChecking=true -jar /home/streama/data/streama/streama-1.1.war

```
And, as streama, I can view the files/dirs in the dir I want to add
```
[streama@rpi ~]$ ls -l /mnt/tosh2TB/media/                                                                                                                                                    
total 24                                                                                                                                                                                      
drwxr-xr-x 163 plex plex 8192 Oct  7 23:05 movies                                                                                                                                             
drwxr-xr-x   6 plex plex   94 Sep 29 00:41 music_video
drwxr-xr-x  22 plex plex 4096 Sep 29 00:34 sport
drwxr-xr-x  85 plex plex 4096 Oct  6 23:25 tv
```

Is there a way to see what the app is specifically complaining about?  I've tried with symlinks and get the same result.  If I put /tmp it works so I know it's not *every* dir, just the one I want :)

There's no java exception in the terminal so I'm guessing this is by design ( ? )

**Comment by oliver-cfc** [comment]
My mistake... looks like the dir needs write permission.  I thought read only would be good enough

**Comment by Jeronimo95** [comment]
Sounds like it's doing the same check as what it does for the uploads folder. The local video folder probably only needs read access.

**Comment by oliver-cfc** [comment]
That makes sense.  I only found code for uploads when searching github for the error message.

I agree not requiring write perms for local dirs the way to go but it seemed like it was doing as it was told so should this be an enhancement rather than a bug?

**Comment by nomnomtom** [comment]
I use a read only nfs for my local dir and I managed to get it to work by setting the local path to /whatever/upload and than mounting my nfs to that folder -- I can choose whatever file I want when adding movies. It doesn't seem to have any negative side effects at all.

**Comment by dularion** [comment]
> Sounds like it's doing the same check as what it does for the uploads folder. The local video folder probably only needs read access.

agreed. its on the list for the next round of fixes

**Comment by stemy2** [comment]
I have the problem. The folder exists and has the correct permissions (access for everybody), but i still have the error message.
