### ISSUE TITLE
Thumbnails don't show

### ISSUE THREAD

**Issue by muhanadali100** [dularion/streama#455]
![desktop screenshot 2017 10 24 - 12 22 44 23](https://user-images.githubusercontent.com/31727156/31938475-50e3664e-b8c0-11e7-8c22-90e5f502b760.png)

the photo is don't show

**Comment by muhanadali100** [comment]
![desktop screenshot 2017 10 24 - 13 52 21 33](https://user-images.githubusercontent.com/31727156/31939336-ad218b32-b8c2-11e7-9863-0125a60ba965.png)

Continue Watching is same proplem

**Comment by muhanadali100** [comment]
![desktop screenshot 2017 10 24 - 13 53 44 85](https://user-images.githubusercontent.com/31727156/31939368-c6e3e77c-b8c2-11e7-93be-5b8755181784.png)

Discover Movies is running ok 

but Continue Watching and Movies in Content don't show the photo

**Comment by muhanadali100** [comment]
thumbnails don't show if i don't use the movie dbi key and add a movie manual like photo and information and the realase data

**Comment by Jeronimo95** [comment]
It needs theMovieDB API key to get the thumbnails automatically. If you manually create the movie you can edit it after the initial creation to upload the thumbnails.
