### ISSUE TITLE
Docker: Error response from daemon: Invalid Container Name ("streama")

### ISSUE THREAD

**Issue by emresaracoglu** [dularion/streama#457]
Hello

I installed 2 times but I get same this error:

`docker: Error response from daemon: Invalid container name (“streama”), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed.`

How I can fix?

**Comment by gkiko** [comment]
You tried this one? https://hub.docker.com/r/gkiko/streama/
What command do you run?

**Comment by emresaracoglu** [comment]
Yes, right now I installed, thank you.
I made all the settings but I get this error at the end of the video upload

> An internal Server error occured.

What could be the solution?

**Comment by sachgits** [comment]
please put up the command that your running on terminal so we can try to understand this from all angles

**Comment by emresaracoglu** [comment]
Hi @sachgits 

I tried two install methods.

1. Method (not working for me)

`docker run -d --name=“streama” -p 8080:8080 -p 4000:4000 -v /data:/data -e “MYSQL_HOST=localhost -e “MYSQL_PORT=3306” -e “MYSQL_DB=myusername_db -e “MYSQL_USER=myusername_db -e “MYSQL_PASSWORD=myPassword whatever/streama`

2. Method (@gkiko give to me)

This method is working.

`docker run -it -p 8080:8080 gkiko/streama`

**Comment by gkiko** [comment]
@emresaracoglu 
Container is attached to the bash session so you can see grails stack trace in your bash window.

**Comment by sachgits** [comment]
i think your having problem with " since the error is indicating that docker did not parse them to get to the name streama. the reason why it not doing so cant tell or its a bug somewhere on docker's part since it should just try running without the double quotes ""

**Comment by emresaracoglu** [comment]
@sachgits Yes I tried but I can not go to the site this time

> Screen: Page not found

If you want, you can close this issue..
we can not go solving.

**Comment by sachgits** [comment]
no need to close this as the issue is not yet solved am working on a Dockerfile to build an image to run streama once am done ill pass it to you so you can try

**Comment by gkiko** [comment]
@emresaracoglu What steps should I take to reproduce the bug?

**Comment by emresaracoglu** [comment]
Today I completely erased the Docker from server and I installed again.

*SSH*
```
[root@server ~]# sudo systemctl start docker
[root@server ~]# docker run -d --name=“streama” -p 8080:8080 -p 4000:4000 -v /data:/data -e “MYSQL_HOST=localhost” -e “MYSQL_PORT=3306” -e “MYSQL_DB=DB_Name” -e “MYSQL_USER=DB_UserName” -e “MYSQL_PASSWORD=DB_Password” whatever/streama
Unable to find image 'whatever/streama:latest' locally
latest: Pulling from whatever/streama
4d2e9ae40c41: Pull complete
a3ed95caeb02: Pull complete
7cf3e1cb1a34: Pull complete
57df89f6e18a: Pull complete
17f65c85feca: Pull complete
ba645fca1b7e: Pull complete
329dc42ad09c: Pull complete
19970c638b4e: Pull complete
2feac12e9416: Pull complete
eb375ca49574: Pull complete
984e8997efc9: Pull complete
44ba2f7de45e: Pull complete
Digest: sha256:939b49493786562e09d9ffd638d1acd55eac6889cd232dbe1d708eda86a1ac05
Status: Downloaded newer image for whatever/streama:latest
docker: Error response from daemon: Invalid container name (“streama”), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed.
See 'docker run --help'.
You have new mail in /var/spool/mail/root
[root@server ~]#
```

*Screen*

> This site can’t be reached

*My Server*

**Distro Name:** CentOS Linux release 7.4.1708 (Core)
**Kernel Version:** 3.10

**Comment by gkiko** [comment]
@emresaracoglu Do not use whatever/streama image! It's 2 years old. Instead use **gkiko/streama** and report the stack trace if there is one. You will see it in you bash session. Also explain all the steps that led to the bug

**Comment by emresaracoglu** [comment]
@gkiko I can close it now because it's resolved. I've done all the tests right now and it works fine with **gkiko/streama**
**Thank you!**
