### ISSUE TITLE
JDK in Ubuntu Docs

### ISSUE THREAD

**Issue by TheConnMan** [dularion/streama#46]
The base install of Ubuntu 14.04 doesn't include Oracle Java which is required to compile Grails. I ended up using the following script (along with some additions to `~/.bashrc`) to add the **JAVA_HOME** variable.

```bash
wget --no-check-certificate https://github.com/aglover/ubuntu-equip/raw/master/equip_java7_64.sh && bash equip_java7_64.sh
```

**Comment by dularion** [comment]
It gets auto-installed when installing tomcat7. Or didn't it, in your case? It did in all of my setups at least

**Comment by dularion** [comment]
Oh I get it now, Java gets auto-installed, but you need the JDK to create the war... hmmm. Ok, will add this line to the docu and reference you!

**Comment by dularion** [comment]
Please reopen if you believe that more info is required regarding JDK in the ubuntu tutorial.

**Comment by TheConnMan** [comment]
Looks great, thanks!
