### ISSUE TITLE
Error when adding bulk-items

### ISSUE THREAD

**Issue by LittlePinkel** [dularion/streama#460]
Hi! I keep getting internal server errors whenever I try to add multiple files (format is mp4). When I try to upload them it works, and adding per episode via the local file tab (browsing) it works perfectly. The terminal gives this output: https://pastebin.com/QCftVi9x. Is this fixable?

Thanks!

**Comment by LittlePinkel** [comment]
Fixed it myself by editing the BulkCreateService.groovy file and removing the log.debug(files) line in matchMetaDataFromFiles, line 36.

**Comment by dularion** [comment]
thanks mate, can you add a PR ?

**Comment by LittlePinkel** [comment]
Done!
