### ISSUE TITLE
An internal Server error occured.

### ISSUE THREAD

**Issue by fantom89** [dularion/streama#471]
Hello,

When I try create a TV show from file I have error:
> An internal Server error occured.

Here is a log: https://pastebin.com/70vKr8SM

And when I run app everytime is error:
> ERROR grails.boot.config.tools.ClassPathScanner - The application defines a Groovy source using the default package. Please move all Groovy sources into a package.

My system is Windows 10 x64, Java 1.8.0_151-b12 x86 (also checked x64), Streama v1.3.0_beta.

Regards

**Comment by Jeronimo95** [comment]
Try downloading a fresh copy of the streama.war from the releases and run it in its own folder (not directly from your downloads folder). Also for testing do not use an application.yml if you have one.

**Comment by fantom89** [comment]
I downloaded latest version and create own folder but still doesn't work, the same errors.

**Comment by Jeronimo95** [comment]
I can't replicate this. Also on Windows 10 x64, Java 1.8.0_151-b12.
Please provide what steps you take (from install to error).

**Comment by fantom89** [comment]
1. Downloaded latest version from release tab
2. Created a folder and moved the streama-1.3.0_beta.war
3. Opened command line and entered **java -jar streama-1.3.0_beta.war**
```
C:\Users\Fantom\Desktop\streama>java -jar streama-1.3.0_beta.war
INFO streama.Application - Starting Application on Fantom-PC with PID 8940 (C:\Users\Fantom\Desktop\streama\streama-1.3.0_beta.war started by Fantom in C:\Users\Fantom\Desktop\streama)
DEBUG streama.Application - Running with Spring Boot v1.4.4.RELEASE, Spring v4.3.6.RELEASE
INFO streama.Application - The following profiles are active: production
ERROR grails.boot.config.tools.ClassPathScanner - The application defines a Groovy source using the default package. Please move all Groovy sources into a package.

Configuring Spring Security Core ...
... finished configuring Spring Security Core

INFO streama.Application - Started Application in 36.246 seconds (JVM running for 38.808)
Grails application running at http://localhost:8080 in environment: production
```
4. Set **Upload Directory** (C:\Users\Fantom\Desktop\) and **Local Video Files** (C:\Users\Fantom\Desktop\video)
5. In **Manage Content** -> **TV Shows**, clicked **Bulk-Create from file(s)**
6. Selected some files and pressed **Run Matcher**
![image](https://user-images.githubusercontent.com/33670610/32885124-d39992a8-cabc-11e7-8d04-6457f258b42c.png)

That's all, after that I have error 

> An internal Server error occured.

 and site is frozen. I checked also in the work on the laptop and the same problem.

**Comment by Jeronimo95** [comment]
Alright yes, this is reproducible with those steps. We'll have to look into it.

@dularion Any ideas? Appears to be happening in BulkCreateService.

**Comment by SkweeZEdit** [comment]
Same problem here.
Issue closed with the same problem : https://github.com/dularion/streama/issues/460
Maybe do a new release would be great. Kind of hotfix.

**Comment by Jeronimo95** [comment]
Thanks for pointing that out. I'll post a new release when I get home this evening.

**Comment by Jeronimo95** [comment]
Hot fix released
https://github.com/dularion/streama/releases/tag/1.3.1_beta

**Comment by fantom89** [comment]
Now I can't run the program.
Here is a log: https://pastebin.com/UZvtvjf7

**Comment by SkweeZEdit** [comment]
Same.

**Comment by Jeronimo95** [comment]
So sorry. Not sure what happened to it... I've uploaded `streama-1.3.1_beta_fix.war` to the v1.3.1 release page, please give that a go.

**Comment by fantom89** [comment]
Now it works.

**Comment by SkweeZEdit** [comment]
Hello. No match found on all movies ...

**Comment by Jeronimo95** [comment]
Your movies might not be named how the default matcher expects. 

The two defaults are 
**Movie**: `/^(?<Name>.*)[_.]\(\d{4}\).*/`  
**TvShow/Episode**: `/^(?<Name>.+)[._]S(?<Season>\d{2})E(?<Episode>\d{2,3}).*/`   

In order to customize the regex, just add the regex in the bottom of the application.yml like so:
```yml
streama:
  regex:
    movies: ^(?<Name>.*)[_.]\(\d{4}\).*
    shows: ^(?<Name>.+)[._]S(?<Season>\d{2})E(?<Episode>\d{2,3}).*

```
