### ISSUE TITLE
.MKV upload doesn't work 1.3.3

### ISSUE THREAD

**Issue by muhanadali100** [dularion/streama#474]
![desktop screenshot 2017 11 25 - 03 42 15 45](https://user-images.githubusercontent.com/31727156/33225956-b03745b2-d192-11e7-891d-40fef9e3c05c.png)
![desktop screenshot 2017 11 25 - 03 50 04 04](https://user-images.githubusercontent.com/31727156/33226006-c02ab19c-d193-11e7-98f3-d9c091f3413d.png)

proplems :
1- uploding movies & .mkv don't work & .mp4 work
2- if i add movie info and movie pictures from the Internet Thumbnails don't show in Contiunes Watching and manage content & if i use movie dbi key to add movie info and movie pictures thumbnails show everywhere
3- In some movies like (Acts.Of.Vengeance.2017.1080p.WEB-DL.DD5.1.H264-FGT.mkv) when i uploaded and playing the movie sound does not work

version 1.3.3

**Comment by muhanadali100** [comment]
![54](https://user-images.githubusercontent.com/31727156/33226046-f17c62f8-d194-11e7-98b4-d4f828e276f4.png)

![51](https://user-images.githubusercontent.com/31727156/33226058-6074bfd4-d195-11e7-8726-9ee210718db1.png)

the proplem just if i add movie info and picture info from my pc don't use moviedb api key

**Comment by Jeronimo95** [comment]
Your MKV File may not totally HTML5 compatible.

>Unfortunately, the application does not convert your videos for you (yet!). In order to get the videos working, you might have to convert them yourself. For compatible codecs, see [HTML5 Video Browser Support](https://en.wikipedia.org/wiki/HTML5_video#Browser_support)
If your videos won't play, make sure that they are HTML5 compatible. A quick and easy test is to open a new empty browser-tab and drag&drop your video file in. If it shows up in a player, then it's a compatible format. If it downloads, it's incompatible.

As for not being able to upload MKVs, you probably need to add their MIME Type in your application.yml. For the default list see:
https://github.com/dularion/streama/blob/master/grails-app/conf/application.yml#L126

**Comment by muhanadali100** [comment]
the movie mkv in 1.3.0 can uploaded successful
but in 1.3.3 error

**Comment by muhanadali100** [comment]
i fixed it 

https://drive.google.com/file/d/1mQGgRpEf0aPn-G3V88zl-8PbI3QkUCKz/view?usp=sharing

**Comment by dularion** [comment]
What did you change?

**Comment by dularion** [comment]
oh i see,   uploadtypes:['video/h264', 'video/mp4', 'video/mpeg', 'video/quicktime', 'video/webm', 'video/x-ms-wm', 'video/x-ms-wmv',
              'video/x-msvideo', 'image/bmp', 'image/gif', 'image/jpeg', 'image/pjpeg', 'image/png', 'image/svg+xml',
              'image/x-icon', 'image/x-png', 'application/x-subrip', 'text/plain', 'text/vtt']

**Comment by dularion** [comment]
regarding the sound not playing, thats a common issue when files are h264 videoCodec but not AAC audiocodec. It is important that the files are BOTH at the same time. at least thats what always worked for me. Before uploading, there is a way to test this: open a new empty browser-tab and drag&drop your video file in. If it **shows up** in a player and **there is sound**, then it's a compatible format. If it downloads, it's incompatible for both. if it only plays the video, but without sound, the audio codec is incompatible.

**Comment by Jeronimo95** [comment]
Closing as a dup of #487 and since this is fixed in 1.4.1 RC2.
