### ISSUE TITLE
File Manager - Menu Missing

### ISSUE THREAD

**Issue by videojock** [dularion/streama#475]
The page menu at the foot of the File Manager is missing after ver 1.2.1
![footerpagemenu](https://user-images.githubusercontent.com/33978168/33229227-e4b05664-d1c2-11e7-88ef-051323f8880a.jpg)
Operating on Windows Server

**Comment by dularion** [comment]
yea this is an issue, sorry about that. hopefully fixing soon

**Comment by dularion** [comment]
check https://github.com/dularion/streama/releases/tag/v1.4.1RC
