### ISSUE TITLE
Streama Android App

### ISSUE THREAD

**Issue by videojock** [dularion/streama#476]
Images do not appear in 'Other Videos'

Cannot clear 'Continue Watching' video and only displays one video item in this section

Season menu links do not work and too close together for less nimble fingers! 

Great work!

**Comment by dularion** [comment]
Fixed in v0.1.0!

**Comment by videojock** [comment]
Streama Android App
Dashboard doesn't scroll down
Search works on the the top right hand menu not on the left hand menu slide out
Images in 'Other Videos' are the Background images not the Poster images.
Transport on video player doesn't hide smoothly and not totally full screen.
Android Ver 6.00 HTC Phone

Chrome Browser
The File Menu Manager still has the bottom menu bar missing when the page is full so you cannot move to the next page in this version.
