### ISSUE TITLE
For interest : make streama works automatically when running Ubuntu

### ISSUE THREAD

**Issue by muhanadali100** [dularion/streama#477]
Download this file : 
https://drive.google.com/file/d/1HRIkI0Au9cTObSNgmfBk3kZSxXKAwVAO/view?usp=sharing

copy and paste in /etc/init.d/

Make the script executable :

cd /etc/init.d/
chmod a+x streama

update-rc.d streama defaults

Reboot the machine and make sure that streama has started.

Note: Open the file you downloaded and change the address of the streama if you have another Dir like : 
Streama_DIR=/var/www/streama/  >>> Streama_DIR=/var/www/streama1/

**Comment by dularion** [comment]
This is cool! but why are you letting ppl download from a drive-document? feels a bit strange. Is that a differently compiled streama.war?

**Comment by dularion** [comment]
also, I'd like to invite you to write this as a wiki page here on streama-github :)

**Comment by dularion** [comment]
I dont think you need a custom streama, the streama in my releases is also executable, so you could just do the same with that, no?

**Comment by muhanadali100** [comment]
1- I don't use a custom streama , This is a shortcut to the main streama address
2- I use the google drive because he is the best in my country
3- the executable for the shortcut streama , not for the main streama

also , you can try it

**Comment by Jeronimo95** [comment]
I've made a wiki page for running as a service: https://github.com/dularion/streama/wiki/Running-as-a-service-(autostart)-on-Ubuntu-15-or-higher
