### ISSUE TITLE
Latest Android App Update Etc

### ISSUE THREAD

**Issue by videojock** [dularion/streama#478]
Streama Android App
Dashboard doesn't scroll down
Search works on the the top right hand menu not on the left hand menu slide out
Images in 'Other Videos' are the Background images not the Poster images.
Transport on video player doesn't hide smoothly and not totally full screen.
Android Ver 6.00 HTC Phone

Chrome Browser
The File Menu Manager still has the bottom menu bar missing when the page is full so you cannot move to the next page in this version.

**Comment by dularion** [comment]
> Dashboard doesn't scroll down 

which android device are you using? which streama version are you using on the server?

**Comment by dularion** [comment]
ive extracted the scrolling issue here https://github.com/dularion/streama/issues/495

**Comment by dularion** [comment]
fixed in next release of the app
