### ISSUE TITLE
Uploading Issues with V1.4.0

### ISSUE THREAD

**Issue by videojock** [dularion/streama#479]
Videos are not being processed after uploading with the red pop up 'internal error'.
Windows server R2012 v2
V1.2.1 is the most stable in my environment at the moment

**Comment by Jeronimo95** [comment]
Can you post your server log?

**Comment by videojock** [comment]
This is on a Windows 2012 R2 server, not sure where the log is you require? I am also testing this on a Ubuntu 16.04 server tomorrow and let you know.

There has been no feed back to my earlier issue about the green page menu in the File Manager which disappeared after version  1.2.1, so you cannot access past page 1.

Finally is the ere a way to convert the Stream H2 database to SQL easily?

Thanks.

**Comment by Jeronimo95** [comment]
This should work for windows:

1. Stop the Strema server.
2. Open a command prompt window in the folder where you're streama_[version].war is.
3. Run `java -jar streama_[version].war > log.txt`.
4. Do the action that causes the error in streama.
5. Upload the log.txt so we can view it.

**Comment by muhanadali100** [comment]
just open the 1.4.0.war by 7-zip

remove [application.yml] in \streama-1.4.0_beta.war\WEB-INF\classes\application.yml

add this application.yml

https://drive.google.com/file/d/1mQGgRpEf0aPn-G3V88zl-8PbI3QkUCKz/view?usp=sharing

and it's work

**Comment by dularion** [comment]
heres a short tutorial on this: https://github.com/dularion/streama/wiki/Getting-started#12-how-to-use-sql-instead-of-h3-as-a-datastore

**Comment by videojock** [comment]
Have now updated to the latest RC release and all seems to be well and far more stable.
Other issues have been resolved in this release too - Excellent

**Comment by dularion** [comment]
wonderful!

**Comment by Jeronimo95** [comment]
Closing as issues are resolved in 1.4.1 RC2.
