### ISSUE TITLE
Player doesn't continue playing after scrubbing to a moment.

### ISSUE THREAD

**Issue by Serubin** [dularion/streama#48]
After moving the scrubbing bar (time bar?) in a movie, the player seems to hang. After reloading the movie started playing as expected.

**Comment by dularion** [comment]
Oh, that is new ... Do you see any JS errors or Server errors?

**Comment by Serubin** [comment]
Unforunately not

**Comment by dularion** [comment]
Ok, What browser are you using? What codec does the file have? Is it just one file or all files? If it does not affect all files, can you detect anything that the failing ones have in common? If you open the Dev Console and look at the network, what are the request-headers in the request right after you've used the srubber?  If all of these questions are a bit hard for you to answer (if you're not a frontend dev), are you willing to transfer one of the files to me that are giving you trouble?

**Comment by Serubin** [comment]
I've only been uploading mp4 files, but it happens on all of them. The website just calls save.json with these headers: 
```
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Cookie:grails_remember_me=c2VydWJpbkBzZXJ1YmluLm5ldDoxNDM5NzAxNzk3NjIxOjdiMDllY2FlZjQxMzMwNWM3ZTA2ZTBiMjZkZGM0N2Y3; JSESSIONID=7130D48789E65956DFB391F11CDA1C78
Host:titan.serubin.net:8080
Referer:http://titan.serubin.net:8080/
User-Agent:Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36
X-Requested-With:XMLHttpRequest
```
No errors that I see in the console. I can send you a file if needed.

**Comment by dularion** [comment]
I don't mean the save action, I mean playback. When scrubbing in the video, it should do several requests to the mp4 file, always with a Range header with an offset.

**Comment by Serubin** [comment]
Hmm, It seems to be working now... If it comes up again I'll re-open this.

**Comment by dularion** [comment]
Ok
