### ISSUE TITLE
I just couldn't get the application to run on window's

### ISSUE THREAD

**Issue by Nedks** [dularion/streama#481]
I tried for ages and ages. I really did but it doesn't help that I have almost no knowledge of cmd or power shell so I can't actually understand any errors I am getting or basic mistakes.

It would be great if someone could make a quick video tutorial of how of them doing it or new instructions which a 5 year-old could understand (cause that's what I need, sorry). I am fairly tech savey and understand it but don't know anything about cmd or power shell. Thank you if anyone can help me.

**Comment by haze135** [comment]
I understand you, i'm a newbie too.
i create a .bat file in the same directory of streama.war with this code `java -jar java -jar streama-1.4.0_beta.war` (if you have downloaded this version).

**Comment by jacobdu215** [comment]
IMO its better to run off a dedicated linux system, if not then maybe create a VM? It would create a nice isolated environment.

**Comment by Jeronimo95** [comment]
It should just be a matter of installing java, downloading streama, running streama.

https://github.com/dularion/streama/wiki/Getting-Started-(Windows)
