### ISSUE TITLE
Dashboard Movie/Show pagination

### ISSUE THREAD

**Issue by siteripper** [dularion/streama#482]
Hello,

with a big database (4000-5000 movies and ~500 TV Shows) the dashboard takes really long to load and gets slow. It would be better if you could do a setting where you can define how many movies are shown and have a pagination menu for browsing.

This is also relevant for the manage content menu.

**Comment by jacobdu215** [comment]
What's your hardware? If you get the main system running on SSD and then the media files into a different dir on separate drive should in theory allow you to speed things up. Or make an SSD as a cache drive?

**Comment by dularion** [comment]
I agree with this ticket! I will add pagination in the next release

**Comment by dularion** [comment]
check https://github.com/dularion/streama/releases/tag/v1.4.1RC
