### ISSUE TITLE
No actions can be performed after inactivity

### ISSUE THREAD

**Issue by shaynethiessen** [dularion/streama#484]
After so many minutes of inactivity, you need to resign in to your account. However there is no visual cue that your login has timed out. This can be frustrating for users because then they click on a movie, but nothing happens until they refresh the page and sign in again.

Could an automatic redirect to the login page be added for when their session has timed out?

**Comment by Jeronimo95** [comment]
I haven't reproduced this yet. But I do agree, if the system is logging you out, but not telling you you're logged out, it's an issue.

**Comment by shaynethiessen** [comment]
I'm running Streama on Debian, using Firefox as my web browser. This happens after leaving Streama open in the browser, idle, for a few hours.

**Comment by dularion** [comment]
yep, can reproduce!

**Comment by dularion** [comment]
done. will be in 1.5.0
