### ISSUE TITLE
Add mkv to upload-types

### ISSUE THREAD

**Issue by muhanadali100** [dularion/streama#487]
upload same issues just add [video/x-matroska + application/octet-stream] to upload-types in application.yml
![untitled](https://user-images.githubusercontent.com/31727156/33799158-e37eb310-dd36-11e7-988b-4989c7be3093.png)

download this files
[application.zip](https://github.com/dularion/streama/files/1545079/application.zip)
extract
copy application.yml to \streama-1.4.1RC.war\WEB-INF\classes\

and it's working

![desktop screenshot 2017 12 09 - 23 21 15 33](https://user-images.githubusercontent.com/31727156/33799186-adb8f096-dd37-11e7-8cc3-6bf98b70014d.png)

**Comment by muhanadali100** [comment]
why you closed ? the fixed for 1.4.2

**Comment by Jeronimo95** [comment]
I closed it because you changed the title to fixed.

**Comment by muhanadali100** [comment]
I meant that the solution exists and must be in the next version

**Comment by Jeronimo95** [comment]
I'll add `video/x-matroska` to upload types in the next version. `application/octet-stream` should already be in there (or will be added in the PR dularion has open).

**Comment by Jeronimo95** [comment]
Closing as fixed in 1.4.1 RC2.
