### ISSUE TITLE
Can't upload image for episode

### ISSUE THREAD

**Issue by muhanadali100** [dularion/streama#488]
![desktop screenshot 2017 12 09 - 23 58 43 00](https://user-images.githubusercontent.com/31727156/33799463-4522779a-dd3d-11e7-8dc9-809bda69e6a4.png)

can't upload image for episode

**Comment by jacobdu215** [comment]
Click on the upload poster area? It should work. & If you have MovieDB API then it will grab both the image and the show/movie details and you'll also automatically be able to fetch episode information

**Comment by muhanadali100** [comment]
the poster upload work , but the image for episode not work

**Comment by dularion** [comment]
I'll check it out for v1.4.1
