### ISSUE TITLE
streama apk don't show the thumbnails with 1.4.1

### ISSUE THREAD

**Issue by muhanadali100** [dularion/streama#490]
1- streama app don't show the thumbnails in the 1.4.1 verison
![screenshot_20171210-190332](https://user-images.githubusercontent.com/31727156/33855232-6647de8a-ded5-11e7-97f1-30848dffdb5c.png)
![screenshot_20171210-190337](https://user-images.githubusercontent.com/31727156/33855234-66794baa-ded5-11e7-9c57-f9d18e57acf9.png)

2- Please make it [Allow anonymous access] in streama apk

**Comment by dularion** [comment]
1.4.1 isnt compatible with mobile yet, see release notes: https://github.com/dularion/streama/releases/tag/v1.4.1RC <https://github.com/dularion/streama/releases/tag/v1.4.1RC>
