### ISSUE TITLE
Android app won’t add server IP

### ISSUE THREAD

**Issue by jacobdu215** [dularion/streama#491]
So I installed the android app and it seems I can’t add my server IP, I don’t have a domain associated because I don’t feel like I really need it since it’s private. The add URL button is grayed out when I just put an IP, if I add http:// it just processes forever and when I add port 8080 like http://192.284.38.3:8080 (fake IP), it says invalid.. so how would I add a plain IP? It won’t let me add it without http and it won’t add when I put it.

**Comment by dularion** [comment]
hm, thats no good! thanks for reporting

**Comment by jacobdu215** [comment]
Any updates on this issue?

**Comment by dularion** [comment]
can I add you to my android beta testers? in that case, please give me your email address which you use on your phone to download apps in the playstore

**Comment by dularion** [comment]
Link to beta: https://play.google.com/apps/testing/dularion.streama

**Comment by jacobdu215** [comment]
@dularion Yea sure, I am using exroidgaming@gmail.com

**Comment by dularion** [comment]
with the link above you can actually install it without me adding your email

**Comment by jacobdu215** [comment]
@dularion ok well just downloaded it and it wont validate an IP still. I entered http://xx.x.xx.xxx and its just stuck on "Validating Domain..."

**Comment by dularion** [comment]
Ok thats good to know. Can you PM me the actual server address with some throwaway username & password? you can use https://gitter.im/

**Comment by jacobdu215** [comment]
@dularion ok send you a message with my server details

**Comment by dularion** [comment]
as discussed, you need streama v1.3.0 or later
