### ISSUE TITLE
Email Option On Windows Server

### ISSUE THREAD

**Issue by videojock** [dularion/streama#493]
What is the best solution to use with the email invite option on a Windows 2012 R2 server,as there is no Sendmail option?

I am running the latest RC2 release which is very stable on the Windows dedicated Server platform.

**Comment by Jeronimo95** [comment]
Does it not work. I can't find anything in the grails mail docs that have anything specific to windows. Do you get any errors when you try and send?

**Comment by dularion** [comment]
One solution is to use an external SMTP,
