### ISSUE TITLE
Android 8.1 - App Fails To Connect

### ISSUE THREAD

**Issue by huntertusk** [dularion/streama#494]
### Issue description
I configured the latest release of Stream (1.4) with an SSL certificate and DNS name for external use. I am able to view all content from any mobile device as well as any desktop/laptop machine using the browser.

When I download the app and try to connect using the same exact DNS entry as my browswer, I get an error:

OOPS...

Something seems to be wrong. 
Make sure you entered the right domain and that the server is up & running!

Also, I notice what appears to be an Android kernel alert:

"Request was denied for security"

### Steps to Reproduce

1. Download app
2. Enter in working DNS entry and click Proceed to Login
3. Error occurs everytime

### Expected Behaviour

I'm assuming I should be able to view all my content through the mobile app.

### Actual Behaviour

I get an error stating that the "Request was denied for security" and am unable to get past this screen.

### Environment Information

- **Operating System**: Android Oreo 8.1 (Google Pixel v1)
- **Streama version**: 1.4.1 RC2

**Comment by Jeronimo95** [comment]
Does it work using the IP address of the server?

**Comment by huntertusk** [comment]
It does not, same error.

**Comment by jacobdu215** [comment]
Think this is same issue as the one I have opened just very detailed: https://github.com/dularion/streama/issues/491

**Comment by dularion** [comment]
can I add you to my android beta testers? in that case, please give me your email address which you use on your phone to download apps in the playstore

**Comment by dularion** [comment]
oh wait, ok. I just released it with "Open Beta". So you guys should be able to see it. its *Release:	0.1.2*
