### ISSUE TITLE
Bulk Add RegExpr does not find match

### ISSUE THREAD

**Issue by ManuGithubSteam** [dularion/streama#497]
### Issue description
As Seen in the screenshots. the Bulk Add regexpr does not match the series files to the corresponding series despite use of consistent naming and fairly standard files name notation (from KODI).

### Steps to Reproduce

1. Rename test files like in the screenshots
2. Try Bulk add.

### Expected Behaviour

The matcher should find the corresponding series to the file name.

### Actual Behaviour

Matcher is not able to filter trough basic nameing shemes.

### Environment Information

- **Operating System**: Linux
- **Streama version**: 1.4rc3

How should the regexp be to find a match ? Or is more in deep stuff required like finding the "Season" folder beforehand ? 

TvShow/Episode: /^(?<Name>.+)[._]S(?<Season>\d{2})E(?<Episode>\d{2,3}).*/

![screenshot_20171219_134443](https://user-images.githubusercontent.com/3456994/34157996-1a149766-e4c4-11e7-8e7c-e3f2a357ea7d.png)
![screenshot_20171219_134513](https://user-images.githubusercontent.com/3456994/34157997-1a32f738-e4c4-11e7-828a-3114202a6e93.png)
![screenshot_20171219_134614](https://user-images.githubusercontent.com/3456994/34157999-1a50533c-e4c4-11e7-8446-f1f0533d9dd4.png)
![screenshot_20171219_134625](https://user-images.githubusercontent.com/3456994/34158000-1a6dfa04-e4c4-11e7-9fdb-2e088a5d77bd.png)
![screenshot_20171219_134635](https://user-images.githubusercontent.com/3456994/34158001-1a8cf6fc-e4c4-11e7-9758-8b3543b9fec3.png)
![screenshot_20171219_134723](https://user-images.githubusercontent.com/3456994/34158002-1aacda44-e4c4-11e7-840f-dbf11399e448.png)

**Comment by dularion** [comment]
Ah i see the issue. the regex matches only files that either use "." or "_" as a delimiter, not " ". ill provide instructions asap

**Comment by dularion** [comment]
Here you go: https://www.youtube.com/watch?v=KSuHf-HhSG8
