### ISSUE TITLE
please fix the sound proplem

### ISSUE THREAD

**Issue by muhanadali100** [dularion/streama#499]
Please fix the sound proplem

how can I change the video player ?

**Comment by ManuGithubSteam** [comment]
What problem do you have?
Can you describe a bit more ?

**Comment by muhanadali100** [comment]
Some movies when I upload and play audio do not work

**Comment by Jeronimo95** [comment]
This was discussed in #474

>regarding the sound not playing, thats a common issue when files are h264 videoCodec but not AAC audiocodec. It is important that the files are BOTH at the same time. at least thats what always worked for me. Before uploading, there is a way to test this: open a new empty browser-tab and drag&drop your video file in. If it shows up in a player and there is sound, then it's a compatible format. If it downloads, it's incompatible for both. if it only plays the video, but without sound, the audio codec is incompatible.  

&nbsp;

Please stop opening duplicate issues and in future please use the issue template.
