### ISSUE TITLE
Database direct edit

### ISSUE THREAD

**Issue by IZ44KPvP** [dularion/streama#503]
how i can edit .db file streama.mv.db and streama.trace ?

**Comment by dularion** [comment]
You mean like perform SELECT and UPDATE queries manually, like in mysql? assuming your url is localhost:8080, u can visit something like phpmyadmin (but a lot fewer functionalities!) here: http://localhost:8080/dbconsole

here is the official guide: https://docs.grails.org/latest/guide/conf.html#databaseConsole

**Comment by Guima001** [comment]
Muito interessante, porem ao realizar acesso desta maneira algo como aparece...

"desculpe você nao tem autorização para acessar esta pagina"

sabe oque pode ser? estou usando usuário de administrador para acesso

**Comment by IZ44KPvP** [comment]
O mesmo acontece comigo

**Comment by Jeronimo95** [comment]
Its seems the DB console does not work for some reason. I'm looking into it.
![image](https://user-images.githubusercontent.com/2177618/34504195-1bbebdae-f071-11e7-8303-8a2b67604576.png)

**Comment by Guima001** [comment]
Obrigado por verificar!

**Comment by Jeronimo95** [comment]
Okay, I've found the issue. The URL mappings were overriding the console. I've pushed a commit to master that fixes it (d30d5e528ebb987b6276b2a2a9cb9a910d22af46).

If you run in development mode the console is enabled by default. You can enable it in production by setting the below in your application yml:

```
environments:
    production:
        grails:
          dbconsole:
            enabled: true
```

You should only be able to access it if you're logged in as an admin. I still **wouldn't enable it in production unless necessary.**

**Comment by IZ44KPvP** [comment]
Eu consegui, mas quais são as informações que tenho que colocar nos seguintes campos:


![image](https://user-images.githubusercontent.com/19996738/34507336-20769ae2-f01c-11e7-9228-5851d554a996.png)

**Comment by Jeronimo95** [comment]
It depends on your environment and what you have set in your application.yml. 

By default in production it will be:

```
Generic H2 (embedded)
url: jdbc:h2:./streama
username: root
```

**Comment by dularion** [comment]
Thanks @Jeronimo95 !
