### ISSUE TITLE
Browse Button Overlaps Custom Logo

### ISSUE THREAD

**Issue by Shrinks99** [dularion/streama#505]
### Issue description
The browse button on the homepage overlaps custom logo images

![screen shot 2017-12-29 at 1 21 02 am](https://user-images.githubusercontent.com/5672810/34430764-926c520c-ec36-11e7-8aaf-3216955f635e.png)

### Steps to Reproduce

1. Create custom logo image larger than the one used by default
2. Upload to the sever

### Expected Behaviour

The browse button should ideally move based on the size of the custom logo.

### Actual Behaviour

Browse overlaps the custom logo.

### Environment Information

- **Operating System**: Ubuntu 17.10
- **Streama version**: 1.4.2

**Comment by dularion** [comment]
Thanks for reporting this! must've missed it. Will look into asap
