### ISSUE TITLE
Edição de Database manualmente

### ISSUE THREAD

**Issue by IZ44KPvP** [dularion/streama#508]
Recentemente abrir um tópico aqui perguntando como eu poderia editar manualmente o arquivo .db do Streama e me informaram que posso alterar as informações dele acessando urlserverstreama/dbconsole mas ao acessar essa pagina aparece uma mensagem parecida com "Você não possui permissão", mesmo com eu logado na conta de Administração.

**Comment by Jeronimo95** [comment]
Please don't open duplicate issues. I've replied on #503.
