### ISSUE TITLE
Registro/Login livre para visitantes

### ISSUE THREAD

**Issue by IZ44KPvP** [dularion/streama#509]
Você poderia adicionar uma opção nas configurações que permitiria o registro de novos usuarios um cadastro realizado direto pelo visitante

Google Translate:
You could add an option in the settings that would allow the registration of new users a register made direct by the visitor

**Comment by Jeronimo95** [comment]
Duplicate of #298.

This isn't implemented. If people could just sign up and access your content, cant that get you in trouble? Better to do invite-only.
