### ISSUE TITLE
Como extrair e compactar o arquivo streama.war

### ISSUE THREAD

**Issue by IZ44KPvP** [dularion/streama#510]
Como posso extrair e compactar o arquivo streama.war se eu usar o Winrar o mesmo fala que o arquivo está corrompido
 
How can I extract and compress the file streama.war if I use Winrar it says that the file is corrupted

**Comment by dularion** [comment]
Can you please add issues in English? Otherwise the searchability of our issues kinda gets broken

**Comment by dularion** [comment]
So here is how you do it: 

Use the provided gradle wrapper in the root
Call it like ./gradlew assemble
(That's for Unix terminal)
For Windows there should be a gradle.bat, there you can call `gradle.bat assemble'
It'll be created in build/libs/ or something similar
