### ISSUE TITLE
Can't play video on 1.5.0 on mobile app

### ISSUE THREAD

**Issue by EdgardoMartin** [dularion/streama#532]
I updated to version 1.5.0 and I can't play the videos in the mobile application. But if I run version 1.4.2 you can see the videos.

**Comment by Jeronimo95** [comment]
Any errors on the sever console or on the app?

**Comment by EdgardoMartin** [comment]
It is the same mistake that I appeared with the first mobile versions. The image is from another post published on the github of the mobile app.

https://user-images.githubusercontent.com/33255132/32223754-6d14f316-be1d-11e7-83f3-3764ceb39992.png

**Comment by EdgardoMartin** [comment]
In version 1.4.2 everything works normal. The problem is when I upgrade to the 1.5.0.

**Comment by Jeronimo95** [comment]
I can reproduce this. We will look into it ASAP.

**Comment by EdgardoMartin** [comment]
If it helps. The videos I have are mp4 (x264 - aac). Thank you

**Comment by dularion** [comment]
Sorry, Ive had a major deadline at work and ive been a bit burned out. but ill get back to bug-fixing asap !

**Comment by dularion** [comment]
alrighty, should be fixed in new  0.1.7 release of the app!
