### ISSUE TITLE
Ability to add files from local source

### ISSUE THREAD

**Issue by gammelon** [dularion/streama#533]
My use case: Streama has access to my movies which lie in its /data folder.
It would be a nice feature if I were able to add the files from there without reuploading (and effectively duplicating) them.
Moreover some sort of automatic detection of movies and shows would be fancy.
Example: Folder "ThatAwesomeShow" has five subfolders named "Season X" in which the individual episodes are situated ("S01E01...."). Streama now tries to automatically detect as many movies/shows as possible and reports the files where this did not succeed or something like that, you get the idea.
That would be very cool!
Keep up the good work, we need free software like this!!! :)

**Comment by dularion** [comment]
Hi, what you're describing already exists! You need to configure a local directory in the settings, that can be used instead of uploading. And then a button will be added where you can add movies and shows from those files via regex name matching! I have a gif somewhere, I'll check

**Comment by dularion** [comment]
Here you go : https://github.com/dularion/streama/releases/tag/v1.2.3_beta

We should add this info to the Readme

**Comment by gammelon** [comment]
Oh missed it, thanks!
