### ISSUE TITLE
MKV format and HTML5

### ISSUE THREAD

**Issue by guruiteu** [dularion/streama#534]
Hello, can you please add a option to upload and play MKV format video files.
Can you please somehow fix that its posible to play streama videos on SMART TV browser (It loades wideo whery long and shows the error with HTML5 TV Dosn't run on android)

It would be whery helpful i'm using streama at home on my PC hosted, but more i would like to kick back and watch on tv. Thanks!

**Comment by guruiteu** [comment]
Alos would be greate AVI. Most files that i have on my PC are AVI or MKV. MP4 is less in interent.

**Comment by Jeronimo95** [comment]
Currently Streama video support is browser dependent. Video transcoding is something we want to implement, see #440.
