### ISSUE TITLE
Needs a serious improvement in performance and resource use

### ISSUE THREAD

**Issue by CardealRusso** [dularion/streama#538]
This thing will never be more of a github child's play with such an absurd use of resources.

**Comment by moritzmoritz** [comment]
Okay. Go for it! Make it shine :p

**Comment by Jeronimo95** [comment]
Thanks for your input! I'm going to close this now because it's not really helpful and your tone is a little demeaning. :)

**Comment by dularion** [comment]
I can say that Java is very demanding for resources. However, once it runs, it runs solidly and is very secure. There was talk about porting it to nodejs, but until nodejs comes out with a solid framework I dont see that happening. But you are welcome to help improve this software!

**Comment by viluon** [comment]
Sorry for necroing, but I just installed Streama on a Raspberry Pi model 3 B+. Its memory usage is fine, but the startup time is over 180 seconds. What's the reason behind this? I've had other Java/Spring-powered software start much faster on the same device (even media servers).
