### ISSUE TITLE
proplem with remove files

### ISSUE THREAD

**Issue by muhanadali100** [dularion/streama#558]
![desktop screenshot 2018 01 22 - 00 59 23 68](https://user-images.githubusercontent.com/31727156/35267952-ea8a4366-0038-11e8-9162-f50ccfb1109f.png)

**Comment by Jeronimo95** [comment]
We'd really appreciate if you'd use the template and provide a more detailed description of the issue.

**Comment by muhanadali100** [comment]
In the file manager .. There are some files that have been deleted and replaced by the audio version I tried to delete them but I discovered that I can not delete anything and show me this problem when I try to delete something

**Comment by dularion** [comment]
What is the server output when this internal server error appears? please try to clear the server output before or (with a couple of empty lines) mark the time BEFORE u press the button, so that afterwards you only get the relevant log outputs. please use pastebin for the log
