### ISSUE TITLE
403: When trying to access a file

### ISSUE THREAD

**Issue by camelCaseD** [dularion/streama#56]
I keep getting a 403 when trying to access a file:
![streama403](https://cloud.githubusercontent.com/assets/1644022/9031391/259e2666-3967-11e5-8e06-d29b7aa89219.PNG)

My logs are clean with no errors.

**Comment by dularion** [comment]
403 - are you sure you are still logged in in the background? The session is sort of short, ticking "remember me" makes it much longer

**Comment by camelCaseD** [comment]
I just logged in again and checked "remember me" and I still get a 403 but when I access the url directly for getting the file I get the following, "Sorry, you're not authorized to view this page". I should be authorized as I am logged in as the admin and haven't changed any of the default permissions.

**Comment by dularion** [comment]
can you paste the entire url?

**Comment by camelCaseD** [comment]
I just figured it out, the url get's name spaced into streama so 'localhost:8080/' becomes 'localhost:8080/streama' so anything accessed as 'localhost:8080/streama/index' thows an unauthorized error just like I've been seeing with retrieving a file. I have been accessing streama as 'localhost:8080' instead of the name spaced  version.

**Comment by dularion** [comment]
yea, that should be fine. you just have to set it in the settings. Did you do that?

**Comment by camelCaseD** [comment]
Ya I did, but I don't remember doing that. Thanks for helping though.

**Comment by dularion** [comment]
By default it gets populated with the /streama namespace, because that is most likely how most people will be running it. So if it differs, just change it there
