### ISSUE TITLE
Episode Image Stopped Working

### ISSUE THREAD

**Issue by videojock** [dularion/streama#560]
The image for episodes has stopped working after updating to ver 1.5.0, same with ver 1.5.1.
The image uploads and displays under content manager and also can be found in the file browser.
When trying to save the image after upload  'internal error' and the image does not display when viewed on the dashboard and has now also disappeared on the content manager view.

Is there any character limit on the description text and could this cause the problem if exceeded?

**Comment by videojock** [comment]
I am still getting this problem with manually adding episode images. This info is in the log and the image is there. 
DEBUG grails.app.controllers.streama.FileController - FILE_IN_FS_NOT_FOUND
This only started to happen after updating to the latest version.

**Comment by dularion** [comment]
cant reproduce currently. Can you try recreating the issue on the new demo-server? http://94.130.181.211:8080/ username: "demo-user", password "demo-user"

**Comment by videojock** [comment]
Since your update 1.5.2 yesterday, the problem has stopped.
I will report back if I have the error again.

**Comment by dularion** [comment]
Oh cool!
