### ISSUE TITLE
Skip upload, scan directory to create content

### ISSUE THREAD

**Issue by ridhwaans** [dularion/streama#566]
**Feature request**
Is there a Manage Content functionality to skip manually uploading files, instead have streama scan a local folder (i.e. /mnt/c/streama/Videos from settings path) and use whatever files there are and map them to movies or shows. Streama can probably be tweaked so that it doesnt upload a copy of the original file but somehow  uses the original file & location to create a movie.

**Comment by Jeronimo95** [comment]
You can set a local directory and then use the bulk add files feature. This won't re-upload any items and use the files right from the set directory.

**Comment by dularion** [comment]
Here is the (new) readme section about this: https://github.com/dularion/streama/blob/master/README.md#accessing-existing-files
