### ISSUE TITLE
Add Sample Application.yml to the Getting Started Wiki Page

### ISSUE THREAD

**Issue by mongomay69** [dularion/streama#572]
Currently in the getting started it says to download the .war and the application.yml but nowhere that i could see was the application.yml linked. I just feel that it should be added for easy startup

2. download the .war and application.yml
Download the latest war from the releases page... Suggestion: use /data/streama for the yml and the war and /data/streama/files for the uploaded files.

Where i found it after some looking:
https://github.com/dularion/streama/blob/master/docs/sample_application.yml

**Comment by Jeronimo95** [comment]
Agreed. Thanks for pointing that out. I've updated the section.
