### ISSUE TITLE
StaleObjectStateException occurred when processing request

### ISSUE THREAD

**Issue by lhw** [dularion/streama#59]
Appears after uploading a 2.5GB on a fairly slow machine. Upload and indexing were not affected however: 
```
| Error 2015-08-03 18:12:48,502 [http-bio-8080-exec-3] ERROR errors.GrailsExceptionResolver  - StaleObjectStateException occurred when processing request: [POST] /streama/video/uploadFile.json
Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [streama.Movie#8]. Stacktrace follows:
Message: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [streama.Movie#8]
    Line | Method
->>  126 | $tt__uploadFile in streama.VideoController
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|    198 | doFilter        in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . .  in grails.plugin.cache.web.filter.AbstractFilter
|     53 | doFilter        in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|     49 | doFilter . . .  in grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter
|     82 | doFilter        in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|   1145 | runWorker . . . in java.util.concurrent.ThreadPoolExecutor
|    615 | run             in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . . . . in java.lang.Thread
```

**Comment by dularion** [comment]
Hmm.. did you by any chance edit the same movie in another browser tab while it was uploading? what happens in the upload-code is that I first fetch the movie from the db, then i process the uploaded file, and then I add it to the movie and save the movie. if the movie was updated between fetching the movie and saving the movie, then this error occurs. If you know how many times you actually edited/saved the movie, take a look into the database, table video. If the movie was only created and then the file was added, the version number should be 1. if it is higher than one, then something else was triggered that saved the movie.

**Comment by lhw** [comment]
I thought I added a comment. Anyway.
It was most likely related to me switching to the settings page to check if the upload continues in the background and then starting the same upload again when I thought it didn't. Corner case but it still shouldn't disrupt a transaction.

**Comment by dularion** [comment]
hmmm.. i see what you mean. But if you navigated away from the upload I think it cuts the connection, because the upload is dependant on you staying on the page. Kind of like you wouldnt navigate away from a wetransfer upload.

**Comment by dularion** [comment]
please reopen if you have any more issues with this
