### ISSUE TITLE
429 MovieDB Rate Limiting: Bulk-Create causes Internal server error

### ISSUE THREAD

**Issue by ahirschberg** [dularion/streama#597]
### Issue description
Bulk-Create results in MovieDB 429 errors very commonly, and the error message presented to the user offers no explanation, making it impossible to see what is going wrong without viewing the logs. 

Related to #311?

### Steps to Reproduce

1. Add a show with several seasons (such as Futurama)
2. Attempt to bulk-create episodes using the matcher
3. Click 'add all found matches'

### Expected Behaviour

The server should:
Present a helpful error message to the user informing them that rate limiting by MovieDB is occurring.
and, if possible to implement, queue the remaining files to add later.

### Actual Behaviour

A notification saying "Internal Server Error Occurred"

### Environment Information

- **Operating System**: Debian: `Linux as 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux`
- **Streama version**: 1.5.2

**Comment by Jeronimo95** [comment]
This is a known issue (#480). But since this is a more concise report and uses the issue template I'll keep this one open.

**Comment by dularion** [comment]
related https://github.com/dularion/streama/issues/498

**Comment by dularion** [comment]
So I have improved the error  handling in the above PR and it now ignores the error-causing episodes, so  theoretically the matcher can be run 2-3 times and all should be matched. however, I do want a queue as well, this is just a bubble-gum fix.

**Comment by dularion** [comment]
Alright! I added some basic API data caching! I hope this will fix the most obvious bugs with this! heres hoping :) will be in v1.6.0-RC1

**Comment by dularion** [comment]
see https://github.com/dularion/streama/releases/tag/v1.6.0-RC1
