### ISSUE TITLE
loginTarget issues

### ISSUE THREAD

**Issue by muhanadali100** [dularion/streama#605]
Proplem 
When I runnug the streama or login in or logout it's send me to loginTarget page automatically
1.6.0-RC1

![desktop screenshot 2018 04 06 - 12 03 18 97](https://user-images.githubusercontent.com/31727156/38413064-56a13080-3993-11e8-830d-d375402a3e1c.png)

**Comment by dularion** [comment]
try redownloading the RC1, the .war i uploaded last night was broken. sorry!
