### ISSUE TITLE
Domain and server management

### ISSUE THREAD

**Issue by benno1214** [dularion/streama#606]
### Issue description
Heyo, first off, awesome stuff you making here :)! second my issue is that i've been trying to get this up and running on a server, vultr ubuntu 16 server, now i can only go into the streama page by going "localhost" or the ip "xxx.xxx.xxx.:8080" but as i got a domain for it, is it poseble to add that domain for it? i've tried to first just go to the ip, without the port, but didnt work out, i've been checking around in some files and tried to edit the url in application file etc, didnt find anything. im kinda new to specielly groovy, and never even heard of it, im sorry if im asking a dumb or just out right wrong question here, but thanks in advance, and sorry for my grammar as well!

-benno1214

### Steps to Reproduce

1. go to localhost/ip of server and then use port 8080, that works fine.
2. go to only ip/the domain that is set to the ip of the server, doesnt work at all, nothing.
3. tried to edit applications and edit the url set of the application also tried to change ports and look into other files what i could find, nothing.

### Expected Behaviour
get the appliction working on the server ip/domain and not only localhost
### Actual Behaviour
only works on localhost:8080

or the server ip (server localhost) :8080 

### Environment Information

- **Ubuntu 16.04 x64**: TODO
- **1.5.2.war**: TODO
- **Custom streama build, describe customizations or provide link to fork (If Applicable)**: TODO
- **Container Version (If Applicable):** TODO

### Example Application / access to your live version

If avalible

**Comment by dularion** [comment]
Please refer to this doc: 
https://github.com/dularion/streama/wiki/FAQs#8-how-do-i-change-the-port
