### ISSUE TITLE
Move chat from Gitter to Discord

### ISSUE THREAD

**Issue by Jeronimo95** [dularion/streama#608]
I think Gitter sucks. Why are notifications not instant? It's supposed to be *instant message*. I also find that it is buggy and not nice to use in general. It would also be good to have multiple channels for development and support. 

This is why I think we should move the official chat to [discord](https://discordapp.com/). We can have channels for different topics, proper notifications, moderation tools, we can add bots for git notifications/new releases. Its all-round a better platform for conversation. The downsides I can see: it doesn't have login-via github, so you'll need to create an account; and getting people to move across.

If anyone has any opinions or other options I'd love to hear them.

**Comment by lclc98** [comment]
I would highly recommend discord, I use it for some of my projects, and I know software like OBS use it.

**Comment by dularion** [comment]
No objections here :)

**Comment by sourceskyboxer** [comment]
And Discord is asshole because it has bad friend of Facebook. I hate Discord I love Gitter
