### ISSUE TITLE
Hardlink uploaded video files

### ISSUE THREAD

**Issue by gkiko** [dularion/streama#65]
I've set up and played with Streama. Nice job :+1: 

It would be nice if attached videos weren't copied in `/data/streama`. Instead we could make a hard link to the original content and store it in `/data/streama`. This way no content will be duplicated in the file system.

**Comment by dularion** [comment]
is this related to https://github.com/dularion/streama/issues/66?

**Comment by gkiko** [comment]
It can be considered to be related issues. But there are several reasons "centralized" file storage could be better solution:

1. Torrent file names are incompatible with streama convention: like _[torrentname]eps1.0_hellofriend.avi[lang]_. Renaming a file to meet streama needs will break seeding.
2. It's centralized and the directory structure can be altered for our needs

**Comment by dularion** [comment]
But imagine the directory with your files was accessible through streama, and you could choose which files to attach to which media elements. In that case, no naming convention outside of streama would be broken, as streama would not rename any files that it not manually uploads somewhere.

**Comment by gkiko** [comment]
OK that sounds reasonable. So I have to map every file myself?
