### ISSUE TITLE
File-Browser for existing files on your harddrive

### ISSUE THREAD

**Issue by dularion** [dularion/streama#66]
In your settings you would then configure one location for manually uploaded files and one location for existing files. 

The directory with your files would then be accessible through streama, and you could choose which files to attach to which media elements. In that case, no naming convention outside of streama would be broken, as streama would not rename any files that it not manually uploads somewhere. It just uses the path to serve the file to the video player.

**Comment by JanWerder** [comment]
:+1: This would be great! 
Use case: My Streama Server is not in my network, and the files are attached via harddrive to the server. I have to re-upload the files, even though they already exist on the harddrive connected to the server.

**Comment by RackerJack** [comment]
any movement on this <3

**Comment by dularion** [comment]
Hi! So far I have not made any progress on this feature.  I've recently become a mother and so my time is a bit limited in these early weeks / months. But I'll try to get back to focusing on the project asap. Anyone who wants to implement this and throw me a pull request: feel free! :)

**Comment by z3ntu** [comment]
Congrats :)

**Comment by alucard0134** [comment]
does #200 fix this @dularion?

**Comment by dularion** [comment]
Yep!
