### ISSUE TITLE
Can't login to demo site?

### ISSUE THREAD

**Issue by Marak** [dularion/streama#67]
**If you would like to view a Streama-Demo, please visit the demo-website.**

http://46.101.209.74:8080/login/auth#/
username: demo@streama.com 
password: demo@streama.com

**Sorry, we were not able to find a user with that username and password.**

**Comment by dularion** [comment]
Hi! I just tried, and I can login fine! Can you make sure not to have any spaces before or after? I will also take a look and see if there is a space somewhere in the website, so that this does not happen anymore.

**Comment by dularion** [comment]
Please reopen if this does not solve the issue

**Comment by z3ntu** [comment]
Can reproduce on Chrome Android with OP's URL&credentials

**Comment by dularion** [comment]
actually right this very moment I cannot login either. I am restarting the tomcat on the demo server to see if that resolves it. Last night i got some weird emails too, as though it had rebooted or something. Will check it out.

**Comment by tux-00** [comment]
Ok on Firefox 39.0.3.

**Comment by Marak** [comment]
There seems to be an extra ` ` char in the user name login string. 

Probably was a copy and paste error from the site.
