### ISSUE TITLE
Forked Grails VM exited with error

### ISSUE THREAD

**Issue by NickBehrends** [dularion/streama#7]
After running run-war (windows) I get 

`Running Grails application`

Followed imediately by 

`Forked Grails VM exited with error`

I have the Java path set up properly, as well as `GRAILS_HOME` (I can even create a Grails project). SO seems to hint at a code error and it is seemingly preventing the app from running. Any ideas?

**Comment by InfernoZeus** [comment]
Can you post a more complete error log, or is that it?

**Comment by NickBehrends** [comment]
Error occurred during initialization of VM
Error: could not create the Java Virtual Machine.
COuld not reserve enough space for object heap
Error:A fatal exception has occurred. Program will exit.
Forked Grails VM exited with error.

Sorry, new to Java, definitely not my choice language.

**Comment by InfernoZeus** [comment]
Looks like a memory shortage issue maybe. How much do you have free before
trying to start it?

**Comment by NickBehrends** [comment]
computer has 16g of ram and an 8 core 2.5 processor.

**Comment by dularion** [comment]
You could try the following: 
Run the JVM with -XX:MaxHeapSize=256m (or any big number), and possibly -Xmx512m
here is a stackoverflow: http://stackoverflow.com/questions/4401396/could-not-reserve-enough-space-for-object-heap

**Comment by NickBehrends** [comment]
That did fix it, thanks much. Can't wait to try this.
