### ISSUE TITLE
If user is deleted from streama database doesn't update

### ISSUE THREAD

**Issue by alallier** [dularion/streama#71]
If you delete a user in streama the database doesn't update and remove that user, so if you go to create that user again, it say's you can't create the user because they already exist.

**Comment by dularion** [comment]
yea, that is on purpose for constraint-issues. I just set a deleted-flag currently. I guess what I could do, is rename the username when this happens... The problem with deleting the entire user would be to also recursively delete their chosen favorite genres, their viewing-status etc.. From my work I am just used to never actually deleting records from the database, as this makes things undoable..

**Comment by alallier** [comment]
Why don't you want to delete all attributes to the user when you chose to delete them?

**Comment by dularion** [comment]
as I said, I am used to it from work. If the whole deleting-action was a mistake and you want to undo, then you cannot do that if you actually delete all the records. It's a best-practice that I learned. But in the case of the unique username i see the issue. I could add a uuid to the end of the username on deleting.. 
I actually don't care much either way. I will mull it over and fix it, either by deleting the user and all associated records, or by adding a uuid to the username when deleting.

**Comment by alallier** [comment]
Okay I understand, well either way works, keeping all the records sounds better actually so in the case of accidental deletion everything is there, just as long as we can re-add the user back. Maybe on deletion you could provide a checkbox that says delete all users data, otherwise we default to just keeping it?

**Comment by dularion** [comment]
not a bad idea :) will go for that.

**Comment by dascandy** [comment]
I would in case of a non-deleting database have a separate table for mapping a username to an actual user, where this username mapping would be invalidated. Then you can create a new mapping for a second user with the same name, and if you then try to undelete the first you get the conflict. And then you can get creative with fixing it.

**Comment by dularion** [comment]
I am not sure I understand you correctly. Do you mean that we have one table, called user, containing among other the things the username with the uniqueness constraint, and another table with stores that same username and an id-reference to the user-table? and then once we delete the user, he gets flagged etc, the username is changed, but the original name stays stored in the other table? 

My approach would have been to leave the username as is, and to append a uuid, so it would be something like *user1@my-streama.com* before delete, and after it would be *user1@my-streama.com_9da548f2-40d3-4950-9c71-9485f4f97e0a* that way, if you want to "undelete" you can simply rename the username to something that makes sense via for instance phpmyadmin. I mean, undeleting is sort of an edge case, but this way it would be possible. 

What would be the benefit of having an extra table like you are suggesting?

**Comment by admwx7** [comment]
A user would then be simply a unique ID that could be bound 1-1 through a
second table to a unique username, deleting a user would be as easy ad
deleting that row in your second table.  Would make handling the historical
user a lot easier, however you lose the username after that point and can't
recreate a user unless that person knows the unique ID associated with the
account.  I like the idea proposed by @dularion personally.

**Comment by alallier** [comment]
So do I @admwx7
