### ISSUE TITLE
Right redirection after login

### ISSUE THREAD

**Issue by z3ntu** [dularion/streama#77]
for example I tried going to http://46.101.209.74:8080/#/player/25?sessionId=d22e0753-117d-b3ba-1abb-cfcc19028407 (with the unique session id shared playing) in another browser, was redirected to the login page but then not back to http://46.101.209.74:8080/#/player/25?sessionId=d22e0753-117d-b3ba-1abb-cfcc19028407

**Comment by dularion** [comment]
Yea... that is actually a really important point. Thanks!
