### ISSUE TITLE
Exit fullscreen button does not work

### ISSUE THREAD

**Issue by z3ntu** [dularion/streama#79]
Windows 8.1, Chrome Canary. Entering fullscreen works

**Comment by dularion** [comment]
confirmed! Will look into it

**Comment by z3ntu** [comment]
I have the feeling that I am finding so many bugs and opening so many issues ^^ but it's nice to help!

**Comment by dularion** [comment]
It is nice to get help! Sometimes when you work on an application for a while you get sort of blind for all the bugs or you don't even test certain things anymore. So I am glad for any "tester" that is interested enough in the application to continue testing, even if bugs appear

**Comment by z3ntu** [comment]
Also, a error message for non-existent sites would be nice instead of instant redirection... i think...

**Comment by dularion** [comment]
Is this a related issue? also: can you give me an example? what non-existing site were you trying to reach and how come you tried to access a non-existing site?
