### ISSUE TITLE
Interesting project

### ISSUE THREAD

**Issue by dantheman213** [dularion/streama#8]
I find your project pretty interesting. How long have you been working on it? I came up with a local based app solution called channelmagic which I uploaded to my own repo which acted liked a TV based channel based setup. You change the channel and get random programming selected for you and they all move along in time so you can flip through channels and watch random content like you would on a traditional set top box. I really enjoyed the experience but thought that a networked server would be a better route. I ultimately came across Plex ( https://plex.tv/ ) and kinda skipped over the idea.

Anyhow, I was wondering what features are in the works or what you're looking to implement in the near future. I may be able to assist.

**Comment by dularion** [comment]
Sounds rad!! 
It took be about 4 days to get this together. But the road-map is full of additional features that I want to add. Here is the list: 

- folder-crawling to discover files as an alternative to uploading them manually
- Synchronized watching between 2 or more browsers (synchronized play/pause etc)
- Video-conversion via ffmpeg through a cron-job for multiple html5-compatible formats
- Functionality to add subtitles while viewing
- Functionality to switch between multiple video-files (for instance for different video-quality)
- Chromecast Support
- Better iOS Support
- (Maybe porting it over to NodeJS)

**Comment by dantheman213** [comment]
Thanks for the info. How likely are you to port the project to NodeJS?

Was there a reason to select Grails over NodeJS originally? How much effort would it take to port over the code?

**Comment by dularion** [comment]
It's pretty likely that I'll do it eventually if the demand is great enough. The reason why I chose Grails is because I program so fast with it.. it would have taken me 4x as long to do the same in nodejs... and there are some things i wouldnt know how to do in nodejs which I would need to figure out first. But in all honesty, for someone who is good with nodejs it would be pretty easy, because all that is needed are several CRUD-REST endpoints for the different database commands... the rest is anyway done in AngularJS.

**Comment by dularion** [comment]
Ive opened a new issue [https://github.com/dularion/streama/issues/20](https://github.com/dularion/streama/issues/20) with the nodejs-port as a subject. I will close this one if that is ok?

**Comment by Copytalky** [comment]
I find this project to be really cool as well! I do have a few suggestions for changes. I feel that for maximum compatibility the project could be done in reactJS and nodeJS. Netflix themselves use react for all of their platforms. Netflix also now uses a form of 'webkit' for cross platform app architecture. They've modified webkit to utilize react. They've labelled their webkit modification as 'gibbon'. I suggest anyone really interested in how netflix UI works checkout https://www.youtube.com/watch?v=eNC0mRYGWgc

You've done an amazing job so far with this project, you yourself said it didn't take you too long to get the prototype going and with it being in the early stages I highly recommend a switch to react/nodejs and plans for a 'gibbon' style webkit would be ultra sweet to have for cross-platform compatibility. 

It's my two-cents worth :) love what you've done so far! I'm pretty newb with react/nodejs so I can't fork this and really do much on my own but i thought I'd throw out some suggestions while the project is in it's early stage of development.

Also with the transcoding for html5 compatibility, I think if upon scanning a drive for media, it should find files and evaluate whether they're html5 stream compliant, if not add them to a queue for transcoding conversion. This could be a feature that the user sets up on initial setup, where it can be setup in two ways:

- User just wants to have streama read media files and transcode live - not affecting original files
- User wants to have streama read media files and convert them permanently to html5 compliant streaming formats.

Typical users can likely get away with just transcoding live. However here's a few things most people don't consider:

- power savings, I'm a huge advocate of saving power and to have a system always transcoding live would mean i'm having my machine process files over and over again potentially, when they should be processed once.

- households that utilize streama for family use, aka 2-4+ people in a home utilizing streama at the same time. One household server that hosts all media content and has to transcode live so many streams would potentially be a bottleneck for a lot of people out there with low budget server systems, not to mention again the power usage would be quite high in comparison to if the user had transcoded all media files upon import.

hope I've been helpful with my suggestions :) I'll keep monitoring the project and see what I can pitch in on.

**Comment by dantheman213** [comment]
Hmm, I'm more in favor of live transcoding. Or maybe have an option that will allow permanent conversion during off time. If you have a huge media 4TB+ of data then transcoding the whole thing can be very costly in terms of processing power and storage space.

This wasn't closed by the way so I'm closing the ticket and any further discussion should take place at:
https://github.com/dularion/streama/issues/20
