### ISSUE TITLE
try -> catch at mysql login

### ISSUE THREAD

**Issue by z3ntu** [dularion/streama#82]
That when it fails to connect / sign in , either stop the program immediately or start the server (with a warning in the console) and when navigating to the site, display an error message

**Comment by dularion** [comment]
I am not sure I can do that, that is something that grails does automatically. Maybe someone else here knows how

**Comment by Kickball** [comment]
As per [this page on groovy exception handling](http://www.tutorialspoint.com/jdbc/jdbc-exceptions.htm) you should do this: 

```
try {
  //Perform initial SQL connection here
} catch (SQLException se){
  //This code will run when an SQL Error occurs
  se.printStackTrace();
}
//Rest of the non SQL connection code.
```

**Comment by Jeronimo95** [comment]
The server doesn't start if it set for mysql and it can't connect. It displays an error like `com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure` which seems fairly explanatory.
