### ISSUE TITLE
Easy Integration with Couchpotato and Sickbeard

### ISSUE THREAD

**Issue by alallier** [dularion/streama#83]
A possibly really cool and handy feature to streama, would be easy integration with [couchpotato](https://couchpota.to/) and [sickbeard](http://sickbeard.com/index.html).

I know a media crawler is in the works and that could cover this idea. As in cocuchpotato downloads something and then streama would crawl a folder, find the new file and automatically add it to streama's dashboard.

But to extend upon this idea, if there could be some cool way to integrate these projects into streama it could add a really cool touch. Something like streama would have a tab to click on that said couchpotato the server would be all configured for you and then you could just add a movie through couchpotato (while being in streama) and basically it would become just set and forget. That way you wouldn't have to juggle around 3 different servers.

This may be out of the scope of streama itself but I though I would atleast mention my idea to see what people think

**Comment by dularion** [comment]
I had never heard of both of these services before. Interesting. I will look into this down the road. Thanks!

**Comment by Jeronimo95** [comment]
Closing as we're not going to support features that may directly violate copyright laws.
