### ISSUE TITLE
NodeJS Support

### ISSUE THREAD

**Issue by mrozbarry** [dularion/streama#84]
In accordance with [a post from reddit](https://www.reddit.com/r/webdev/comments/3f1ya3/i_recently_created_this_open_source_selfhosted/ctlf8au), I will help with NodeJS support if that is a path you would like to take.

This issue is mostly so I remember if I have some free time.  I will try and do some work o a branch and make a pull request at some point, but if not, someone else is free to take up this mantle.

**Comment by dularion** [comment]
We are already on it, see this issue: https://github.com/dularion/streama/issues/20

**Comment by dularion** [comment]
Looking forward to your contributions!!
