### ISSUE TITLE
Distributed Servers

### ISSUE THREAD

**Issue by JanWerder** [dularion/streama#86]
The application should be able to fetch files from multiple servers. That way different users can contritube to one central system.

**Comment by coxley** [comment]
@JanWerder Surely this is better suited for the underlying system to handle - NFS or some other fs mounts. They do their job really well and leaves it simple at the application level.

**Comment by dularion** [comment]
Let me know if the approach suggested by @coxley is not what you had in mind. Until then, I will close this issue.
