### ISSUE TITLE
Including Harddrives

### ISSUE THREAD

**Issue by fb13** [dularion/streama#87]
I have a collection of recorded video files from TV, my digitized Bluray and DVDs and private videos on two hard disks. What I do not want is to upload those files into a Streama application that uses a postgres database on one disk, since then I would need to buy another bigger harddrive.

Use Case: I want to watch my home collection on my TV via WLAN. I do not want to switch between the two hard drives and I want to see cover images for my Bluray and DVD movies.

Are you planning on integrating an option to select videos from attached disk volumes?

**Comment by z3ntu** [comment]
So you want to have two (or more) seperate locations for files?

**Comment by dularion** [comment]
is this related to https://github.com/dularion/streama/issues/66 ?

**Comment by fb13** [comment]
Yes, I want to have different locations for files and it looks like that this really is a duplicate of #66!

One side question before closing it: Would it be possible to stream 1080p HD videos from my streama app deployed on a raspberry pi via DLNA to my TV or would I get awful laggs?

**Comment by dularion** [comment]
no DLNA support currently, there are some discussions regarding this though, see https://github.com/dularion/streama/issues/58. Regarding lags: not sure how DLNA does it, but I am hosting streama remotely and 1080p works great, in my case it depends on my local download and the upload capacity of the server. But again, not sure how DLNA does it.
