### ISSUE TITLE
Add non-themoviedb shows

### ISSUE THREAD

**Issue by erasche** [dularion/streama#91]
I have some norwegian shows and I'd like to add those to streama. As far as I can tell I can only create a show from the UI if it's found in their API.

![add-show](https://cloud.githubusercontent.com/assets/458683/9841178/4cde1026-5a62-11e5-8fdb-f4def8826748.png)

It'd be nice if an `Add manual show` button (or similar) option shows up if the search isn't found.

**Comment by dularion** [comment]
Thanks for the good use-case! Didn't even come to my mind :) I will add this functionality soon!

**Comment by alecnunn** [comment]
Fantastic!  This will be a good feature to have to add video courses that I have downloaded.

**Comment by Bitsnoxx** [comment]
In the meanwhile you could add the TV Show to themoviedb https://www.themoviedb.org/tv/new

**Comment by coxley** [comment]
Not sure the demand for it, but could be nice to have a "Media Info" plugin/loader API so it's easier to add functionality for other projects similar to themoviedb. There are some that are better suited for Anime content, foreign ones, etc.

I haven't looked at your code close enough to know what that would "cost", so just food for though. :)

**Comment by asmartin** [comment]
+1

This would be nice for home videos as well, or obscure videos that aren't available on themoviedb.org

**Comment by dularion** [comment]
Ok, I've added basic functionality for this now. When creating a new show, there is now a button "add manually", which will switch to a manual input form. Once created, a custom poster image can be uploaded and episodes can be added manually. Please let me know if this works for you guys and if you wish for any further enhancements to this feature.

**Comment by dularion** [comment]
please reopen if anything is still missing

**Comment by asmartin** [comment]
I tested this out and it looks like it will work well, thanks!
