### ISSUE TITLE
video formats supported?

### ISSUE THREAD

**Issue by tnguyen14** [dularion/streama#93]
I intend on digitize my DVD collection and expose them with streama. What kind of file formats are supported? 

Also, how should the data upload directory be organized?

**Comment by tnguyen14** [comment]
I just saw this https://github.com/dularion/streama/wiki/Local-Streama-Setup#video-playback
So basically WebM and MP4?

**Comment by dularion** [comment]
Best would be h264 with AAC audio encoding. Thats what I always use, and it works great! WebM works great too, though I have not used it yet. And for firefox, you want ogg theora.

**Comment by tnguyen14** [comment]
@dularion thanks. So for the same video, I should have it be exported to different formats in order for it to work across browsers?

Also, how should the videos be organized in the data directory?

**Comment by tnguyen14** [comment]
I think I was confused before. Streama will actually do the uploading and organizing itself of the videos, right? So it's not like I would be putting the videos somewhere and streama would read from it.

**Comment by admwx7** [comment]
I believe there is a task out to support linking to external media, as well
as hard links to media already on a server, the original upload format was
a search for the media locally then upload it to streama through the ui

**Comment by tnguyen14** [comment]
I just tried using Handbrake to encode a video to h264 and AAC for audio. Yet, when I upload the video to streama, I get this error:

`
There seems to be a problem adding the video-file to the player. This is most likely due to a codec-problem. Try converting it to a compatible HTML5 codec, remove the currently attached file and re-add it. If the codecs are fine, check the error log of the server.
`
Is there any suggestion on what I could do?

**Comment by tnguyen14** [comment]
I followed the guide you have here https://gist.github.com/dularion/6237d651c385d2552916, using the same command. I ended up with the same error as well..

**Comment by dularion** [comment]
This should not be happening if you chose AAC and h264. Did you use the command line or handbrake GUI?

**Comment by dzomb** [comment]
Also getting this error with MP4 files.  They play when I open them in chrome, but I receive the same error as @tnguyen14 from the app.  Going to try converting them in handbrake to mp4/h264 w/ aac and will post the results. Using the handbrake gui

**Comment by dzomb** [comment]
no luck - but i found that im getting a 403 in the console 
![image](https://cloud.githubusercontent.com/assets/8173014/12605875/cc48dd16-c496-11e5-818d-d63e33e05cfd.png)

**Comment by dzomb** [comment]
fixed it - my base url had a slash after the port number, removing that solved my problem

**Comment by emanuelkufrin** [comment]
Also have problem with some mp4 files, audio not working on google chrome android for example. On desktop working fine, on mozilla firefox on android also working fine. Checked with ffmpeg, all videos and tv series are mp4 h264, and audio is aac mp4. And 70% movies and tv series are working, 30% of them which are same coded and everything, video working, subtitle working, but audio not. Any solutions? @dularion
