### ISSUE TITLE
docker container not working

### ISSUE THREAD

**Issue by the4ndy** [dularion/streama#96]
I launched a fresh Ubuntu 14.04 VM, install Docker and mysql-server and ran the docker command from the install instructions and while the container starts and runs and an namp scan shows port 8080 open and Apache Tomcat as the service running on that port, in a chrome browser from a machine on the same LAN it attempts to connect and eventually times out. I can provide any debug material needed but I don't know what I am doing wrong. I swear not usually this incompetent :disappointed:

**Comment by admwx7** [comment]
What URL are you using to connect?

**Comment by the4ndy** [comment]
it is an ubuntu server 14.04 VM so there is no GUI so i access it via another linux box on the same LAN at the URL 10.0.0.7:8080 I have tried in Chrome and Firefox. after a reboot of the machine i can "connect" to the server but the page that i get in my browser is empty, no source no nothing :(

**Comment by admwx7** [comment]
That IP looks all kinds of wrong, but run ifconfig on the server and use
that IP, if that's actually it then all is good. The only other possibility
is that your router firewall is blocking connections. Though a blank page
doesn't make sense in that case.

**Comment by the4ndy** [comment]
Why does that IP not look right? My private LAN is on the 10.0.0.0/24 subnet and I have statically assigned 10.0.0.7 to my Ubuntu VM. I apologize if I did not make this clear before, this is being done entirely on my private LAN. I will tackle opening this server up to the web when the time comes. If the app does not run on a local network I can move ahead with giving it a live IP and making it web facing, just let me know. 

Is there any sort of Log or output I can provide that might help you discover what is going on? I have also tried accessing the web app via the localhost:8080 URL from the GUI-less server using a console based web browser (lynx) but it provides the same result, a blank page or timeout.

Could there perhaps be some configuration needed in Tomcat that is preventing this from working? I install tomcat via apt-get install tomcat7 and follow any other instructions explicitly stated in the directions, but beyond that, I do not touch Tomcat or MySQL at all (as I am not certain if tinkering will break the app, though my plan is to tinker once the app works and see what custom settings I can apply without breaking the functionality of the app).

Again, my apologies for being difficult, you have been a great help. Thanks!

**Comment by the4ndy** [comment]
The issue I believe is that the database is not created. I do not know if you need to create the database or if docker creates it for you, that at least to me was not clear in the instructions and I am for sure a beginner at this. I intend to try to make my own sql db and then run the docker command and see if that works....i will report back with my findings. And i would very much like to help by improving the documentation / instructions for installing via docker (as well as via remote server).

**Comment by gkiko** [comment]
closing in favor of #197
