### ISSUE TITLE
http://localhost:8080/streama is a blank page - commandLine says server is running.

### ISSUE THREAD

**Issue by SamCousinsGB** [dularion/streama#98]
![image](https://cloud.githubusercontent.com/assets/12578919/10773160/bf257a32-7cf1-11e5-88f5-99149536c114.png)

![image](https://cloud.githubusercontent.com/assets/12578919/10773172/d13a838e-7cf1-11e5-9af0-1eb9882b13c2.png)

**Comment by dularion** [comment]
In your console I can see that the application is actually but running properly, you can see that there are errors and that the driver for the db connection exited with errors. To help you debug a full stacktrace is required.

**Comment by dularion** [comment]
Is this issue still open?

**Comment by gkiko** [comment]
I recall having similar problem but can't remember how I fixed it. Keep it open for some time

**Comment by Azizoufy** [comment]
I had the same problem while setting up a new password to the mysql database. The solution is to not set a password to mysql or edit the grails-app/conf/Data Source. groovy file

**Comment by dularion** [comment]
Reopen if the problem persists.
